### ISSUE TITLE
Crash when piping file into external programm

### ISSUE THREAD

**Issue by palango** [helix-editor/helix#1024]
### Reproduction steps

Open https://raw.githubusercontent.com/raiden-network/scenario-player/master/README.rst
Select all (`%`), pipe it to a shell command (`|`), run `rg oo`.

This crashes with
```
RUST_BACKTRACE=full hx README.rst
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Line index out of bounds: line index 26, Rope/RopeSlice line count 6', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.3.1/src/slice.rs:338:41
stack backtrace:
   0:        0x10b16f1a1 - __mh_execute_header
   1:        0x10b18ef4b - __mh_execute_header
   2:        0x10b169c1a - __mh_execute_header
   3:        0x10b170d85 - __mh_execute_header
   4:        0x10b170967 - __mh_execute_header
   5:        0x10ac8297f - __mh_execute_header
   6:        0x10b171496 - __mh_execute_header
   7:        0x10b170f0e - __mh_execute_header
   8:        0x10b16f617 - __mh_execute_header
   9:        0x10b170e7a - __mh_execute_header
  10:        0x10b1c56df - __mh_execute_header
  11:        0x10b1c57c5 - __mh_execute_header
  12:        0x10ad59901 - __mh_execute_header
  13:        0x10ad5abb6 - __mh_execute_header
  14:        0x10ad5a4d7 - __mh_execute_header
  15:        0x10ad611bf - __mh_execute_header
  16:        0x10acba8e3 - __mh_execute_header
  17:        0x10ad4a4a1 - __mh_execute_header
  18:        0x10ac8a914 - __mh_execute_header
  19:        0x10ac5dfa9 - __mh_execute_header
  20:        0x10ac725a9 - __mh_execute_header
  21:        0x10ac7b3d3 - __mh_execute_header
  22:        0x10ac66d0a - __mh_execute_header
  23:        0x10ac5f376 - __mh_execute_header
  24:        0x10ac6da21 - __mh_execute_header
  25:        0x10b17199a - __mh_execute_header
  26:        0x10ac66e09 - __mh_execute_header
```

### Environment

- Platform:  macOS 12.0.1
- Helix version: 0.5.0
Log file is empty.

**Comment by pickfire** [comment]
Seemed like your output is missing debug info. Here's mine. 1132b7088a853f1edac451a34ad1cbbba03e1f26 helix v0.5.0-122-g1132b70

<details>
<summary>trace</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Line index out of bounds: line index 78, Rope/RopeSlice line count 6', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.3.1/src/slice.rs:338:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: ropey::slice::RopeSlice::line_to_byte
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.3.1/src/slice.rs:338:9
   5: helix_term::ui::editor::EditorView::doc_syntax_highlights
             at ./helix-term/src/ui/editor.rs:138:25
   6: helix_term::ui::editor::EditorView::render_view
             at ./helix-term/src/ui/editor.rs:78:26
   7: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
             at ./helix-term/src/ui/editor.rs:1086:13
   8: helix_term::compositor::Compositor::render
             at ./helix-term/src/compositor.rs:156:13
   9: helix_term::application::Application::render
             at ./helix-term/src/application.rs:186:9
  10: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:316:13
  11: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:208:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  13: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:617:9
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  15: hx::main_impl::{{closure}}
             at ./helix-term/src/main.rs:118:21
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  17: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/park/thread.rs:263:54
  18: tokio::coop::with_budget::{{closure}}
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/coop.rs:106:9
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  20: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  21: tokio::coop::with_budget
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/coop.rs:99:5
  22: tokio::coop::budget
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/coop.rs:76:5
  23: tokio::park::thread::CachedParkThread::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/park/thread.rs:263:31
  24: tokio::runtime::enter::Enter::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/runtime/enter.rs:151:13
  25: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/runtime/thread_pool/mod.rs:77:9
  26: tokio::runtime::Runtime::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.1/src/runtime/mod.rs:463:43
  27: hx::main_impl
             at ./helix-term/src/main.rs:120:5
  28: hx::main
             at ./helix-term/src/main.rs:42:21
  29: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</summary>
