### ISSUE TITLE
Problems with typescript-language-server

### ISSUE THREAD

**Issue by joshi4** [helix-editor/helix#103]
setup: I have installed typescript-language-server with`npm install -g typescript-language-server`

command to run: `RUST_BACKTRACE=full hx file.ts` 

output: 

~~~
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(Error { code: InternalError, message: "Request initialize failed with message: The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined", data: None })', helix-lsp/src/lib.rs:213:69


stack backtrace:
   0:        0x107468bc4 - std::backtrace_rs::backtrace::libunwind::trace::h0e344f93e1be12b3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x107468bc4 - std::backtrace_rs::backtrace::trace_unsynchronized::h547096f273f197d3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x107468bc4 - std::sys_common::backtrace::_print_fmt::h46deca35c22bc084
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x107468bc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x107486d0e - core::fmt::write::h367e10cc391177e1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:        0x1074649d6 - std::io::Write::write_fmt::h69f760cf0ceceb64
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:        0x10746ad69 - std::sys_common::backtrace::_print::h06c56467d8f0565c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10746ad69 - std::sys_common::backtrace::print::h83e6ec856bd254a6
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10746ad69 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:        0x10746a850 - std::panicking::default_hook::hf6b37b6d4ff1b717
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:        0x10746b3d5 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:        0x10746af15 - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:        0x107469028 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10746ae7a - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:        0x1074aa56f - core::panicking::panic_fmt::h84e4b5f5d5160f07
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:        0x1074aa475 - core::option::expect_none_failed::h5c27880b225cac16
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
  16:        0x1071c5ec1 - helix_lsp::Registry::get::hb2d58e605161cf74
  17:        0x107108e1f - helix_view::editor::Editor::open::h1fd141572b484dc9
  18:        0x107009eee - hx::application::Application::new::h23b60fd62ab70357
  19:        0x10703ab9e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd05e3b34368e44e5
  20:        0x107051260 - tokio::runtime::thread_pool::ThreadPool::block_on::h041ba11287310c9b
  21:        0x106fc91dd - tokio::runtime::Runtime::block_on::he5053f89c2ab840f
  22:        0x106fed71d - hx::main::hd180c249a6130dcd
  23:        0x10706858a - std::sys_common::backtrace::__rust_begin_short_backtrace::h2828ac4124c87be8
  24:        0x1070685b1 - std::rt::lang_start::{{closure}}::h2bcc212421600d08
  25:        0x10746b744 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b22ce68aa2879c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  26:        0x10746b744 - std::panicking::try::do_call::h51a4853c94b1bdea
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  27:        0x10746b744 - std::panicking::try::ha45bc5eab1f103eb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  28:        0x10746b744 - std::panic::catch_unwind::h191bc002afc126a7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  29:        0x10746b744 - std::rt::lang_start_internal::h0c37a46739a0311d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  30:        0x106fed849 - _main
~~~

**Comment by archseer** [comment]
I think I fixed this in the latest master (https://github.com/helix-editor/helix/commit/8d6fad4cac65083a0b08e49391c579ec793bc8f3) can you give it another try?

**Comment by joshi4** [comment]
Thanks works perfectly now !
