### ISSUE TITLE
Crash when trying to insert text from lsp

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#11350]
### Summary

I am using pylsp with codeium via the helix-gpt lsp. When I see an autocomplete and hit tab and then enter to insert it, helix crashes.

### Reproduction Steps

 

I tried this:

1. `hx myfile.py`
2. start writing a signature for a function
3. select the lsp autocompletion.

I expected this to happen:

Autocompletion inserted.

Instead, this happened:

thread 'main' panicked at helix-core/src/transaction.rs:483:9:
Positions [(47, Before)] are out of range for changeset len 0!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: helix_core::transaction::ChangeSet::map_pos
   3: helix_view::document::Document::apply_impl
   4: helix_view::document::Document::apply_inner
   5: helix_view::document::Document::restore
   6: helix_term::ui::completion::Completion::new::{{closure}}
   7: <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::handle_event
   8: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::handle_event
   9: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
  10: helix_term::compositor::Compositor::handle_event
  11: helix_term::application::Application::run::{{closure}}
  12: tokio::runtime::park::CachedParkThread::block_on
  13: tokio::runtime::runtime::Runtime::block_on
  14: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-07-27T20:16:10.449 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(8)), original request likely timed out
2024-07-27T20:16:15.213 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(15)), original request likely timed out
2024-07-27T20:16:15.258 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(16)), original request likely timed out
2024-07-27T20:16:28.563 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(13)), original request likely timed out
2024-07-27T20:16:30.557 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(14)), original request likely timed out

```
</details>

### Platform

Void Linux

### Terminal Emulator

blink / mosh / tmux

### Installation Method

source

### Helix Version

24.07-71-g9b65448f

**Comment by sbromberger** [comment]
Here's a full backtrace:

```
thread 'main' panicked at helix-core/src/transaction.rs:483:9:                                                               
Positions [(392, Before)] are out of range for changeset len 0!                                                              
stack backtrace:                                                                                                             
   0:     0x55dfce5d3c51 - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec                                 
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtra
ce/libunwind.rs:93:5                                                                                                         
   1:     0x55dfce5d3c51 - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8                             
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtra
ce/mod.rs:66:5                                                                                                               
   2:     0x55dfce5d3c51 - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23                                         
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:
5                                                                                                                            
   3:     0x55dfce5d3c51 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b9178
4c                                                                                                                           
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:
22                                                                                                                           
   4:     0x55dfcd8543dc - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5                                                   
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9           
   5:     0x55dfcd8543dc - core::fmt::write::ha37c23b175e921b3                                                               
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21        
   6:     0x55dfce5cf98e - std::io::Write::write_fmt::haa1b000741bcbbe1                    
   7:     0x55dfce5d3a34 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:
5
   8:     0x55dfce5d3a34 - std::sys_common::backtrace::print::hb982056c6f29541c                             
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:
9
   9:     0x55dfce5d5773 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55dfce5d54b1 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55dfce5d5db4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h87b887549356728a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  12:     0x55dfce5d5db4 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
  13:     0x55dfce5d5b5e - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  14:     0x55dfce5d4126 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170
:18
  15:     0x55dfce5d5902 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  16:     0x55dfcd754075 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  17:     0x55dfcdb2c342 - helix_core::transaction::ChangeSet::map_pos::hc3775fca33702634
  18:     0x55dfce2a8e24 - helix_view::document::Document::apply_impl::hec2c222e80aeb840
  19:     0x55dfce2a9cfd - helix_view::document::Document::apply_inner::hb9a89d1375187eca
  20:     0x55dfce2aad91 - helix_view::document::Document::restore::h90f5fc087bca280a
  21:     0x55dfcddfa8d4 - helix_term::ui::completion::Completion::new::{{closure}}::h42a8f138d371eae3
  22:     0x55dfcddfb8d1 - <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::handle_event::h1bf9bce43b53b
b26                                                                                                                          
  23:     0x55dfce16b5e8 - <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::handle_event::haa7d4b12e31
b993a                                                                                                                        
  24:     0x55dfce165734 - <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event::hff20ca33
d9a4535b                                                                                                                     
  25:     0x55dfce158aca - helix_term::compositor::Compositor::handle_event::hfb594358bd38dc2f                               
  26:     0x55dfce34418e - helix_term::application::Application::run::{{closure}}::hc367e5757c593be2                         
  27:     0x55dfce35902d - tokio::runtime::park::CachedParkThread::block_on::h1075cfeb71a3f667                               
  28:     0x55dfce3ce4fc - tokio::runtime::runtime::Runtime::block_on::h7f3a0c6665c9ff82                                     
  29:     0x55dfce3dd453 - hx::main::hd66bb734998a63b8
  30:     0x55dfce39e313 - std::sys_common::backtrace::__rust_begin_short_backtrace::he8aa0bc60115db3a
  31:     0x55dfce3eaa7d - std::rt::lang_start::{{closure}}::hfd74b2dbc1d03313
  32:     0x55dfce5c766f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb2
52e2                           
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
  33:     0x55dfce5c766f - std::panicking::try::do_call::h629e203a624883e4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  34:     0x55dfce5c766f - std::panicking::try::h7b61614724d6a4f1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  35:     0x55dfce5c766f - std::panic::catch_unwind::h354ac1c0268491d8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  36:     0x55dfce5c766f - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
  37:     0x55dfce5c766f - std::panicking::try::do_call::h54583f67455bff32
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  38:     0x55dfce5c766f - std::panicking::try::hb0e12c4e01d39dc2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  39:     0x55dfce5c766f - std::panic::catch_unwind::h367b6339e3ca9a3b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  40:     0x55dfce5c766f - std::rt::lang_start_internal::ha5ce8533eaa0fda8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  41:     0x55dfce3dd545 - main
  42:     0x7fc590673c4c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  43:     0x7fc590673d05 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  44:     0x55dfcd7d0cc1 - _start
                               at /builddir/glibc-2.39/csu/../sysdeps/x86_64/start.S:115
  45:                0x0 - <unknown>
```

**Comment by sbromberger** [comment]
Likely related: https://github.com/helix-editor/helix/issues/11291

**Comment by sbromberger** [comment]
Cannot reproduce after updating to latest master.
