### ISSUE TITLE
Crash on `jump_backward` after opening a split

### ISSUE THREAD

**Issue by cotneit** [helix-editor/helix#11508]
### Summary

Helix crashes on `jump_backward` after opening a split

Error:
```
thread 'main' panicked at helix-view\src\document.rs:1840:14:
This should only be called after ensure_view_init
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

 

1. Open a file (reproduced with Rust and TypeScript)
2. Go to definition (`g-d`) on anything that would take us to another file
3. Open a split via (`c-w s`/`c-w v`)
4. Press `ctrl-o` to `jump_backward`
5. Crash

### Helix log

<details><summary>RUST_BACKTRACE=1</summary>

```
thread 'main' panicked at helix-view\src\document.rs:1840:14:
This should only be called after ensure_view_init
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:72
   2: core::panicking::panic_display
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:168
   3: core::panicking::panic_str
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:152
   4: core::option::expect_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\option.rs:1988
   5: enum2$<core::option::Option<ref$<helix_view::document::ViewData> > >::expect<ref$<helix_view::document::ViewData> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\option.rs:898
   6: helix_view::document::Document::view_data
             at .\helix-view\src\document.rs:1838
   7: helix_view::document::Document::view_offset
             at .\helix-view\src\document.rs:1852
   8: helix_view::align_view
             at .\helix-view\src\lib.rs:55
   9: helix_view::view::View::ensure_cursor_in_view_center
             at .\helix-view\src\view.rs:346
  10: helix_term::commands::jump_backward
             at .\helix-term\src\commands.rs:5161
  11: enum2$<helix_term::commands::MappableCommand>::execute
             at .\helix-term\src\commands.rs:240
  12: helix_term::ui::editor::impl$1::handle_keymap_event::closure$1
             at .\helix-term\src\ui\editor.rs:877
  13: helix_term::ui::editor::EditorView::handle_keymap_event
             at .\helix-term\src\ui\editor.rs:903
  14: helix_term::ui::editor::EditorView::command_mode
             at .\helix-term\src\ui\editor.rs:1017
  15: helix_term::ui::editor::impl$3::handle_event
             at .\helix-term\src\ui\editor.rs:1414
  16: helix_term::compositor::Compositor::handle_event
             at .\helix-term\src\compositor.rs:152
  17: helix_term::application::impl$0::handle_terminal_events::async_fn$0
             at .\helix-term\src\application.rs:662
  18: helix_term::application::impl$0::event_loop_until_idle::async_fn$0<crossterm::event::stream::EventStream>
             at .\helix-term\src\application.rs:335
  19: helix_term::application::impl$0::event_loop::async_fn$0<crossterm::event::stream::EventStream>
             at .\helix-term\src\application.rs:309
  20: helix_term::application::impl$0::run::async_fn$0<crossterm::event::stream::EventStream>
             at .\helix-term\src\application.rs:1216
  21: hx::main_impl::async_block$0
             at .\helix-term\src\main.rs:160
  22: core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125
  23: tokio::runtime::park::impl$4::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\park.rs:281
  24: tokio::runtime::coop::with_budget
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:107
  25: tokio::runtime::coop::budget
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:73
  26: tokio::runtime::park::CachedParkThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\park.rs:281
  27: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\blocking.rs:66
  28: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\mod.rs:87
  29: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >,enum2$<core::result::Result<i32,an
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\runtime.rs:65
  30: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\mod.rs:86
  31: tokio::runtime::runtime::Runtime::block_on_inner<core::pin::Pin<alloc::boxed::Box<enum2$<hx::main_impl::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\runtime.rs:363
  32: tokio::runtime::runtime::Runtime::block_on<enum2$<hx::main_impl::async_block_env$0> >
             at C:\Users\cotneit\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\runtime.rs:333
  33: hx::main_impl
             at .\helix-term\src\main.rs:162
  34: hx::main
             at .\helix-term\src\main.rs:37
  35: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\hx.exe -vv .` (exit code: 101)
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal 1.20.11781.0

### Installation Method

source

### Helix Version

24.07-142-gff33b077

**Comment by cotneit** [comment]
This is likely the same issue as one mentioned in https://github.com/helix-editor/helix/issues/10847#issuecomment-2253507786 by @James-Firth and @the-mikedavis, if a bug report was created for it I wasn't able to find it

**Comment by the-mikedavis** [comment]
Yeah this does sound like what I ran into.

<details><summary>Backtrace:</summary>

```
thread 'main' panicked at helix-view/src/document.rs:1840:14:
This should only be called after ensure_view_init
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:168:5
   3: core::panicking::panic_str
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1988:5
   5: core::option::Option<T>::expect
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:898:21
   6: helix_view::document::Document::view_data
             at ./helix-view/src/document.rs:1838:9
   7: helix_view::document::Document::view_offset
             at ./helix-view/src/document.rs:1852:9
   8: helix_view::align_view
             at ./helix-view/src/lib.rs:55:27
   9: helix_view::view::View::ensure_cursor_in_view_center
             at ./helix-view/src/view.rs:346:13
  10: helix_term::commands::jump_backward
             at ./helix-term/src/commands.rs:5161:9
  11: helix_term::commands::MappableCommand::execute
             at ./helix-term/src/commands.rs:240:41
  12: helix_term::ui::editor::EditorView::handle_keymap_event::{{closure}}
             at ./helix-term/src/ui/editor.rs:877:13
  13: helix_term::ui::editor::EditorView::handle_keymap_event
             at ./helix-term/src/ui/editor.rs:903:17
  14: helix_term::ui::editor::EditorView::command_mode
             at ./helix-term/src/ui/editor.rs:1017:17
  15: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
             at ./helix-term/src/ui/editor.rs:1414:33
  16: helix_term::compositor::Compositor::handle_event
             at ./helix-term/src/compositor.rs:152:19
  17: helix_term::application::Application::handle_terminal_events::{{closure}}
             at ./helix-term/src/application.rs:662:22
  18: helix_term::application::Application::event_loop_until_idle::{{closure}}
             at ./helix-term/src/application.rs:335:56
  19: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:309:58
  20: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:1216:39
  21: hx::main_impl::{{closure}}
             at ./helix-term/src/main.rs:160:54
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  23: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:63
  24: tokio::runtime::coop::with_budget
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  25: tokio::runtime::coop::budget
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  26: tokio::runtime::park::CachedParkThread::block_on
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:31
  27: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/blocking.rs:66:9
  28: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:87:13
  29: tokio::runtime::context::runtime::enter_runtime
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  30: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:86:9
  31: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:363:45
  32: tokio::runtime::runtime::Runtime::block_on
             at /home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:333:13
  33: hx::main_impl
             at ./helix-term/src/main.rs:162:5
  34: hx::main
             at ./helix-term/src/main.rs:37:21
  35: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
```

</details>

The way we switch documents in the `jump_forward` and `jump_backward` commands is a little bespoke: https://github.com/helix-editor/helix/blob/ff33b07756548935577aefc15cf48a1beb27b162/helix-term/src/commands.rs#L5152-L5161

(Usually we would use `Editor::switch` but that adds to the jumplist.) We need to call `doc.ensure_view_init(view.id)` before the call to `view.ensure_cursor_in_view_center` since the document we switch to might not have been opened in the view before.
