### ISSUE TITLE
:goto should not crash if it doesn't input the line number?

### ISSUE THREAD

**Issue by wingyplus** [helix-editor/helix#1159]
I'm not sure is it a bug. The `:goto` command will be panic if I just typing `:goto` and enter. The stacktrace is:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-term/src/commands.rs:2489:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wingyplus** [comment]
More info with `RUST_BACKTRACE`:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-term/src/commands.rs:2489:20
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: helix_term::commands::cmd::goto_line_number
   4: helix_term::commands::command_mode::{{closure}}
   5: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   6: helix_term::application::Application::handle_terminal_events
   7: helix_term::application::Application::run::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by archseer** [comment]
\cc @s1ck

**Comment by wingyplus** [comment]
I opened a PR to be an opinion. Hope this would help. 🙇

**Comment by s1ck** [comment]
Thanks for reporting the issue. I can review it later :)
