### ISSUE TITLE
Paste using middle-mouse button pastes twice or panics

### ISSUE THREAD

**Issue by bestouff** [helix-editor/helix#1174]
### Reproduction steps

- select some text in a terminal (not the one running `hx`)
- switch to a term running a freshly started `hx`
- press `a` to enter `insert` mode
- press the middle mouse button
- watch the text being pasted **twice** instead of once

=> alternatively, you can try shift-middle-click for the same result (IMHO shift-click should bypass `hx` and just enter the primary selection as if it was typed)

=> alternatively again, you can middle-click twice in `normal` mode if you have selected this text: "`~/.cache/helix/helix.log`" and watch `hx` panic with:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.5.4/src/dfa.rs:1417:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic_bounds_check
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:77:5
   3: regex::re_unicode::Regex::find_at
   4: helix_term::commands::search_impl
   5: helix_term::ui::regex_prompt::{{closure}}
   6: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   7: helix_term::application::Application::handle_terminal_events
   8: helix_term::application::Application::run::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::park::thread::CachedParkThread::block_on
  11: tokio::runtime::thread_pool::ThreadPool::block_on
  12: tokio::runtime::Runtime::block_on
  13: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Environment

- Platform: Linux Debian Sid
- Helix version: v0.5.0-149-g67bf425

> Nothing was output to `~/.cache/helix/helix.log` during these tests.

**Comment by pickfire** [comment]
Not sure if this is related but there is a bug when pasting long texts, the text get cuts off half way since display stops rendering and you have to press some other key to continue rendering.
