### ISSUE TITLE
Somewhat frequent request X timed out error

### ISSUE THREAD

**Issue by Bowarc** [helix-editor/helix#11918]
### Summary

Using the Rust lsp i often (every couple of hours) get delay on save and lsp action (goto definition etc..) to a point where buffer save requests are just ignored (at least it looks like it) and its spamming `Request <incrementing number> timed out`. (<> descriptive tag, not actual text)

The only solution i found is `:lsp-restart`

### Reproduction Steps

The thing is that i don't really know what triggers it.

I don't feel like i save too much (maybe once a minute at max ?), nor spam lsp actions

Sorry :c

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-10-19T09:29:48.041 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:30:07.750 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(4451)), original request likely timed out
2024-10-19T09:30:13.851 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:30:28.475 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:30:38.500 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:30:50.556 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(4554)), original request likely timed out
2024-10-19T09:30:50.973 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:31:39.094 helix_lsp::transport [ERROR] rust-analyzer <- InternalError: Invalid offset LineCol { line: 49, col: 0 } (line index length: 1213)
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "Panic context:\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "> \n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "version: 1.81.0 (eeb90cda 2024-09-04)\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "notification: textDocument/didChange\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "thread 'LspServer' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\\library\\alloc\\src\\string.rs:1933:29:\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "assertion failed: self.is_char_boundary(n)\n"
2024-10-19T09:33:01.700 helix_lsp::transport [ERROR] rust-analyzer err <- "stack backtrace:\n"
2024-10-19T09:33:01.744 helix_view::document [ERROR] Failed to copy metadata on write: The operation completed successfully. (os error 0)
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "   0:     0x7ffae774408d - std::backtrace_rs::backtrace::dbghelp64::trace\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\dbghelp64.rs:91\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "   1:     0x7ffae774408d - std::backtrace_rs::backtrace::trace_unsynchronized\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\mod.rs:66\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "   2:     0x7ffae774408d - std::sys::backtrace::_print_fmt\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:65\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "   3:     0x7ffae774408d - std::sys::backtrace::impl$0::print::impl$0::fmt\n"
2024-10-19T09:33:01.755 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:40\n"
2024-10-19T09:33:01.771 helix_lsp::transport [ERROR] rust-analyzer err <- "   4:     0x7ffae7774bb9 - core::fmt::rt::Argument::fmt\n"
2024-10-19T09:33:01.771 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\rt.rs:173\n"
2024-10-19T09:33:01.771 helix_lsp::transport [ERROR] rust-analyzer err <- "   5:     0x7ffae7774bb9 - core::fmt::write\n"
2024-10-19T09:33:01.771 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\mod.rs:1182\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "   6:     0x7ffae773ab71 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\io\\mod.rs:1827\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "   7:     0x7ffae7747127 - std::panicking::default_hook::closure$1\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:269\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "   8:     0x7ffae7746d19 - std::panicking::default_hook\n"
2024-10-19T09:33:01.772 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:296\n"
2024-10-19T09:33:01.775 helix_lsp::transport [ERROR] rust-analyzer err <- "   9:     0x7ff732b8b47c - <unknown>\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "  10:     0x7ffae774796b - alloc::boxed::impl$50::call\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2084\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "  11:     0x7ffae774796b - std::panicking::rust_panic_with_hook\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:808\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "  12:     0x7ffae774773f - std::panicking::begin_panic_handler::closure$0\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:667\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "  13:     0x7ffae77449ff - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:168\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "  14:     0x7ffae7747356 - std::panicking::begin_panic_handler\n"
2024-10-19T09:33:01.776 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:665\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  15:     0x7ffae779dc34 - core::panicking::panic_fmt\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\panicking.rs:74\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  16:     0x7ffae779dcdd - core::panicking::panic\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\panicking.rs:148\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  17:     0x7ff73183313c - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  18:     0x7ff731813719 - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  19:     0x7ff7317664b7 - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  20:     0x7ff731761e5b - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  21:     0x7ff73150cce6 - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  22:     0x7ff731474919 - <unknown>\n"
2024-10-19T09:33:01.777 helix_lsp::transport [ERROR] rust-analyzer err <- "  23:     0x7ff7314efb49 - <unknown>\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "  24:     0x7ffae7758f0d - alloc::boxed::impl$48::call_once\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2070\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "  25:     0x7ffae7758f0d - alloc::boxed::impl$48::call_once\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2070\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "  26:     0x7ffae7758f0d - std::sys::pal::windows::thread::impl$0::new::thread_start\n"
2024-10-19T09:33:01.778 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\pal\\windows\\thread.rs:58\n"
2024-10-19T09:33:01.783 helix_lsp::transport [ERROR] rust-analyzer err <- "  27:     0x7ffb5deb7374 - BaseThreadInitThunk\n"
2024-10-19T09:33:01.788 helix_lsp::transport [ERROR] rust-analyzer err <- "  28:     0x7ffb5e93cc91 - RtlUserThreadStart\n"
2024-10-19T09:33:01.788 helix_lsp::transport [ERROR] rust-analyzer err <- "thread '<unnamed>' panicked at /rust/deps\\lsp-server-0.7.6\\src\\stdio.rs:28:37:\n"
2024-10-19T09:33:01.788 helix_lsp::transport [ERROR] rust-analyzer err <- "receiver was dropped, failed to send a message: \"SendError(..)\"\n"
2024-10-19T09:33:01.788 helix_lsp::transport [ERROR] rust-analyzer err <- "stack backtrace:\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "   0:     0x7ffae774408d - std::backtrace_rs::backtrace::dbghelp64::trace\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\dbghelp64.rs:91\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "   1:     0x7ffae774408d - std::backtrace_rs::backtrace::trace_unsynchronized\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\mod.rs:66\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "   2:     0x7ffae774408d - std::sys::backtrace::_print_fmt\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:65\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "   3:     0x7ffae774408d - std::sys::backtrace::impl$0::print::impl$0::fmt\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:40\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "   4:     0x7ffae7774bb9 - core::fmt::rt::Argument::fmt\n"
2024-10-19T09:33:01.789 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\rt.rs:173\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "   5:     0x7ffae7774bb9 - core::fmt::write\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\mod.rs:1182\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "   6:     0x7ffae773ab71 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\io\\mod.rs:1827\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "   7:     0x7ffae7747127 - std::panicking::default_hook::closure$1\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:269\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "   8:     0x7ffae7746d19 - std::panicking::default_hook\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:296\n"
2024-10-19T09:33:01.790 helix_lsp::transport [ERROR] rust-analyzer err <- "   9:     0x7ff732b8b47c - <unknown>\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "  10:     0x7ffae774796b - alloc::boxed::impl$50::call\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2084\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "  11:     0x7ffae774796b - std::panicking::rust_panic_with_hook\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:808\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "  12:     0x7ffae7747776 - std::panicking::begin_panic_handler::closure$0\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:674\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "  13:     0x7ffae77449ff - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:168\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "  14:     0x7ffae7747356 - std::panicking::begin_panic_handler\n"
2024-10-19T09:33:01.791 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:665\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  15:     0x7ffae779dc34 - core::panicking::panic_fmt\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\panicking.rs:74\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  16:     0x7ffae779e1e0 - core::result::unwrap_failed\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\result.rs:1679\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  17:     0x7ff732ba53ec - <unknown>\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  18:     0x7ff732bab1d2 - <unknown>\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  19:     0x7ffae7758f0d - alloc::boxed::impl$48::call_once\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2070\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "  20:     0x7ffae7758f0d - alloc::boxed::impl$48::call_once\n"
2024-10-19T09:33:01.792 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2070\n"
2024-10-19T09:33:01.793 helix_lsp::transport [ERROR] rust-analyzer err <- "  21:     0x7ffae7758f0d - std::sys::pal::windows::thread::impl$0::new::thread_start\n"
2024-10-19T09:33:01.793 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\pal\\windows\\thread.rs:58\n"
2024-10-19T09:33:01.793 helix_lsp::transport [ERROR] rust-analyzer err <- "  22:     0x7ffb5deb7374 - BaseThreadInitThunk\n"
2024-10-19T09:33:01.793 helix_lsp::transport [ERROR] rust-analyzer err <- "  23:     0x7ffb5e93cc91 - RtlUserThreadStart\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "thread 'main' panicked at /rust/deps\\jod-thread-0.1.2\\src\\lib.rs:33:22:\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "called `Result::unwrap()` on an `Err` value: Any { .. }\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "stack backtrace:\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "   0:     0x7ffae774408d - std::backtrace_rs::backtrace::dbghelp64::trace\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\dbghelp64.rs:91\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "   1:     0x7ffae774408d - std::backtrace_rs::backtrace::trace_unsynchronized\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\mod.rs:66\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "   2:     0x7ffae774408d - std::sys::backtrace::_print_fmt\n"
2024-10-19T09:33:08.200 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:65\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "   3:     0x7ffae774408d - std::sys::backtrace::impl$0::print::impl$0::fmt\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:40\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "   4:     0x7ffae7774bb9 - core::fmt::rt::Argument::fmt\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\rt.rs:173\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "   5:     0x7ffae7774bb9 - core::fmt::write\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\fmt\\mod.rs:1182\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "   6:     0x7ffae773ab71 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\io\\mod.rs:1827\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "   7:     0x7ffae7747127 - std::panicking::default_hook::closure$1\n"
2024-10-19T09:33:08.201 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:269\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "   8:     0x7ffae7746d19 - std::panicking::default_hook\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:296\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "   9:     0x7ff732b8b47c - <unknown>\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "  10:     0x7ffae774796b - alloc::boxed::impl$50::call\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\alloc\\src\\boxed.rs:2084\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "  11:     0x7ffae774796b - std::panicking::rust_panic_with_hook\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:808\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "  12:     0x7ffae7747776 - std::panicking::begin_panic_handler::closure$0\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:674\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "  13:     0x7ffae77449ff - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>\n"
2024-10-19T09:33:08.202 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\sys\\backtrace.rs:168\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  14:     0x7ffae7747356 - std::panicking::begin_panic_handler\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:665\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  15:     0x7ffae779dc34 - core::panicking::panic_fmt\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\panicking.rs:74\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  16:     0x7ffae779e1e0 - core::result::unwrap_failed\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\core\\src\\result.rs:1679\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  17:     0x7ff7315093f2 - <unknown>\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  18:     0x7ff731507907 - <unknown>\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  19:     0x7ff731474906 - <unknown>\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  20:     0x7ff7314ee854 - <unknown>\n"
2024-10-19T09:33:08.203 helix_lsp::transport [ERROR] rust-analyzer err <- "  21:     0x7ffae772ba49 - std::rt::lang_start_internal::closure$2\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\rt.rs:141\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  22:     0x7ffae772ba49 - std::panicking::try::do_call\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:557\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  23:     0x7ffae772ba49 - std::panicking::try\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panicking.rs:521\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  24:     0x7ffae772ba49 - std::panic::catch_unwind\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\panic.rs:350\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  25:     0x7ffae772ba49 - std::rt::lang_start_internal\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\\std\\src\\rt.rs:141\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  26:     0x7ff73150fd7c - <unknown>\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  27:     0x7ff732bc4cdc - <unknown>\n"
2024-10-19T09:33:08.204 helix_lsp::transport [ERROR] rust-analyzer err <- "  28:     0x7ffb5deb7374 - BaseThreadInitThunk\n"
2024-10-19T09:33:08.205 helix_lsp::transport [ERROR] rust-analyzer err <- "  29:     0x7ffb5e93cc91 - RtlUserThreadStart\n"
2024-10-19T09:33:08.250 helix_lsp::transport [ERROR] rust-analyzer err: <- StreamClosed
2024-10-19T09:33:08.254 helix_lsp::transport [ERROR] rust-analyzer err: <- IO(Os { code: 232, kind: BrokenPipe, message: "The pipe is being closed." })
2024-10-19T09:33:08.770 helix_lsp::transport [ERROR] rust-analyzer err: <- IO(Os { code: 232, kind: BrokenPipe, message: "The pipe is being closed." })
// Repeat last line 690 times
// end of log
```

</details>

### Platform

Windows 10

### Terminal Emulator

Windows terminal(portable) 1.21

### Installation Method

scoop

### Helix Version

helix 24.7 (079f5442)

**Comment by Bowarc** [comment]
This time the error seems to be `2024-10-19T15:45:52.487 helix_lsp::transport [ERROR] rust-analyzer <- InternalError: Invalid offset LineCol { line: 25, col: 0 } (line index length: 638)
`
