### ISSUE TITLE
thread 'main' panicked at helix-core/src/transaction.rs:185:46:

### ISSUE THREAD

**Issue by gobijan** [helix-editor/helix#12221]
### Summary

Hi, thanks for making helix. It's awesome and runs mostly stable. However today it crashed on me:

    thread 'main' panicked at helix-core/src/transaction.rs:185:46:
    internal error: entered unreachable code: (Some(Retain(18446744073709550406)))
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction Steps

I tried to switch to another open helix tab (had 3 window splits open) then it crashed. I was editing a Ruby on Rails application with ruby-lsp, solargraph and copilot as LSPs open.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-12-09T09:42:08.335 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(429)), original request likely timed out
2024-12-09T09:42:10.587 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(430)), original request likely timed out
2024-12-09T09:44:15.720 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(431)), original request likely timed out
```

</details>

### Platform

macOS

### Terminal Emulator

iTerm2 Build 3.5.10

### Installation Method

brew

### Helix Version

helix 24.7 (079f5442)

**Comment by TornaxO7** [comment]
May I ask if you can reproduce this on the latest master?

**Comment by gobijan** [comment]
It rarely happens so I am not sure what triggers it. Maybe some language server died because of too many open files or something and then helix tries to send into a closed channel which is not handled gracefully. Did you tackle this area in the latest master? Can try to run it later but not sure if I can reproduce it.

**Comment by TornaxO7** [comment]
I didn't have any crashes of helix for a long time and I'm only using the master branch. So no, I can't provide any useful information here

![sadge](https://github.com/user-attachments/assets/2a89394e-ade8-44ef-b2c4-7a416b562313)

**Comment by woojiq** [comment]
Have you researched github issues before creating this one?
