### ISSUE TITLE
Language Server Error on Termux  (  ```Async job failed: protocal error: Server error: content modified```)

### ISSUE THREAD

**Issue by anzhi0708** [helix-editor/helix#1229]
### Reproduction steps
- Modify Rust code on Termux with `rust-analyzer` support
 

### Environment

- Platform:  Termux (Android)
- Helix version:  0.5.0

<details><summary>~/.cache/helix/helix.log (screenshot)</summary>

![image](https://user-images.githubusercontent.com/57821133/144648854-710a4324-2065-4cf5-874c-acd634f0d527.png)

</details>
<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/57821133/144649227-7e65b5c7-b1d2-4996-99f9-fd40308dc0e6.png)

</details>

**Comment by archseer** [comment]
Please reproduce with `hx -v` so we get more log output.

**Comment by anzhi0708** [comment]
> Please reproduce with `hx -v` so we get more log output.

Didn't know it, I'll keep that in mind! ^_^

**Comment by flukejones** [comment]
I get a similar error. A few actually - initial LSP run never completes, and then I get the errors mentioned in this issue.

[helix.log](https://github.com/helix-editor/helix/files/7684778/helix.log)

**Comment by archseer** [comment]
@flukejones you seem to have an issue on the rust-analyzer side, all of these messages are coming in verbatim from the LSP

```
2021-12-01T00:06:23.046 helix_lsp::transport [ERROR] err <- "thread '<unnamed>' panicked at 'Internal error, cycle detected:\n"
2021-12-01T00:06:23.046 helix_lsp::transport [ERROR] err <- "\n"
2021-12-01T00:06:23.046 helix_lsp::transport [ERROR] err <- "DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 819 }\n"
2021-12-01T00:06:23.047 helix_lsp::transport [ERROR] err <- "DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 2 }\n"
2021-12-01T00:06:23.047 helix_lsp::transport [ERROR] err <- "', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48\n"
2021-12-01T00:06:23.047 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "   0: rust_begin_unwind\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "   1: std::panicking::begin_panic_fmt\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "   2: salsa::QueryTable<Q>::get::{{closure}}\n"
2021-12-01T00:06:23.054 helix_lsp::transport [ERROR] err <- "   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim\n"

```



There seem to be various reports of this from around April/May that were supposedly fixed, are you running the latest rust-analyzer? https://github.com/rust-analyzer/rust-analyzer/issues/8824

**Comment by flukejones** [comment]
My apologies. I should have noticed this. Yes updating it worked. For whatever reason I thought rustup was updating it and had forgotten I did a manual install.

**Comment by pascalkuthe** [comment]
I am closing this as it actually sounds like this was resolved
