### ISSUE TITLE
Occasional crash when jumping to previous location

### ISSUE THREAD

**Issue by dylrich** [helix-editor/helix#1238]
### Reproduction steps

I am unsure how to reproduce other than: It happens occasionally when I `ctrl-o` to go back to a previous file. It may possibly happen more often on files I haven't edited for a little while?

### Environment

- Platform: Ubuntu 18 x86 Linux
- Helix version: v0.5.0-209-g35ac815 built from master

<details><summary>~/.cache/helix/helix.log</summary>
I don't have log output for you, but I do have a stack trace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 4659, Rope/RopeSlice char length 4173', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.3.1/src/slice.rs:263:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: ropey::slice::RopeSlice::char_to_byte
   4: helix_core::graphemes::nth_prev_grapheme_boundary
   5: helix_core::selection::Range::grapheme_aligned
   6: helix_core::selection::Selection::ensure_invariants
   7: helix_term::commands::jump_backward
   8: helix_term::ui::editor::EditorView::handle_keymap_event
   9: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
  10: helix_term::application::Application::handle_terminal_events
  11: helix_term::application::Application::run::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::park::thread::CachedParkThread::block_on
  14: tokio::runtime::thread_pool::ThreadPool::block_on
  15: tokio::runtime::Runtime::block_on
  16: hx::main
```
</details>

**Comment by archseer** [comment]
Hmm I think that's because the jump location no longer exists (if the document has less lines)

**Comment by pickfire** [comment]
There was this issue previously for pipe https://github.com/helix-editor/helix/pull/1123, I think it depends on what command that was runned previously.

**Comment by archseer** [comment]
It's the `view.jumps` list

**Comment by Termina94** [comment]
pr above to fix issue

I replicated this issue by:
- start app
- global search -> open file
- ctrl-o to go to previous jump

the issue was that the empty scratch buffer created at app start was being added to the jump list when switching to a file using the global search. There was a similar check elsewhere that checked on doc delete but not on switch

The panic itself was coming from the `current!` macro trying to unwrap a non-existent document.

Would it not make more sense to have the `current!` macro return an option tuple to avoid issues like this crashing the program?

**Comment by the-mikedavis** [comment]
I can reproduce ☝️

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/commands.rs:3919:27
stack backtrace:
   0:     0x55f2ee1cb0d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
   1:     0x55f2edaa784c - core::fmt::write::hba4337c43d992f49
   2:     0x55f2ee1c4995 - std::io::Write::write_fmt::heb73de6e02cfabed
   3:     0x55f2ee1ccf7e - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
   4:     0x55f2ee1cccad - std::panicking::default_hook::h2e88d02087fae196
   5:     0x55f2ee087fcb - helix_term::application::Application::run::{{closure}}::{{closure}}::ha911ea75af28c401
   6:     0x55f2ee1cd60b - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
   7:     0x55f2ee1cd40c - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
   8:     0x55f2ee1cb604 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
   9:     0x55f2ee1cd19d - rust_begin_unwind
  10:     0x55f2eda2cd53 - core::panicking::panic_fmt::h366d3a309ae17c94
  11:     0x55f2eda2cc1d - core::panicking::panic::h8705e81f284be8a5
  12:     0x55f2edefdc5a - helix_term::commands::jump_backward::hbfebaf85010847f6
  13:     0x55f2eddae997 - helix_term::ui::editor::EditorView::handle_keymap_event::hb4ccbf9c7492f688
  14:     0x55f2eddb1011 - <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event::he3f4382d5be18977
  15:     0x55f2edda7451 - helix_term::compositor::Compositor::handle_event::hffd1d7fda4dd3ce2
  16:     0x55f2eddda81e - helix_term::application::Application::handle_terminal_events::hd16faa0197ec48a3
  17:     0x55f2ee0842ba - helix_term::application::Application::event_loop::{{closure}}::h3ad637e9d15bda46
  18:     0x55f2ee09b329 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he718b1b42048c5cc
  19:     0x55f2ee068782 - std::thread::local::LocalKey<T>::with::h435f69e7d9b93b2e
  20:     0x55f2ee05ea98 - tokio::park::thread::CachedParkThread::block_on::hf460660029437eb1
  21:     0x55f2ee0512a3 - tokio::runtime::thread_pool::ThreadPool::block_on::hd5b228a0e807c775
  22:     0x55f2ee077390 - tokio::runtime::Runtime::block_on::h2fb2f5f57432439c
  23:     0x55f2ee03343d - hx::main::hc4fc2362cf1271b5
  24:     0x55f2ee058e03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h140c864e67994081
  25:     0x55f2ee0683dd - std::rt::lang_start::{{closure}}::hb16e5a4d88ad63a7
  26:     0x55f2ee1bf2eb - std::rt::lang_start_internal::h9c06694362b5b80c
  27:     0x55f2ee033562 - main
  28:     0x7ff4abdb3237 - __libc_start_call_main
  29:     0x7ff4abdb32f5 - __libc_start_main_impl
  30:     0x55f2eda5cfd1 - _start
  31:                0x0 - <unknown>
```

Ideally we should be keeping a jump list that is viable at every jump and only editing or dropping entries when editing buffers like with `:buffer-close`, rather than playing defense anywhere we bring up the document (since we bring it up very often).
