### ISSUE TITLE
Bug: editting a new theme.toml crashes helix.

### ISSUE THREAD

**Issue by rieger-jared** [helix-editor/helix#175]
I'm running Helix on MacOS Big Sur 11.4 (20F71) on a MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) INTEL.

StackTrace
```shell
RUST_BACKTRACE=1 hx theme.toml
thread 'main' panicked at 'Attempt to index past end of Rope: char index 4, Rope char length 4', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.2.0/src/rope.rs:996:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

To reproduce.

```shell
touch theme.toml
RUST_BACKTRACE=1 hx theme.toml
```

In the new file, type 

- `i` to get into insert mode
- type the text `asdf`
- press `esc` key to get out of insert mode
- save the file with `:w`
- then press `j`
 
This should then crash helix with the error 

```shell
thread 'main' panicked at 'Attempt to index past end of slice: line index 1, slice line length 1', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.2.0/src/slice.rs:534:9
stack backtrace:
   0:        0x103541b44 - __mh_execute_header
   1:        0x10355fc8e - __mh_execute_header
   2:        0x10353d956 - __mh_execute_header
   3:        0x103543ce9 - __mh_execute_header
   4:        0x1035437d0 - __mh_execute_header
   5:        0x1030e93fd - __mh_execute_header
   6:        0x103544378 - __mh_execute_header
   7:        0x103543e95 - __mh_execute_header
   8:        0x103541fa8 - __mh_execute_header
   9:        0x103543dfa - __mh_execute_header
  10:        0x103582c8b - __mh_execute_header
  11:        0x1032f0ed7 - __mh_execute_header
  12:        0x10308d8d1 - __mh_execute_header
  13:        0x10310f6e5 - __mh_execute_header
  14:        0x10312646d - __mh_execute_header
  15:        0x1030e7c7d - __mh_execute_header
  16:        0x103120a41 - __mh_execute_header
  17:        0x10309ab3f - __mh_execute_header
  18:        0x1030bef3d - __mh_execute_header
  19:        0x10313b24a - __mh_execute_header
  20:        0x10313b271 - __mh_execute_header
  21:        0x1035446c4 - __mh_execute_header
  22:        0x1030bf069 - __mh_execute_header
```

I hope this was easy to follow.

**Comment by archseer** [comment]
What release are you using? I think the homebrew tap needs updating to `0.0.10`

**Comment by rieger-jared** [comment]
Is that right? 
```shell
hx --version
helix-term 0.1.0
```

**Comment by archseer** [comment]
[Just updated the tap](https://github.com/helix-editor/homebrew-helix/commit/c45dcd43a470c0b2bc346ba83f2df16ba54d1117), can you update via brew?

**Comment by rieger-jared** [comment]
Okay, that seems to have fixed the issue. Thanks!

By the way, how do I check the version of Helix?

**Comment by archseer** [comment]
Since this release `hx --version` should now show the proper version number :)
