### ISSUE TITLE
Building grammar fails on Fedora

### ISSUE THREAD

**Issue by Hofer-Julian** [helix-editor/helix#1915]
### Summary

Building grammar fails with:

```
  --- stderr
  thread 'main' panicked at 'Failed to compile tree-sitter grammars: Failed to build some grammar(s)

  Caused by:
      0: Failed to execute C compiler
      1: No such file or directory (os error 2)', helix-term/build.rs:22:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:127:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:127:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', 
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/var/home/julian/Projekte/others/helix/helix-term)`, intermediate artifacts can be found at `/var/home/julian/Projekte/others/helix/target`
```

Tested with master as well as 22.03
rustc: 1.59.0

### Reproduction Steps

git clone https://github.com/helix-editor/helix
cd helix
cargo install --path helix-term
hx --grammar fetch
hx --grammar build

### Platform

Linux (Fedora Silverblue 35)

### Terminal Emulator

gnome-terminal

### Helix Version

helix master

**Comment by Hofer-Julian** [comment]
On windows it seems to work fine.

**Comment by Hofer-Julian** [comment]
@archseer thanks a lot.
I've actually installed a bunch of stuff with `sudo dnf groupinstall "Development Tools" "Development Libraries"`.
Who would have thought that this is only a subset of `sudo dnf group install "C Development Tools and Libraries"` 🤷🏻
