### ISSUE TITLE
index out of bounds on Windows

### ISSUE THREAD

**Issue by IanS5** [helix-editor/helix#22]
when I run the command `hx` (v0.0.6 binary from the release page) on Windows 10 it panics immediately with

```txt
thread 'main' panicked at 'index out of bounds: the len is 3451 but the index is 3451', helix-tui\src\buffer.rs:185:14
```

I'm using Windows Terminal, and the len changes depending on the terminal size.

**Comment by alex-knyaz** [comment]
Same.

Here is my backtrace:
```thread 'main' panicked at 'index out of bounds: the len is 11623 but the index is 11623', helix-tui\src\buffer.rs:185:14
stack backtrace:
   0:     0x7ff65f3d1aee - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff65f3d1aee - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff65f3d1aee - std::sys_common::backtrace::_print_fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff65f3d1aee - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff65f3edcfc - core::fmt::write
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\fmt\mod.rs:1092
   5:     0x7ff65f3cd9d8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\io\mod.rs:1572
   6:     0x7ff65f3d4a5d - std::sys_common::backtrace::_print
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff65f3d4a5d - std::sys_common::backtrace::print
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff65f3d4a5d - std::panicking::default_hook::{{closure}}
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:208
   9:     0x7ff65f3d4529 - std::panicking::default_hook
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:225
  10:     0x7ff65f0bb7a3 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::hc7678c603bb1d705
  11:     0x7ff65f3d5145 - std::panicking::rust_panic_with_hook
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:595
  12:     0x7ff65f3d4cb1 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:497
  13:     0x7ff65f3d240f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:141
  14:     0x7ff65f3d4c09 - std::panicking::begin_panic_handler
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:493
  15:     0x7ff65f4e89a0 - core::panicking::panic_fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:92
  16:     0x7ff65f4e8967 - core::panicking::panic_bounds_check
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:69
  17:     0x7ff65f1c427f - helix_tui::buffer::Buffer::set_style::hed1d13c3b48d5305
  18:     0x7ff65f0ff771 - <hx::ui::editor::EditorView as hx::compositor::Component>::render::hbab99c200d40d384
  19:     0x7ff65f0f28b3 - hx::compositor::Compositor::render::hea9c906b824105f2
  20:     0x7ff65f0b6507 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8dea0a1971d85a54
  21:     0x7ff65f0f9a09 - tokio::runtime::enter::Enter::block_on::hdf82571d84a06592
  22:     0x7ff65f06bbae - tokio::runtime::Runtime::block_on::h1fb76b09904f19ab
  23:     0x7ff65f0be5f2 - hx::ui::file_picker::h40bf0de4cb458c43
  24:     0x7ff65f115c46 - std::sys_common::backtrace::__rust_end_short_backtrace::h52cf7ae955fa074a
  25:     0x7ff65f115c5c - std::rt::lang_start::{{closure}}::hb102f37685dbdeab
  26:     0x7ff65f3d52a7 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\library\core\src\ops\function.rs:280
  27:     0x7ff65f3d52a7 - std::panicking::try::do_call
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:379
  28:     0x7ff65f3d52a7 - std::panicking::try
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:343
  29:     0x7ff65f3d52a7 - std::panic::catch_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panic.rs:431
  30:     0x7ff65f3d52a7 - std::rt::lang_start_internal
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\rt.rs:51
  31:     0x7ff65f0bed97 - main
  32:     0x7ff65f4d07c0 - invoke_main
                               at D:\agent\_work\13\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33:     0x7ff65f4d07c0 - __scrt_common_main_seh
                               at D:\agent\_work\13\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34:     0x7ffba8b77034 - BaseThreadInitThunk
  35:     0x7ffbaa702651 - RtlUserThreadStart```

Hope this helps.

**Comment by rpherman** [comment]
I built helix on my windows 10 machine after updating rust, and I get the following:

`thread 'main' panicked at 'index out of bounds: the len is 3451`

`thread 'main' panicked at 'index out of bounds: the len is 3451 but the index is 3451', helix-tui\src\buffer.rs:185:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:92
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:69
   3: helix_tui::buffer::Buffer::set_style
   4: <hx::ui::editor::EditorView as hx::compositor::Component>::render
   5: hx::compositor::Compositor::render
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::Runtime::block_on
   9: hx::ui::file_picker
  10: std::rt::lang_start::{{closure}}
  11: core::ops::function::impls::{{impl}}::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\library\core\src\ops\function.rs:280
  12: std::panicking::try::do_call
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:379
  13: std::panicking::try
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:343
  14: std::panic::catch_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panic.rs:431
  15: std::rt::lang_start_internal
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\rt.rs:51
  16: main
  17: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  18: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  19: BaseThreadInitThunk
  20: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by archseer** [comment]
I'm looking into this, it seems that it's trying to render out of bounds.
