### ISSUE TITLE
`:open` panic

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#225]
```
thread 'main' panicked at 'Trying to access position outside the buffer: x=121, y=19, area=Rect { x: 0, y: 0, width: 120, height: 30 }', helix-tui\src\buffer.rs:217:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\/library\std\src\panicking.rs:515
   1: std::panicking::begin_panic_fmt
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\/library\std\src\panicking.rs:457
   2: helix_tui::buffer::Buffer::index_of
             at C:\Users\there\Desktop\helix\helix-tui\src\buffer.rs:217
   3: helix_tui::buffer::Buffer::set_stringn<enum$<alloc::borrow::Cow<str>>**>
             at C:\Users\there\Desktop\helix\helix-tui\src\buffer.rs:291
   4: helix_term::ui::prompt::Prompt::render_prompt
             at C:\Users\there\Desktop\helix\helix-term\src\ui\prompt.rs:157
   5: helix_term::ui::prompt::{{impl}}::render
             at C:\Users\there\Desktop\helix\helix-term\src\ui\prompt.rs:297
   6: helix_term::compositor::Compositor::render
             at C:\Users\there\Desktop\helix\helix-term\src\compositor.rs:137
   7: helix_term::application::Application::render
             at C:\Users\there\Desktop\helix\helix-term\src\application.rs:92
   8: helix_term::application::Application::handle_terminal_events
             at C:\Users\there\Desktop\helix\helix-term\src\application.rs:151
   9: helix_term::application::{{impl}}::event_loop::{{closure}}
             at C:\Users\there\Desktop\helix\helix-term\src\application.rs:109
  10: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\core\src\future\mod.rs:80
  11: helix_term::application::{{impl}}::run::{{closure}}
             at C:\Users\there\Desktop\helix\helix-term\src\application.rs:320
  12: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\core\src\future\mod.rs:80
  13: hx::main::{{closure}}
             at C:\Users\there\Desktop\helix\helix-term\src\main.rs:96
  14: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\core\src\future\mod.rs:80
  15: tokio::park::thread::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\park\thread.rs:263
  16: tokio::coop::with_budget::{{closure}}<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>,closure-0>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\coop.rs:106
  17: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\std\src\thread\local.rs:400
  18: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\std\src\thread\local.rs:376
  19: tokio::coop::with_budget
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\coop.rs:99
  20: tokio::coop::budget
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\coop.rs:76
  21: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\park\thread.rs:263
  22: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\runtime\enter.rs:151
  23: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\runtime\thread_pool\mod.rs:71
  24: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\there\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.1\src\runtime\mod.rs:452
  25: hx::main
             at C:\Users\there\Desktop\helix\helix-term\src\main.rs:98
  26: core::ops::function::FnOnce::call_once<fn() -> enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>,tuple<>>
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/blob/69fe46a122f728b4bb6cb218fd410544097b0dcd/helix-term/src/ui/prompt.rs#L130

It's this line that enables the bug.

**Comment by archseer** [comment]
No, the `x` coordinate is off-screen, not `y`.

https://github.com/helix-editor/helix/blob/69fe46a122f728b4bb6cb218fd410544097b0dcd/helix-term/src/ui/prompt.rs#L158

I think the width is incorrect here:

https://github.com/helix-editor/helix/blob/69fe46a122f728b4bb6cb218fd410544097b0dcd/helix-term/src/ui/prompt.rs#L161

**Comment by kirawi** [comment]
Possibly, but reverting that line back to how it was before prevented the panic.

**Comment by archseer** [comment]
Can you check if https://github.com/helix-editor/helix/commit/d545e6164416e0aecc71ff1350b5c9827723c43d addresses the problem for you?

**Comment by kirawi** [comment]
Looks like it.
