### ISSUE TITLE
Crash when iterating through files on Windows

### ISSUE THREAD

**Issue by quixoticaxis** [helix-editor/helix#2301]
### Summary

Helix panics when trying to iterate through files on Windows in a specific scenario (see reproduction steps). Both release and the latest versions have this issue.

### Reproduction Steps

1. Open Helix.
2. Type `:open C:`.
3. Press TAB and Helix would erroneously append the file from the current folder. For example, when using the release version, automatic completion would give `:open C:hx.exe`.
4. Press Backspace.
5. Helix crashes.

### Helix log

Log file is empty, but I have collected the backtrace on the latest version from git:

```
     Running `target\debug\hx.exe`
thread 'main' panicked at 'range start index 2 out of range for slice of length 0', library\std\src\path.rs:730:24
stack backtrace:
   0:     0x7ff7d3885a41 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7d3885a41 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7d3885a41 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff7d3885a41 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff7d38a911a - core::fmt::write
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\fmt\mod.rs:1190
   5:     0x7ff7d387bf89 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\io\mod.rs:1657
   6:     0x7ff7d3888722 - std::sys_common::backtrace::_print
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff7d3888722 - std::sys_common::backtrace::print
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff7d3888722 - std::panicking::default_hook::closure$1
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:295
   9:     0x7ff7d38882e5 - std::panicking::default_hook
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:314
  10:     0x7ff7d253d623 - alloc::boxed::impl$46::call<tuple$<ref$<core::panic::panic_info::PanicInfo> >,dyn$<core::ops::function::Fn<tuple$<ref$<core::panic::panic_info::PanicInfo> >,assoc$<Output,tuple$<> > >,core::marker::Send,core::marker::Sync>,alloc::alloc::Global>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\alloc\src\boxed.rs:1867
  11:     0x7ff7d2533c78 - helix_term::application::impl$0::run::async_fn$0::closure$0
                               at *************\helix-term\src\application.rs:736
  12:     0x7ff7d3888ee1 - std::panicking::rust_panic_with_hook
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:702
  13:     0x7ff7d3888c2d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:588
  14:     0x7ff7d3886377 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:138
  15:     0x7ff7d38888a9 - std::panicking::begin_panic_handler
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
  16:     0x7ff7d38da215 - core::panicking::panic_fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
  17:     0x7ff7d38da3a7 - core::slice::index::slice_start_index_len_fail
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\slice\index.rs:35
  18:     0x7ff7d387f8e1 - core::slice::index::impl$5::index
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\slice\index.rs:329
  19:     0x7ff7d387f8e1 - core::slice::index::impl$0::index
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\slice\index.rs:15
  20:     0x7ff7d387f8e1 - std::path::Components::include_cur_dir
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:736
  21:     0x7ff7d387f5b6 - std::path::Components::len_before_body
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:671
  22:     0x7ff7d387f5b6 - std::path::Components::trim_right
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:788
  23:     0x7ff7d387f5b6 - std::path::Components::as_path
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:707
  24:     0x7ff7d38823e3 - std::path::impl$62::_strip_prefix::closure$0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:2276
  25:     0x7ff7d38823e3 - core::option::Option::map
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\option.rs:906
  26:     0x7ff7d38823e3 - std::path::Path::_strip_prefix
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\path.rs:2275
  27:     0x7ff7d32f330e - std::path::Path::strip_prefix<ref$<std::path::PathBuf> >
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\path.rs:2271
  28:     0x7ff7d28f1431 - helix_term::ui::completers::filename_impl::closure$1::closure$0<helix_term::ui::completers::filename::closure_env$0>
                               at *************\helix-term\src\ui\mod.rs:399
  29:     0x7ff7d2651c10 - enum$<core::option::Option<ignore::walk::DirEntry>, 0, 2, Some>::and_then<ignore::walk::DirEntry,tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,helix_term::ui::completers::filename_impl::closure$1::closure_env$0<helix_term::ui
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\option.rs:1239
  30:     0x7ff7d28f132a - helix_term::ui::completers::filename_impl::closure$1<helix_term::ui::completers::filename::closure_env$0>
                               at *************\helix-term\src\ui\mod.rs:381
  31:     0x7ff7d2a17d40 - core::iter::adapters::filter_map::filter_map_try_fold::closure$0<enum$<core::result::Result<ignore::walk::DirEntry,enum$<ignore::Error> > >,tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,tuple$<>,enum$<core::ops::control_flow:
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\adapters\filter_map.rs:46
  32:     0x7ff7d29a353f - core::iter::traits::iterator::Iterator::try_fold<ignore::walk::Walk,tuple$<>,core::iter::adapters::filter_map::filter_map_try_fold::closure_env$0<enum$<core::result::Result<ignore::walk::DirEntry,enum$<ignore::Error> > >,tuple$<core::ops::range::RangeFrom
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\traits\iterator.rs:2109
  33:     0x7ff7d2a19b7c - core::iter::adapters::filter_map::impl$2::try_fold<tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,ignore::walk::Walk,helix_term::ui::completers::filename_impl::closure_env$1<helix_term::ui::completers::filename::closure_env$0>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\adapters\filter_map.rs:77
  34:     0x7ff7d2a1c63e - core::iter::traits::iterator::Iterator::find<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers::filename_impl::closure_env$1<helix_term::ui::completers::filename::closure_env$0> >,ref_mut$<helix_term::ui::completers
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\traits\iterator.rs:2577
  35:     0x7ff7d2a1d23c - core::iter::adapters::filter::impl$2::next<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers::filename_impl::closure_env$1<helix_term::ui::completers::filename::closure_env$0> >,helix_term::ui::completers::filename_
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\adapters\filter.rs:56
  36:     0x7ff7d26b5565 - alloc::vec::spec_from_iter_nested::impl$0::from_iter<tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\alloc\src\vec\spec_from_iter_nested.rs:26
  37:     0x7ff7d26c17f0 - alloc::vec::spec_from_iter::impl$0::from_iter<tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers::filen
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\alloc\src\vec\spec_from_iter.rs:33
  38:     0x7ff7d26dc245 - alloc::vec::impl$17::from_iter<tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str> > >,core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers::filename_impl::closu
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\alloc\src\vec\mod.rs:2552
  39:     0x7ff7d2a1dec0 - core::iter::traits::iterator::Iterator::collect<core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<ignore::walk::Walk,helix_term::ui::completers::filename_impl::closure_env$1<helix_term::ui::completers::filename::closure_env$
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\iter\traits\iterator.rs:1778
  40:     0x7ff7d28f010b - helix_term::ui::completers::filename_impl<helix_term::ui::completers::filename::closure_env$0>
                               at *************\helix-term\src\ui\mod.rs:376
  41:     0x7ff7d28d566a - helix_term::ui::completers::filename
                               at *************\helix-term\src\ui\mod.rs:290
  42:     0x7ff7d277ebbb - helix_term::commands::typed::command_mode::closure$0
                               at *************\helix-term\src\commands\typed.rs:1613
  43:     0x7ff7d279be6a - alloc::boxed::impl$45::call_mut<tuple$<ref$<helix_view::editor::Editor>,str>,dyn$<core::ops::function::FnMut<tuple$<ref$<helix_view::editor::Editor>,str>,assoc$<Output,alloc::vec::Vec<tuple$<core::ops::range::RangeFrom<usize>,enum$<alloc::borrow::Cow<str>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\alloc\src\boxed.rs:1860
  44:     0x7ff7d2acb1a2 - helix_term::ui::prompt::Prompt::recalculate_completion
                               at *************\helix-term\src\ui\prompt.rs:89
  45:     0x7ff7d2acc218 - helix_term::ui::prompt::Prompt::delete_char_backwards
                               at *************\helix-term\src\ui\prompt.rs:227
  46:     0x7ff7d2acdfa7 - helix_term::ui::prompt::impl$2::handle_event
                               at *************\helix-term\src\ui\prompt.rs:473
  47:     0x7ff7d263c44d - helix_term::compositor::Compositor::handle_event
                               at *************\helix-term\src\compositor.rs:147
  48:     0x7ff7d263a033 - helix_term::application::Application::handle_terminal_events
                               at *************\helix-term\src\application.rs:382
  49:     0x7ff7d252d81c - helix_term::application::impl$0::event_loop::async_fn$0
                               at *************\helix-term\src\application.rs:236
  50:     0x7ff7d256efc9 - core::future::from_generator::impl$1::poll<helix_term::application::impl$0::event_loop::async_fn_env$0>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\future\mod.rs:84
  51:     0x7ff7d2533579 - helix_term::application::impl$0::run::async_fn$0
                               at *************\helix-term\src\application.rs:739
  52:     0x7ff7d256e235 - core::future::from_generator::impl$1::poll<helix_term::application::impl$0::run::async_fn_env$0>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\future\mod.rs:84
  53:     0x7ff7d255d01f - hx::main_impl::async_block$0
                               at *************\helix-term\src\main.rs:116
  54:     0x7ff7d256f3f5 - core::future::from_generator::impl$1::poll<hx::main_impl::async_block_env$0>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\future\mod.rs:84
  55:     0x7ff7d25753b0 - tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0> >
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\park\thread.rs:263
  56:     0x7ff7d2521b69 - tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<enum$<core::result::Result<i32,anyhow::Error> > >, 0, 1, Ready>,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0>
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\coop.rs:102
  57:     0x7ff7d253aad2 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<enum$<core::result::Result<i32,anyhow::Error> > >, 0, 1, Ready>,tokio
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\thread\local.rs:413
  58:     0x7ff7d253a657 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<enum$<core::result::Result<i32,anyhow::Error> > >, 0, 1, Ready>,tokio::pa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\thread\local.rs:389
  59:     0x7ff7d2574b89 - tokio::coop::with_budget
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\coop.rs:95
  60:     0x7ff7d2574b89 - tokio::coop::budget
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\coop.rs:72
  61:     0x7ff7d2574b89 - tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0> >
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\park\thread.rs:263
  62:     0x7ff7d255d815 - tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0> >
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\runtime\enter.rs:151
  63:     0x7ff7d25353ff - tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0> >
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\runtime\thread_pool\mod.rs:73
  64:     0x7ff7d256578d - tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<hx::main_impl::async_block_env$0> >
                               at C:\Users\quixo\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\runtime\mod.rs:477
  65:     0x7ff7d25416dd - hx::main_impl
                               at *************\helix-term\src\main.rs:118
  66:     0x7ff7d2541569 - hx::main
                               at *************\helix-term\src\main.rs:35
  67:     0x7ff7d256001b - core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,anyhow::Error>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops\function.rs:227
  68:     0x7ff7d255969b - std::sys_common::backtrace::__rust_begin_short_backtrace<enum$<core::result::Result<tuple$<>,anyhow::Error>, 1, 18446744073709551615, Err> (*)(),enum$<core::result::Result<tuple$<>,anyhow::Error>, 1, 18446744073709551615, Err> >
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\sys_common\backtrace.rs:122
  69:     0x7ff7d2550d31 - std::rt::lang_start::closure$0<enum$<core::result::Result<tuple$<>,anyhow::Error>, 1, 18446744073709551615, Err> >
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\rt.rs:145
  70:     0x7ff7d38852af - core::ops::function::impls::impl$2::call_once
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops\function.rs:259
  71:     0x7ff7d38852af - std::panicking::try::do_call
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:492
  72:     0x7ff7d38852af - std::panicking::try
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:456
  73:     0x7ff7d38852af - std::panic::catch_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panic.rs:137
  74:     0x7ff7d38852af - std::rt::lang_start_internal::closure$2
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\rt.rs:128
  75:     0x7ff7d38852af - std::panicking::try::do_call
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:492
  76:     0x7ff7d38852af - std::panicking::try
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:456
  77:     0x7ff7d38852af - std::panic::catch_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panic.rs:137
  78:     0x7ff7d38852af - std::rt::lang_start_internal
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\rt.rs:128
  79:     0x7ff7d2550cff - std::rt::lang_start<enum$<core::result::Result<tuple$<>,anyhow::Error>, 1, 18446744073709551615, Err> >
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\rt.rs:144
  80:     0x7ff7d2541836 - main
  81:     0x7ff7d38d7f3c - invoke_main
                               at d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  82:     0x7ff7d38d7f3c - __scrt_common_main_seh
                               at d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  83:     0x7fffd2a754e0 - BaseThreadInitThunk
  84:     0x7fffd4b2485b - RtlUserThreadStart
```

The error without `RUST_BACKTRACE=1` for release is

> thread 'main' panicked at 'range start index 2 out of range for slice of length 0', library\std\src\path.rs:723:24

### Platform

Windows

### Terminal Emulator

I don't know, I'm using PowerShell

### Helix Version

helix 22.03 (d4e45fd4) for release, 22.03-162-g2c60798b when building from source

**Comment by kirawi** [comment]
I'm able to replicate.

**Comment by quixoticaxis** [comment]
I've updated my initial post, because I noticed that transcript somehow failed to capture the beginning of the stack trace.

**Comment by pascalkuthe** [comment]
I am pretty sure this was fixed.Its kind of hard to tell now what exactly caused this but there were multiple related fixes to the completors. I tested the reproduction case on wine and it now opens `C:\hx.exe`  so at least not a crash.

If you still run into this issue on lastest master feel free to reopen or create a new issue

**Comment by quixoticaxis** [comment]
I checked the latest pre-built binary, and crash no longer reproduces.
I should note though that `open C:hx.exe` currently does not open `C:\hx.exe` (there is probably no such file), but instead opens `CURRENT_DIRECTORY\hx.exe`.

**Comment by quixoticaxis** [comment]
Actually you may use any uppercase letter:
1. type A:
2. press Tab
3. you'd get A:some_file_from_current_directory autocompletion
4. press ENTER
5. some_file_from_current_directory is opened.
