### ISSUE TITLE
Can not build from source on Ubuntu 20.04

### ISSUE THREAD

**Issue by jarrodhroberson** [helix-editor/helix#2353]
### Summary

clean clone of repo and it will not compile.

tried with and with out `--recurse-submodules` get the same error either way.

### Reproduction Steps

 

I tried this:

1. followed install from source instructions

I expected this to happen:

it to compile and install

Instead, this happened:

```
error: failed to run custom build command for `helix-term v0.6.0 (/home/jhr/git/helix/helix-term)`

Caused by:
  process didn't exit successfully: `/home/jhr/git/helix/target/release/build/helix-term-6ae4485ccde53e15/build-script-build` (exit status: 101)
  --- stdout
  Grammar 'protobuf' checked out at '19c211a01434d9f03efff99f85e19f967591b175'.
  Grammar 'json' checked out at '65bceef69c3b0f24c0b19ce67d79f57c96e90fcb'.
  Grammar 'html' checked out at 'd93af487cc75120c89257195e6be46c999c6ba18'.
  Grammar 'gowork' checked out at '6dd9dd79fb51e9f2abc829d5e97b15015b6a8ae2'.
  Grammar 'rust' checked out at 'a360da0a29a19c281d08295a35ecd0544d2da211'.
  Grammar 'c' checked out at 'f05e279aedde06a25801c3f2b2cc8ac17fac52ae'.
  Grammar 'go' checked out at '0fa917a7022d1cd2e9b779a6a8fc5dc7fad69c75'.
  Grammar 'fish' checked out at '04e54ab6585dfd4fee6ddfe5849af56f101b6d4f'.
  Grammar 'toml' checked out at '7cff70bbcbbc62001b465603ca1ea88edd668704'.
  Grammar 'gomod' checked out at 'e8f51f8e4363a3d9a427e8f63f4c1bbc5ef5d8d0'.
  Grammar 'twig' checked out at 'b7444181fb38e603e25ea8fcdac55f9492e49c27'.
  Grammar 'bash' checked out at '275effdfc0edce774acf7d481f9ea195c6c403cd'.
  Grammar 'cpp' checked out at 'e8dcc9d2b404c542fd236ea5f7208f90be8a6e89'.
  Grammar 'nix' checked out at '50f38ceab667f9d482640edfee803d74f4edeba5'.
  Grammar 'php' checked out at '57f855461aeeca73bd4218754fb26b5ac143f98f'.
  Grammar 'elixir' checked out at '1dabc1c790e07115175057863808085ea60dd08a'.
  Grammar 'python' checked out at 'd6210ceab11e8d812d4ab59c07c81458ec6e5184'.
  Grammar 'css' checked out at '94e10230939e702b4fa3fa2cb5c3bc7173b95d07'.
  Grammar 'ruby' checked out at 'dfff673b41df7fadcbb609c6338f38da3cdd018e'.
  Grammar 'c-sharp' checked out at '53a65a908167d6556e1fcdb67f1ee62aac101dda'.
  Grammar 'nickel' checked out at 'c4dd1420b6cfeb6103d38eb1ce5195eb81197edc'.
  Grammar 'ledger' checked out at '0cdeb0e51411a3ba5493662952c3039de08939ca'.
  Grammar 'java' checked out at 'bd6186c24d5eb13b4623efac9d944dcc095c0dad'.
  Grammar 'javascript' checked out at '4a95461c4761c624f2263725aca79eeaefd36cad'.
  Grammar 'tsx' checked out at '3e897ea5925f037cfae2e551f8e6b12eec2a201a'.
  Grammar 'svelte' checked out at '349a5984513b4a4a9e143a6e746120c6ff6cf6ed'.
  Grammar 'julia' checked out at '12ea597262125fc22fd2e91aa953ac69b19c26ca'.
  Grammar 'yaml' checked out at '0e36bed171768908f331ff7dff9d956bae016efb'.
  Grammar 'tsq' checked out at 'b665659d3238e6036e22ed0e24935e60efb39415'.
  Grammar 'make' checked out at 'a4b9187417d6be349ee5fd4b6e77b4172c6827dd'.
  Grammar 'cmake' checked out at 'f6616f1e417ee8b62daf251aa1daa5d73781c596'.
  Grammar 'zig' checked out at '93331b8bd8b4ebee2b575490b2758f16ad4e9f30'.
  Grammar 'vue' checked out at '91fe2754796cd8fba5f229505a23fa08f3546c06'.
  Grammar 'comment' checked out at '5dd3c62f1bbe378b220fe16b317b85247898639e'.
  Grammar 'tablegen' checked out at '568dd8a937347175fd58db83d4c4cdaeb6069bd2'.
  Grammar 'llvm-mir' checked out at '06fabca19454b2dc00c1b211a7cb7ad0bc2585f1'.
  Grammar 'latex' checked out at '7f720661de5316c0f8fee956526d4002fa1086d8'.
  Grammar 'llvm' checked out at '3b213925b9c4f42c1acfe2e10bfbb438d9c6834d'.
  Grammar 'glsl' checked out at '88408ffc5e27abcffced7010fc77396ae3636d7e'.
  Grammar 'dart' checked out at '6a25376685d1d47968c2cef06d4db8d84a70025e'.
  Grammar 'git-diff' checked out at 'c12e6ecb54485f764250556ffd7ccb18f8e2942b'.
  Grammar 'git-commit' checked out at '7ae23de633de41f8f5b802f6f05b6596df6d00c1'.
  Grammar 'haskell' checked out at 'b6ec26f181dd059eedd506fa5fbeae1b8e5556c8'.
  Grammar 'dockerfile' checked out at '7af32bc04a66ab196f5b9f92ac471f29372ae2ce'.
  Grammar 'markdown' checked out at 'ad8c32917a16dfbb387d1da567bf0c3fb6fffde2'.
  Grammar 'typescript' checked out at '3e897ea5925f037cfae2e551f8e6b12eec2a201a'.
  Grammar 'regex' checked out at 'e1cfca3c79896ff79842f057ea13e529b66af636'.
  Grammar 'wgsl' checked out at 'f00ff52251edbd58f4d39c9c3204383253032c11'.
  Grammar 'graphql' checked out at '5e66e961eee421786bdda8495ed1db045e06b5fe'.
  Grammar 'git-rebase' checked out at '332dc528f27044bc4427024dbb33e6941fc131f2'.
  Grammar 'git-config' checked out at '0e4f0baf90b57e5aeb62dcdbf03062c6315d43ea'.
  Grammar 'iex' checked out at '39f20bb51f502e32058684e893c0c0b00bb2332c'.
  Grammar 'scala' checked out at '0a3dd53a7fc4b352a538397d054380aaa28be54c'.
  Grammar 'elm' checked out at 'bd50ccf66b42c55252ac8efc1086af4ac6bab8cd'.
  Grammar 'rescript' checked out at '4cd7ba91696886fdaca086fb32b5fd8cc294a129'.
  Grammar 'erlang' checked out at '3f611cfdc790214c3f9f9cf1658b3ae8039c54b8'.
  Grammar 'perl' checked out at '0ac2c6da562c7a2c26ed7e8691d4a590f7e8b90a'.
  Grammar 'org' checked out at '1c3eb533a9cf6800067357b59e03ac3f91fc3a54'.
  Grammar 'lua' checked out at '6f5d40190ec8a0aa8c8410699353d820f4f7d7a6'.
  Grammar 'hcl' checked out at '3cb7fc28247efbcb2973b97e71c78838ad98a583'.
  Grammar 'gleam' checked out at '7159ce961592192b0e7cdf88782cda0fdf41a4cb'.
  Grammar 'embedded-template' checked out at 'd21df11b0ecc6fd211dbe11278e92ef67bd17e97'.
  Grammar 'eex' checked out at 'f742f2fe327463335e8671a87c0b9b396905d1d1'.
  Grammar 'r' checked out at 'cc04302e1bff76fa02e129f332f44636813b0c3c'.
  Grammar 'heex' checked out at '592e22292a367312c35e13de7fdb888f029981d6'.
  Grammar 'sql' checked out at '0caa7fa2ee00e0b770493a79d4efacc1fc376cc5'.
  Grammar 'gdscript' checked out at '2a6abdaa47fcb91397e09a97c7433fd995ea46c6'.
  Grammar 'nu' checked out at 'db4e990b78824c8abef3618e0f93b7fe1e8f4c0d'.
  Grammar 'solidity' checked out at 'f3a002274744e859bf64cf3524985f8c31ea84fd'.
  Grammar 'devicetree' checked out at '877adbfa0174d25894c40fa75ad52d4515a36368'.
  Grammar 'vala' checked out at 'c9eea93ba2ec4ec1485392db11945819779745b3'.
  Grammar 'cairo' checked out at '5155c6eb40db6d437f4fa41b8bcd8890a1c91716'.
  Grammar 'ocaml-interface' checked out at '23d419ba45789c5a47d31448061557716b02750a'.
  Grammar 'ocaml' checked out at '23d419ba45789c5a47d31448061557716b02750a'.
  Grammar 'hare' checked out at 'bc26a6a949f2e0d98b7bfc437d459b250900a165'.
  Grammar 'swift' checked out at 'e75240f89bb3bfd3396155859ae364e5c58d7377'.
  Grammar 'kotlin' checked out at 'a4f71eb9b8c9b19ded3e0e9470be4b1b77c2b569'.
  Grammar 'lean' checked out at 'd98426109258b266e1e92358c5f11716d2e8f638'.
  Building grammar 'rust'
  Building grammar 'protobuf'
  Building grammar 'toml'
  Building grammar 'elixir'
  Building grammar 'fish'
  Building grammar 'c'
  Building grammar 'json'
  Building grammar 'c-sharp'
  Building grammar 'go'
  Building grammar 'gomod'
  Building grammar 'cpp'
  Building grammar 'gowork'
  Building grammar 'typescript'
  Building grammar 'css'
  Building grammar 'python'
  Building grammar 'nix'
  Building grammar 'ruby'
  Building grammar 'nickel'
  Building grammar 'bash'
  Building grammar 'html'
  Building grammar 'javascript'
  Building grammar 'tsx'
  Building grammar 'php'
  Building grammar 'twig'
  Building grammar 'lean'
  Building grammar 'latex'
  Building grammar 'julia'
  Building grammar 'java'
  Building grammar 'ledger'

  --- stderr
  thread 'thread 'main' panicked at '<unnamed>Failed to compile tree-sitter grammars: Failed to build some grammar(s)

  Caused by:
      0: Failed to execute C compiler
      1: No such file or directory (os error 2)' panicked at '', called `Result::unwrap()` on an `Err` value: SendError { .. }helix-term/build.rs:', 22:26helix-loader/src/grammar.rs
  :note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }called `Result::unwrap()` on an `Err` value: SendError { .. }', ', helix-loader/src/grammar.rshelix-loader/src/grammar.rs::136136::3535

  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/home/jhr/git/helix/helix-term)`, intermediate artifacts can be found at `/home/jhr/git/helix/target`
```

### Helix log

<details><summary>cargo install --path helix-term</summary>

```
error: failed to run custom build command for `helix-term v0.6.0 (/home/jhr/git/helix/helix-term)`

Caused by:
  process didn't exit successfully: `/home/jhr/git/helix/target/release/build/helix-term-6ae4485ccde53e15/build-script-build` (exit status: 101)
  --- stdout
  Grammar 'protobuf' checked out at '19c211a01434d9f03efff99f85e19f967591b175'.
  Grammar 'json' checked out at '65bceef69c3b0f24c0b19ce67d79f57c96e90fcb'.
  Grammar 'html' checked out at 'd93af487cc75120c89257195e6be46c999c6ba18'.
  Grammar 'gowork' checked out at '6dd9dd79fb51e9f2abc829d5e97b15015b6a8ae2'.
  Grammar 'rust' checked out at 'a360da0a29a19c281d08295a35ecd0544d2da211'.
  Grammar 'c' checked out at 'f05e279aedde06a25801c3f2b2cc8ac17fac52ae'.
  Grammar 'go' checked out at '0fa917a7022d1cd2e9b779a6a8fc5dc7fad69c75'.
  Grammar 'fish' checked out at '04e54ab6585dfd4fee6ddfe5849af56f101b6d4f'.
  Grammar 'toml' checked out at '7cff70bbcbbc62001b465603ca1ea88edd668704'.
  Grammar 'gomod' checked out at 'e8f51f8e4363a3d9a427e8f63f4c1bbc5ef5d8d0'.
  Grammar 'twig' checked out at 'b7444181fb38e603e25ea8fcdac55f9492e49c27'.
  Grammar 'bash' checked out at '275effdfc0edce774acf7d481f9ea195c6c403cd'.
  Grammar 'cpp' checked out at 'e8dcc9d2b404c542fd236ea5f7208f90be8a6e89'.
  Grammar 'nix' checked out at '50f38ceab667f9d482640edfee803d74f4edeba5'.
  Grammar 'php' checked out at '57f855461aeeca73bd4218754fb26b5ac143f98f'.
  Grammar 'elixir' checked out at '1dabc1c790e07115175057863808085ea60dd08a'.
  Grammar 'python' checked out at 'd6210ceab11e8d812d4ab59c07c81458ec6e5184'.
  Grammar 'css' checked out at '94e10230939e702b4fa3fa2cb5c3bc7173b95d07'.
  Grammar 'ruby' checked out at 'dfff673b41df7fadcbb609c6338f38da3cdd018e'.
  Grammar 'c-sharp' checked out at '53a65a908167d6556e1fcdb67f1ee62aac101dda'.
  Grammar 'nickel' checked out at 'c4dd1420b6cfeb6103d38eb1ce5195eb81197edc'.
  Grammar 'ledger' checked out at '0cdeb0e51411a3ba5493662952c3039de08939ca'.
  Grammar 'java' checked out at 'bd6186c24d5eb13b4623efac9d944dcc095c0dad'.
  Grammar 'javascript' checked out at '4a95461c4761c624f2263725aca79eeaefd36cad'.
  Grammar 'tsx' checked out at '3e897ea5925f037cfae2e551f8e6b12eec2a201a'.
  Grammar 'svelte' checked out at '349a5984513b4a4a9e143a6e746120c6ff6cf6ed'.
  Grammar 'julia' checked out at '12ea597262125fc22fd2e91aa953ac69b19c26ca'.
  Grammar 'yaml' checked out at '0e36bed171768908f331ff7dff9d956bae016efb'.
  Grammar 'tsq' checked out at 'b665659d3238e6036e22ed0e24935e60efb39415'.
  Grammar 'make' checked out at 'a4b9187417d6be349ee5fd4b6e77b4172c6827dd'.
  Grammar 'cmake' checked out at 'f6616f1e417ee8b62daf251aa1daa5d73781c596'.
  Grammar 'zig' checked out at '93331b8bd8b4ebee2b575490b2758f16ad4e9f30'.
  Grammar 'vue' checked out at '91fe2754796cd8fba5f229505a23fa08f3546c06'.
  Grammar 'comment' checked out at '5dd3c62f1bbe378b220fe16b317b85247898639e'.
  Grammar 'tablegen' checked out at '568dd8a937347175fd58db83d4c4cdaeb6069bd2'.
  Grammar 'llvm-mir' checked out at '06fabca19454b2dc00c1b211a7cb7ad0bc2585f1'.
  Grammar 'latex' checked out at '7f720661de5316c0f8fee956526d4002fa1086d8'.
  Grammar 'llvm' checked out at '3b213925b9c4f42c1acfe2e10bfbb438d9c6834d'.
  Grammar 'glsl' checked out at '88408ffc5e27abcffced7010fc77396ae3636d7e'.
  Grammar 'dart' checked out at '6a25376685d1d47968c2cef06d4db8d84a70025e'.
  Grammar 'git-diff' checked out at 'c12e6ecb54485f764250556ffd7ccb18f8e2942b'.
  Grammar 'git-commit' checked out at '7ae23de633de41f8f5b802f6f05b6596df6d00c1'.
  Grammar 'haskell' checked out at 'b6ec26f181dd059eedd506fa5fbeae1b8e5556c8'.
  Grammar 'dockerfile' checked out at '7af32bc04a66ab196f5b9f92ac471f29372ae2ce'.
  Grammar 'markdown' checked out at 'ad8c32917a16dfbb387d1da567bf0c3fb6fffde2'.
  Grammar 'typescript' checked out at '3e897ea5925f037cfae2e551f8e6b12eec2a201a'.
  Grammar 'regex' checked out at 'e1cfca3c79896ff79842f057ea13e529b66af636'.
  Grammar 'wgsl' checked out at 'f00ff52251edbd58f4d39c9c3204383253032c11'.
  Grammar 'graphql' checked out at '5e66e961eee421786bdda8495ed1db045e06b5fe'.
  Grammar 'git-rebase' checked out at '332dc528f27044bc4427024dbb33e6941fc131f2'.
  Grammar 'git-config' checked out at '0e4f0baf90b57e5aeb62dcdbf03062c6315d43ea'.
  Grammar 'iex' checked out at '39f20bb51f502e32058684e893c0c0b00bb2332c'.
  Grammar 'scala' checked out at '0a3dd53a7fc4b352a538397d054380aaa28be54c'.
  Grammar 'elm' checked out at 'bd50ccf66b42c55252ac8efc1086af4ac6bab8cd'.
  Grammar 'rescript' checked out at '4cd7ba91696886fdaca086fb32b5fd8cc294a129'.
  Grammar 'erlang' checked out at '3f611cfdc790214c3f9f9cf1658b3ae8039c54b8'.
  Grammar 'perl' checked out at '0ac2c6da562c7a2c26ed7e8691d4a590f7e8b90a'.
  Grammar 'org' checked out at '1c3eb533a9cf6800067357b59e03ac3f91fc3a54'.
  Grammar 'lua' checked out at '6f5d40190ec8a0aa8c8410699353d820f4f7d7a6'.
  Grammar 'hcl' checked out at '3cb7fc28247efbcb2973b97e71c78838ad98a583'.
  Grammar 'gleam' checked out at '7159ce961592192b0e7cdf88782cda0fdf41a4cb'.
  Grammar 'embedded-template' checked out at 'd21df11b0ecc6fd211dbe11278e92ef67bd17e97'.
  Grammar 'eex' checked out at 'f742f2fe327463335e8671a87c0b9b396905d1d1'.
  Grammar 'r' checked out at 'cc04302e1bff76fa02e129f332f44636813b0c3c'.
  Grammar 'heex' checked out at '592e22292a367312c35e13de7fdb888f029981d6'.
  Grammar 'sql' checked out at '0caa7fa2ee00e0b770493a79d4efacc1fc376cc5'.
  Grammar 'gdscript' checked out at '2a6abdaa47fcb91397e09a97c7433fd995ea46c6'.
  Grammar 'nu' checked out at 'db4e990b78824c8abef3618e0f93b7fe1e8f4c0d'.
  Grammar 'solidity' checked out at 'f3a002274744e859bf64cf3524985f8c31ea84fd'.
  Grammar 'devicetree' checked out at '877adbfa0174d25894c40fa75ad52d4515a36368'.
  Grammar 'vala' checked out at 'c9eea93ba2ec4ec1485392db11945819779745b3'.
  Grammar 'cairo' checked out at '5155c6eb40db6d437f4fa41b8bcd8890a1c91716'.
  Grammar 'ocaml-interface' checked out at '23d419ba45789c5a47d31448061557716b02750a'.
  Grammar 'ocaml' checked out at '23d419ba45789c5a47d31448061557716b02750a'.
  Grammar 'hare' checked out at 'bc26a6a949f2e0d98b7bfc437d459b250900a165'.
  Grammar 'swift' checked out at 'e75240f89bb3bfd3396155859ae364e5c58d7377'.
  Grammar 'kotlin' checked out at 'a4f71eb9b8c9b19ded3e0e9470be4b1b77c2b569'.
  Grammar 'lean' checked out at 'd98426109258b266e1e92358c5f11716d2e8f638'.
  Building grammar 'rust'
  Building grammar 'protobuf'
  Building grammar 'toml'
  Building grammar 'elixir'
  Building grammar 'fish'
  Building grammar 'c'
  Building grammar 'json'
  Building grammar 'c-sharp'
  Building grammar 'go'
  Building grammar 'gomod'
  Building grammar 'cpp'
  Building grammar 'gowork'
  Building grammar 'typescript'
  Building grammar 'css'
  Building grammar 'python'
  Building grammar 'nix'
  Building grammar 'ruby'
  Building grammar 'nickel'
  Building grammar 'bash'
  Building grammar 'html'
  Building grammar 'javascript'
  Building grammar 'tsx'
  Building grammar 'php'
  Building grammar 'twig'
  Building grammar 'lean'
  Building grammar 'latex'
  Building grammar 'julia'
  Building grammar 'java'
  Building grammar 'ledger'

  --- stderr
  thread 'thread 'main' panicked at '<unnamed>Failed to compile tree-sitter grammars: Failed to build some grammar(s)

  Caused by:
      0: Failed to execute C compiler
      1: No such file or directory (os error 2)' panicked at '', called `Result::unwrap()` on an `Err` value: SendError { .. }helix-term/build.rs:', 22:26helix-loader/src/grammar.rs
  :note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }called `Result::unwrap()` on an `Err` value: SendError { .. }', ', helix-loader/src/grammar.rshelix-loader/src/grammar.rs::136136::3535

  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', helix-loader/src/grammar.rs:136:35
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/home/jhr/git/helix/helix-term)`, intermediate artifacts can be found at `/home/jhr/git/helix/target`
```

</details>

### Platform

Distributor ID: Ubuntu Description:    Ubuntu 20.04.4 LTS Release:        20.04 Codename:       focal

### Terminal Emulator

microsoft terminal 

### Helix Version

22.03-167-gede01b5f

**Comment by the-mikedavis** [comment]
Can you try `rm -rf runtime/grammars/*` in the source directory and trying again? It looks like something may have failed to clone but I'm not sure.

**Comment by colaxdev** [comment]
Try updating the repository and install the `build-essential` package. If it doesn't work, update your system

**Comment by kajih** [comment]
I had the same problem, turned out it was low memory and I fixed it by adding a memory swap file.
