### ISSUE TITLE
Crash when saving simple PHP class

### ISSUE THREAD

**Issue by frexsdev** [helix-editor/helix#2360]
### Summary

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 79, Rope/RopeSlice char length 75', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.4.1/src/rope.rs:690:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction Steps

- hx file.php
**SAVE** = **CRASH**

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-05-01T15:07:46.378 helix_lsp [ERROR] unhandled LSP notification: indexingStarted
2022-05-01T15:07:56.015 helix_lsp [ERROR] unhandled LSP notification: indexingEnded
```

</details>

### Platform

Linux

### Terminal Emulator

wezterm 20220408-101518-b908e2dd

### Helix Version

22.03-167-gede01b5f

**Comment by kirawi** [comment]
What was the file?

**Comment by colaxdev** [comment]
The **FULL** error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 787, Rope/RopeSlice char length 784', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.4.1/src/rope.rs:690:41
stack backtrace:
   0:     0x55e0d49851e4 - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e0d49851e4 - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e0d49851e4 - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e0d49851e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e0d42aaf5c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55e0d497d7ca - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55e0d4987fe6 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e0d4987fe6 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e0d4987fe6 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55e0d4987d02 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x55e0d4849429 - helix_term::application::Application::run::{{closure}}::{{closure}}::h93a23d194c521e02
  11:     0x55e0d49887f8 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  12:     0x55e0d49884a4 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  13:     0x55e0d4985724 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x55e0d498820d - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  15:     0x55e0d4233413 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  16:     0x55e0d4233503 - core::result::unwrap_failed::h719f957ed74f93fd
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  17:     0x55e0d4484a73 - ropey::rope::Rope::char_to_line::h39fbc32261c7cbb0
  18:     0x55e0d44e676a - helix_lsp::client::Client::changeset_to_changes::hb6342c1cda7e7112
  19:     0x55e0d44e7241 - helix_lsp::client::Client::text_document_did_change::h7b1606e96f1f4c4e
  20:     0x55e0d47e4c94 - helix_view::document::Document::apply_impl::h9e14d2d4d5ea2146
  21:     0x55e0d47e52c7 - helix_view::document::Document::apply::he235e75970443b2c
  22:     0x55e0d4739200 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h800663446f5695a1
  23:     0x55e0d468a05f - helix_term::job::Jobs::handle_callback::h744a8744ebf253cb
  24:     0x55e0d4845e3c - helix_term::application::Application::event_loop::{{closure}}::h40c5da8279d0630f
  25:     0x55e0d485a193 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3070eb42e3789ea8
  26:     0x55e0d4824d3c - tokio::park::thread::CachedParkThread::block_on::ha23f7aa16c43dfb6
  27:     0x55e0d481c1a9 - tokio::runtime::thread_pool::ThreadPool::block_on::h9a11016ae998e5e0
  28:     0x55e0d483d2b8 - tokio::runtime::Runtime::block_on::h84509510252a1161
  29:     0x55e0d4823de6 - hx::main::h4fb2116a13c06f64
  30:     0x55e0d47f78d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he8170ec16898ae92
  31:     0x55e0d483d01d - std::rt::lang_start::{{closure}}::h9964c91072d85f17
  32:     0x55e0d498484f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  33:     0x55e0d498484f - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  34:     0x55e0d498484f - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  35:     0x55e0d498484f - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  36:     0x55e0d498484f - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  37:     0x55e0d498484f - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  38:     0x55e0d498484f - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  39:     0x55e0d498484f - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  40:     0x55e0d498484f - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  41:     0x55e0d4827aa2 - main
  42:     0x7f0a3e8c2310 - __libc_start_call_main
  43:     0x7f0a3e8c23c1 - __libc_start_main@GLIBC_2.2.5
  44:     0x55e0d42617e5 - _start
  45:                0x0 - <unknown>
```

The file is a simple PHP class

**Comment by kirawi** [comment]
For reproduction purposes, could you provide the file?

**Comment by danielyrovas** [comment]
I got the same just now running no LSP server on a markdown file.

**Comment by archseer** [comment]
The error seems to originate from a callback received from a LSP though. Probably the formatting callback.

**Comment by colaxdev** [comment]
I think the it's is the LSP. Maybe add a special config where we fix this ? like:

```toml
[[lang]]
name = "php"
fix_lsp = true
```
