### ISSUE TITLE
Changing Keymaps in source panicks

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#2396]
I use the cole make keyboard layout. I made a python script to change all the defualt keybindings.
```python
colemak = {
    "e": "f",
    "E": "F",
    "r": "p",
    "R": "P",
    "t": "g",
    "T": "G",
    "y": "j",
    "Y": "J",
    "u": "l",
    "U": "L",
    "i": "u",
    "I": "U",
    "o": "y",
    "O": "Y",
    "p": ";",
    "P": ":",
    "s": "r",
    "S": "R",
    "d": "s",
    "D": "S",
    "f": "t",
    "F": "T",
    "g": "d",
    "G": "D",
    "j": "n",
    "J": "N",
    "k": "e",
    "K": "E",
    "l": "i",
    "L": "I",
    ";": "o",
    ":": "O",
    "n": "k",
    "N": "K",
}
data = ""
with open('helix-term/src/keymap/default.rs', 'r') as file:
    data = file.read()
    for i in colemak:
        data = data.replace(f'"{i}"', f'"!{colemak[i]}"')
    data = data.replace('"!', '"')
    file.close()

print(data)

with open('helix-term/src/keymap/default.rs', 'w') as file:
    file.write(data)
    file.close()
```
compiling and installing it doesn't produce any error but while running it panics
```
❯ hx
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid key code ''', helix-term/src/keymap/default.rs:8:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with the env var

```
 ❯ RUST_BACKTRACE=1 hx
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid key code ''', helix-term/src/keymap/default.rs:8:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: helix_term::keymap::default::default
   4: <&mut toml::de::Deserializer as serde::de::Deserializer>::deserialize_struct
   5: helix_term::application::Application::new
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::park::thread::CachedParkThread::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::Runtime::block_on
  10: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by archseer** [comment]
Can you show the generated file? 

I don't recommend you modify the code in this way btw, you'll likely have issues as we change the code up

**Comment by IsotoxalDev** [comment]
I know modifying this way is bad but it is tiring to change every damn keys manually
```rs
use std::collections::HashMap;

use super::macros::keymap;
use super::{Keymap, Mode};
use helix_core::hashmap;

pub fn default() -> HashMap<Mode, Keymap> {
    let normal = keymap!({ "Normal mode"
        "h" | "left" => move_char_left,
        "n" | "down" => move_line_down,
        "e" | "up" => move_line_up,
        "i" | "right" => move_char_right,

        "g" => find_till_char,
        "t" => find_next_char,
        "G" => till_prev_char,
        "T" => find_prev_char,
        "p" => replace,
        "P" => replace_with_yanked,
        "A-." =>  repeat_last_motion,

        "~" => switch_case,
        "`" => switch_to_lowercase,
        "A-`" => switch_to_uppercase,

        "home" => goto_line_start,
        "end" => goto_line_end,

        "w" => move_next_word_start,
        "b" => move_prev_word_start,
        "f" => move_next_word_end,

        "W" => move_next_long_word_start,
        "B" => move_prev_long_word_start,
        "F" => move_next_long_word_end,

        "v" => select_mode,
        "D" => goto_line,
        "d" => { "Goto"
            "d" => goto_file_start,
            "f" => goto_last_line,
            "t" => goto_file,
            "h" => goto_line_start,
            "i" => goto_line_end,
            "r" => goto_first_nonwhitespace,
            "s" => goto_definition,
            "j" => goto_type_definition,
            "p" => goto_reference,
            "u" => goto_implementation,
            "g" => goto_window_top,
            "c" => goto_window_center,
            "b" => goto_window_bottom,
            "a" => goto_last_accessed_file,
            "m" => goto_last_modified_file,
            "k" => goto_next_buffer,
            ";" => goto_previous_buffer,
            "." => goto_last_modification,
        },
        "O" => command_mode,

        "u" => insert_mode,
        "U" => prepend_to_line,
        "a" => append_mode,
        "A" => append_to_line,
        "y" => open_below,
        "Y" => open_above,

        "s" => delete_selection,
        "A-d" => delete_selection_noyank,
        "c" => change_selection,
        "A-c" => change_selection_noyank,

        "C" => copy_selection_on_next_line,
        "A-C" => copy_selection_on_prev_line,


        "r" => select_regex,
        "A-s" => split_selection_on_newline,
        "R" => split_selection,
        "o" => collapse_selection,
        "A-;" => flip_selections,
        "A-o" | "A-up" => expand_selection,
        "A-i" | "A-down" => shrink_selection,
        "A-p" | "A-left" => select_prev_sibling,
        "A-n" | "A-right" => select_next_sibling,

        "%" => select_all,
        "x" => extend_line,
        "X" => extend_to_line_bounds,
        // crop_to_whole_line

        "m" => { "Match"
            "m" => match_brackets,
            "r" => surround_add,
            "p" => surround_replace,
            "s" => surround_delete,
            "a" => select_textobject_around,
            "u" => select_textobject_inner,
        },
        "[" => { "Left bracket"
            "s" => goto_prev_diag,
            "S" => goto_first_diag,
            "t" => goto_prev_function,
            "c" => goto_prev_class,
            "a" => goto_prev_parameter,
            "y" => goto_prev_comment,
            ";" => goto_prev_paragraph,
            "space" => add_newline_above,
        },
        "]" => { "Right bracket"
            "s" => goto_next_diag,
            "S" => goto_last_diag,
            "t" => goto_next_function,
            "c" => goto_next_class,
            "a" => goto_next_parameter,
            "y" => goto_next_comment,
            ";" => goto_next_paragraph,
            "space" => add_newline_below,
        },

        "/" => search,
        "?" => rsearch,
        "k" => search_next,
        "K" => search_prev,
        "*" => search_selection,

        "l" => undo,
        "L" => redo,
        "A-u" => earlier,
        "A-U" => later,

        "j" => yank,
        // yank_all
        ";" => paste_after,
        // paste_all
        ":" => paste_before,

        "Q" => record_macro,
        "q" => replay_macro,

        ">" => indent,
        "<" => unindent,
        "=" => format_selections,
        "N" => join_selections,
        "E" => keep_selections,
        "A-K" => remove_selections,

        "," => keep_primary_selection,
        "A-," => remove_primary_selection,

        // "q" => record_macro,
        // "Q" => replay_macro,

        "&" => align_selections,
        "_" => trim_selections,

        "(" => rotate_selections_backward,
        ")" => rotate_selections_forward,
        "A-(" => rotate_selection_contents_backward,
        "A-)" => rotate_selection_contents_forward,

        "A-:" => ensure_selections_forward,

        "esc" => normal_mode,
        "C-b" | "pageup" => page_up,
        "C-f" | "pagedown" => page_down,
        "C-u" => half_page_up,
        "C-d" => half_page_down,

        "C-w" => { "Window"
            "C-w" | "w" => rotate_view,
            "C-s" | "r" => hsplit,
            "C-v" | "v" => vsplit,
            "t" => goto_file_hsplit,
            "T" => goto_file_vsplit,
            "C-q" | "q" => wclose,
            "C-o" | "y" => wonly,
            "C-h" | "h" | "left" => jump_view_left,
            "C-j" | "n" | "down" => jump_view_down,
            "C-k" | "e" | "up" => jump_view_up,
            "C-l" | "i" | "right" => jump_view_right,
            "k" => { "New split scratch buffer"
                "C-s" | "r" => hsplit_new,
                "C-v" | "v" => vsplit_new,
            },
        },

        // move under <space>c
        "C-c" => toggle_comments,

        // z family for save/restore/combine from/to sels from register

        "tab" => jump_forward, // tab == <C-i>
        "C-o" => jump_backward,
        "C-s" => save_selection,

        "space" => { "Space"
            "t" => file_picker,
            "T" => file_picker_in_current_directory,
            "b" => buffer_picker,
            "r" => symbol_picker,
            "R" => workspace_symbol_picker,
            "a" => code_action,
            "'" => last_picker,
            "s" => { "Debug (experimental)" sticky=true
                "i" => dap_launch,
                "b" => dap_toggle_breakpoint,
                "c" => dap_continue,
                "h" => dap_pause,
                "u" => dap_step_in,
                "y" => dap_step_out,
                "k" => dap_next,
                "v" => dap_variables,
                "g" => dap_terminate,
                "C-c" => dap_edit_condition,
                "C-l" => dap_edit_log,
                "r" => { "Switch"
                    "g" => dap_switch_thread,
                    "t" => dap_switch_stack_frame,
                    // sl, sb
                },
                "f" => dap_enable_exceptions,
                "F" => dap_disable_exceptions,
            },
            "w" => { "Window"
                "C-w" | "w" => rotate_view,
                "C-s" | "r" => hsplit,
                "C-v" | "v" => vsplit,
                "t" => goto_file_hsplit,
                "T" => goto_file_vsplit,
                "C-q" | "q" => wclose,
                "C-o" | "y" => wonly,
                "C-h" | "h" | "left" => jump_view_left,
                "C-j" | "n" | "down" => jump_view_down,
                "C-k" | "e" | "up" => jump_view_up,
                "C-l" | "i" | "right" => jump_view_right,
                "k" => { "New split scratch buffer"
                    "C-s" | "r" => hsplit_new,
                    "C-v" | "v" => vsplit_new,
                },
            },
            "j" => yank_joined_to_clipboard,
            "J" => yank_main_selection_to_clipboard,
            ";" => paste_clipboard_after,
            ":" => paste_clipboard_before,
            "P" => replace_selections_with_clipboard,
            "/" => global_search,
            "e" => hover,
            "p" => rename_symbol,
            "?" => command_palette,
        },
        "z" => { "View"
            "z" | "c" => align_view_center,
            "g" => align_view_top,
            "b" => align_view_bottom,
            "m" => align_view_middle,
            "e" | "up" => scroll_up,
            "n" | "down" => scroll_down,
            "C-b" | "pageup" => page_up,
            "C-f" | "pagedown" => page_down,
            "C-u" => half_page_up,
            "C-d" => half_page_down,
        },
        "Z" => { "View" sticky=true
            "z" | "c" => align_view_center,
            "g" => align_view_top,
            "b" => align_view_bottom,
            "m" => align_view_middle,
            "e" | "up" => scroll_up,
            "n" | "down" => scroll_down,
            "C-b" | "pageup" => page_up,
            "C-f" | "pagedown" => page_down,
            "C-u" => half_page_up,
            "C-d" => half_page_down,
        },

        "\"" => select_register,
        "|" => shell_pipe,
        "A-|" => shell_pipe_to,
        "" => shell_insert_output,
        "A-!" => shell_append_output,
        "$" => shell_keep_pipe,
        "C-z" => suspend,

        "C-a" => increment,
        "C-x" => decrement,
    });
    let mut select = normal.clone();
    select.merge_nodes(keymap!({ "Select mode"
        "h" | "left" => extend_char_left,
        "n" | "down" => extend_line_down,
        "e" | "up" => extend_line_up,
        "i" | "right" => extend_char_right,

        "w" => extend_next_word_start,
        "b" => extend_prev_word_start,
        "f" => extend_next_word_end,
        "W" => extend_next_long_word_start,
        "B" => extend_prev_long_word_start,
        "F" => extend_next_long_word_end,

        "k" => extend_search_next,
        "K" => extend_search_prev,

        "g" => extend_till_char,
        "t" => extend_next_char,
        "G" => extend_till_prev_char,
        "T" => extend_prev_char,

        "home" => extend_to_line_start,
        "end" => extend_to_line_end,
        "esc" => exit_select_mode,

        "v" => normal_mode,
    }));
    let insert = keymap!({ "Insert mode"
        "esc" => normal_mode,

        "backspace" => delete_char_backward,
        "C-h" => delete_char_backward,
        "del" => delete_char_forward,
        "C-d" => delete_char_forward,
        "ret" => insert_newline,
        "C-j" => insert_newline,
        "tab" => insert_tab,
        "C-w" => delete_word_backward,
        "A-backspace" => delete_word_backward,
        "A-d" => delete_word_forward,
        "C-s" => commit_undo_checkpoint,

        "left" => move_char_left,
        "C-b" => move_char_left,
        "down" => move_line_down,
        "C-n" => move_line_down,
        "up" => move_line_up,
        "C-p" => move_line_up,
        "right" => move_char_right,
        "C-f" => move_char_right,
        "A-b" => move_prev_word_end,
        "C-left" => move_prev_word_end,
        "A-f" => move_next_word_start,
        "C-right" => move_next_word_start,
        "A-<" => goto_file_start,
        "A->" => goto_file_end,
        "pageup" => page_up,
        "pagedown" => page_down,
        "home" => goto_line_start,
        "C-a" => goto_line_start,
        "end" => goto_line_end_newline,
        "C-e" => goto_line_end_newline,

        "C-k" => kill_to_line_end,
        "C-u" => kill_to_line_start,

        "C-x" => completion,
        "C-r" => insert_register,
    });
    hashmap!(
        Mode::Normal => Keymap::new(normal),
        Mode::Select => Keymap::new(select),
        Mode::Insert => Keymap::new(insert),
    )
}```

**Comment by the-mikedavis** [comment]
I see

```
"" => shell_insert_output
```

which I expect is the invalid mapping. The default key for `shell_insert_output` is `!`.

**Comment by IsotoxalDev** [comment]
Oh!
