### ISSUE TITLE
Panic on searching inside selection when search term not visible

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#261]
### Reproduction steps
1. Open a blank buffer and enter this line:

```
This is a very very very long sentence with multiple letters and spaces and words.
```

2. Resize the terminal so that the last part of the sentence is not visible
3. Ways to panic:
    - Select the line and search for `This` and hit Escape: `XsThis` and `Esc`
    - Go to the end, select till the beginning and search for `words` (will panic before `Esc` or `Enter`): `glvghswords`
4. Panic:
```
thread 'main' panicked at 'Trying to access position outside the buffer:
    x=89, y=0, area=Rect { x: 0, y: 0, width: 72, height: 39 }',
    helix-tui/src/buffer.rs:217:9
```

### Environment

- Platform: Linux
- Helix version: `v0.2.0-13-g9701a19`

**Comment by pickfire** [comment]
On latest master d415a666feab2c5c7a5dc190a9bded7382c2e0e8, I can't reproduce the first one, maybe that was fixed?

Steps to reproduce

1. Insert
`This is a very very very long sentence with multiple letters and spaces and words.`
2. Select line till the end from beginning and select word, `xalt-;swords`

```
thread 'main' panicked at 'Trying to access position outside the buffer: x=87, y=0, area=Rect { x: 0, y: 0, width: 80, height: 25 }', helix-tui/src/buffer.rs:217:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: helix_tui::buffer::Buffer::index_of
             at ./helix-tui/src/buffer.rs:217:9
   3: helix_tui::buffer::Buffer::get_mut
             at ./helix-tui/src/buffer.rs:184:17
   4: helix_tui::buffer::Buffer::set_style
             at ./helix-tui/src/buffer.rs:358:17
   5: helix_term::ui::editor::EditorView::render_buffer
             at ./helix-term/src/ui/editor.rs:322:21
   6: helix_term::ui::editor::EditorView::render_view
             at ./helix-term/src/ui/editor.rs:72:9
   7: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
             at ./helix-term/src/ui/editor.rs:716:13
   8: helix_term::compositor::Compositor::render
             at ./helix-term/src/compositor.rs:137:13
   9: helix_term::application::Application::render
             at ./helix-term/src/application.rs:92:9
  10: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:151:13
  11: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:109:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:331:9
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: hx::main::{{closure}}
             at ./helix-term/src/main.rs:96:5
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  17: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/park/thread.rs:263:54
  18: tokio::coop::with_budget::{{closure}}
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:106:9
  19: std::thread::local::LocalKey<T>::try_with
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  20: std::thread::local::LocalKey<T>::with
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  21: tokio::coop::with_budget
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:99:5
  22: tokio::coop::budget
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:76:5
  23: tokio::park::thread::CachedParkThread::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/park/thread.rs:263:31
  24: tokio::runtime::enter::Enter::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/enter.rs:151:13
  25: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/thread_pool/mod.rs:71:9
  26: tokio::runtime::Runtime::block_on
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/mod.rs:452:43
  27: hx::main
             at ./helix-term/src/main.rs:98:5
  28: core::ops::function::FnOnce::call_once
             at /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by sudormrfbin** [comment]
> On latest master d415a66, I can't reproduce the first one, maybe that was fixed?

It seems to be fixed in master 👍🏾
