### ISSUE TITLE
browse to definition of console.log panics

### ISSUE THREAD

**Issue by smason** [helix-editor/helix#2737]
### Summary

just started using the javascript language server and had it panic unexpectedly on me, 

### Reproduction Steps

I installed the language server, created a dummy file and started helix via

```shell
npm i -g typescript-language-server typescript
cat > foo.js << EOF
console.log()
EOF
hx foo.js
```

then I ran `hx foo.js`, put the cursor over `log` and hit `gd` to browse to definition

### Helix log

<details><summary>backtrace</summary>

```
thread 'main' panicked at 'Could not parse queries for language "typescript". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 7, column: 1, offset: 159, message: "jsx_opening_element", kind: NodeType }', helix-core/src/syntax.rs:385:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e0944922007e1bb4fe59809293acf4364410cccc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e0944922007e1bb4fe59809293acf4364410cccc/library/core/src/panicking.rs:142:14
   2: helix_core::syntax::LanguageConfiguration::initialize_highlight
   3: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   4: once_cell::imp::initialize_or_wait
   5: once_cell::imp::OnceCell<T>::initialize
   6: helix_view::document::Document::set_language
   7: helix_view::document::Document::open
   8: helix_view::editor::Editor::open
   9: helix_term::commands::lsp::jump_to_location
  10: helix_term::commands::lsp::goto_impl
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: helix_term::job::Jobs::handle_callback
  13: helix_term::application::Application::event_loop::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: std::thread::local::LocalKey<T>::with
  16: tokio::park::thread::CachedParkThread::block_on
  17: tokio::runtime::thread_pool::ThreadPool::block_on
  18: tokio::runtime::Runtime::block_on
  19: hx::main
```

</details>

<details><summary>helix log</summary>

```
2022-06-10T12:12:15.616 helix_loader [DEBUG] Located configuration folders: []
2022-06-10T12:12:15.717 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-06-10T12:12:15.717 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-06-10T12:12:15.717 mio::poll [TRACE] registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
2022-06-10T12:12:15.717 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false}},"window":{"workDoneProgress":true},"workspace":{"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"workspaceFolders":true}},"processId":52275,"rootUri":null,"workspaceFolders":[]},"id":0}
2022-06-10T12:12:15.717 mio::poll [TRACE] registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
2022-06-10T12:12:15.717 mio::poll [TRACE] registering event source with poller: token=Token(5), interests=READABLE | WRITABLE
2022-06-10T12:12:15.718 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-06-10T12:12:15.718 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2022-06-10T12:12:15.921 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"[lspserver] Using Typescript version (bundled) 4.7.3 from path \"/home/smason/.local/lib/node_modules/typescript/lib/tsserver.js\""}}
2022-06-10T12:12:15.921 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "[lspserver] Using Typescript version (bundled) 4.7.3 from path \"/home/smason/.local/lib/node_modules/typescript/lib/tsserver.js\"" }
2022-06-10T12:12:16.143 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","\"","'","/","@","<"],"resolveProvider":true},"codeActionProvider":{"codeActionKinds":["source.fixAll.ts","source.removeUnused.ts","source.addMissingImports.ts","source.organizeImports.ts"]},"definitionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.organizeImports","_typescript.applyRenameFile"]},"hoverProvider":true,"renameProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"workspaceSymbolProvider":true,"implementationProvider":true,"typeDefinitionProvider":true,"foldingRangeProvider":true,"semanticTokensProvider":{"documentSelector":null,"legend":{"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","member"],"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"]},"full":true,"range":true},"callsProvider":true}}}
2022-06-10T12:12:16.143 helix_lsp::transport [INFO] <- {"capabilities":{"callsProvider":true,"codeActionProvider":{"codeActionKinds":["source.fixAll.ts","source.removeUnused.ts","source.addMissingImports.ts","source.organizeImports.ts"]},"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","\"","'","/","@","<"]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.organizeImports","_typescript.applyRenameFile"]},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"referencesProvider":true,"renameProvider":true,"semanticTokensProvider":{"documentSelector":null,"full":true,"legend":{"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"],"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","member"]},"range":true},"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"textDocumentSync":2,"typeDefinitionProvider":true,"workspaceSymbolProvider":true}}
2022-06-10T12:12:16.143 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2022-06-10T12:12:16.144 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"javascript","text":"console.log()\n","uri":"file:///home/smason/foo.js","version":0}}}
2022-06-10T12:12:16.714 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/smason/foo.js","diagnostics":[]}}
2022-06-10T12:12:17.173 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":9,"line":0},"textDocument":{"uri":"file:///home/smason/foo.js"}},"id":1}
2022-06-10T12:12:17.231 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":1,"result":[{"uri":"file:///home/smason/.local/lib/node_modules/typescript/lib/lib.dom.d.ts","range":{"start":{"line":17166,"character":4},"end":{"line":17166,"character":7}}}]}
2022-06-10T12:12:17.231 helix_lsp::transport [INFO] <- [{"range":{"end":{"character":7,"line":17166},"start":{"character":4,"line":17166}},"uri":"file:///home/smason/.local/lib/node_modules/typescript/lib/lib.dom.d.ts"}]
2022-06-10T12:12:17.238 mio::poll [TRACE] deregistering event source from poller
2022-06-10T12:12:17.238 mio::poll [TRACE] deregistering event source from poller
2022-06-10T12:12:17.239 mio::poll [TRACE] deregistering event source from poller
2022-06-10T12:12:17.239 mio::poll [TRACE] deregistering event source from poller
2022-06-10T12:12:17.239 mio::poll [TRACE] deregistering event source from poller
2022-06-10T12:12:17.239 mio::poll [TRACE] deregistering event source from poller
```

</details>

### Platform

linux

### Terminal Emulator

foot

### Helix Version

just updated to current master, i.e. helix 22.05 (f37ffaa3)

**Comment by smason** [comment]
forgot to note that my grammars are all coming up as "up to date" and "already built"

**Comment by smason** [comment]
oops, sorry, I broke my `runtime` dir

to anyone else seeing this, make sure that your runtime dir, i.e. `~/.config/helix/runtime` is up to date.  for me that meant recreating it, as a symlink, into the `runtime` directory of the code I'd just pulled
