### ISSUE TITLE
Hi, I have some issues trying to compile from source on aarch64 GNU/Linux Debian GNU/Linux 9.13 with git --version 2.11.0,

### ISSUE THREAD

**Issue by corvinux** [helix-editor/helix#2756]
Hi, I have some issues trying to compile from source on aarch64 GNU/Linux Debian GNU/Linux 9.13 with git --version 2.11.0,
My branch is up-to-date with 'origin/master'
--- stderr
  thread 'main' panicked at 'Failed to fetch tree-sitter grammars: Failed to fetch some grammar(s)

  Caused by:
      Git command failed.
      Stdout: 
      Stderr: error: no such remote ref bc26a6a949f2e0d98b7bfc437d459b250900a165
      ', helix-term/build.rs:21:26
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once

_Originally posted by @corvinux in https://github.com/helix-editor/helix/issues/2398#issuecomment-1153373555_

**Comment by the-mikedavis** [comment]
This looks the same as #2398: git 2.11.0 seems to be incompatible with source-hut's server-side git version for fetching at exact revisions.

You can update your git version or add a `~/.config/helix/languages.toml` to disable fetching just that grammar:

```toml
# ~/.config/helix/languages.toml
use-grammars = { except = [ "hare" ] }
```
