### ISSUE TITLE
0.6.0: Typing `where A: Iterator<Item =` causes a byte-vs-char index panic.

### ISSUE THREAD

**Issue by nathan-at-least** [helix-editor/helix#3143]
### Summary

I'm editing files in a rust crate and I started typing `where A: Iterator<`, and `hx` died with this panic:

```
thread 'main' panicked at 'byte index 23 is not a char boundary; it is inside '…' (bytes 22..25) of `trait Iterator<Item = …>`', library/core/src/str/mod.rs:127:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I re-opened hx and starting typing the same thing and it occurred again. I then created a new crate from scratch attempting to write this:

```
fn blah<T>(it: T)
where
    T: Iterator<Item = ()>,
{
    todo!()
}
```

-and it indeed panicked again, so this is very reproducible.

ps: It's my first day using `hx` coming from `vim` and I love it!

### Reproduction Steps

 

I tried this:

1. `hx`
2. <space> f - file picker
3. Select a rust file
4. Navigate to where I want to write a new method
5. Enter insert mode with `o` (the new method is one line below the `impl` statement.
6. As I'm entering text in insert mode, I type `where A: Iterator<`
7. It panics when I type the `<`

I expected this to happen:

Typing completes, and maybe helpful dialogs pop up telling me about `Iterator`.

Instead, this happened:

A panic. The error message suggests to me that there's some kind of display string which uses the single unicode ellipses `…`, but something in `hx` is referring to a byte index, rather than a char index.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "Panic context:\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "> \n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "version: 0.0.0 (84a6fac37 2022-07-21)\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "request: textDocument/completion CompletionParams {\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "    text_document_position: TextDocumentPositionParams {\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "        text_document: TextDocumentIdentifier {\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "            uri: Url {\n"
2022-07-21T21:59:13.601 helix_lsp::transport [ERROR] err <- "                scheme: \"file\",\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                cannot_be_a_base: false,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                username: \"\",\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                password: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                host: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                port: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                path: \"/tmp/tempdir-shell.6ZrVivZmO7sS/foo/src/main.rs\",\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                query: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "                fragment: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "            },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "        },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "        position: Position {\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "            line: 0,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "            character: 10,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "        },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    work_done_progress_params: WorkDoneProgressParams {\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "        work_done_token: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    partial_result_params: PartialResultParams {\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "        partial_result_token: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    },\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "    context: None,\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "}\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "thread 'Worker' panicked at 'Bad range: node range 0..9, range 10..10', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.5/src/cursor.rs:786:13\n"
2022-07-21T21:59:13.602 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   0: rust_begin_unwind\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   1: core::panicking::panic_fmt\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   2: rowan::cursor::SyntaxNode::covering_element\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   3: syntax::parsing::reparsing::incremental_reparse\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   4: syntax::Parse<syntax::ast::generated::nodes::SourceFile>::reparse\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   5: ide_completion::context::CompletionContext::new\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   6: ide_completion::completions\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   7: std::panicking::try\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   8: ide::Analysis::completions\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "   9: rust_analyzer::handlers::handle_completion\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "  10: std::panicking::try\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "  11: <F as threadpool::FnBox>::call_box\n"
2022-07-21T21:59:13.679 helix_lsp::transport [ERROR] err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
2022-07-21T21:59:13.680 helix_lsp::transport [ERROR] <- InternalError: request handler panicked: Bad range: node range 0..9, range 10..10
```

</details>

### Platform

Linux (crostini)

### Terminal Emulator

crostini terminal, hx running inside tmux.

### Helix Version

22.05-261-g8b2a1415

**Comment by archseer** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3120
