### ISSUE TITLE
Issues with `pyls`

### ISSUE THREAD

**Issue by tuxiqae** [helix-editor/helix#33]
Seems like Helix panics when it tries to open Python files specifically, I tried both large and small files, it panicked on both, both when the file is given using the CLI and both when selected through the `:open <file.py>` option.
I was able to open `TOML, Rust, C, C++, txt, XML, CSV, JSON` perfectly well.

```
❯ hx ~/path/to/file.py
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', helix-lsp/src/transport.rs:103:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-lsp/src/client.rs:156:18
```

Reproducible in both `helix-git` and `helix-bin` AUR packages.
(Seems like it also panics when I try to extract the version on the `helix-git` package)
```
❯ hx --version
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', helix-term/src/main.rs:117:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Active Rust versions:
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.54.0-nightly (657bc0188 2021-05-31)
```

**Comment by archseer** [comment]
It looks like you have `pyls` installed and it's failing to communicate with it (can't find the `Content-Length` header).

Do you have a sample project I could test on?

**Comment by tuxiqae** [comment]
You may try testing on my WIP project https://github.com/tuxiqae/Friecipe

Or any other Python project TBH

**Comment by tuxiqae** [comment]
P.S. Seems like `pyls` really isn't working

```
 ❯ pyls
Traceback (most recent call last):
  File "/home/user/.local/bin/pyls", line 5, in <module>
    from pyls.__main__ import main
ModuleNotFoundError: No module named 'pyls'
```

**Comment by IceDragon200** [comment]
So this is a language server integration issue, I was able to navigate your project without issue, but I don't have pyls at all, so that may have helped

**Comment by archseer** [comment]
Reopening because I'd still like to solve the underlying cause, but at least it shouldn't panic anymore

**Comment by malte-v** [comment]
I don't think this is specific to `pyls`. I frequently get random crashes with `rust-analyzer`, too.

**Comment by malte-v** [comment]
Some debug logging reveals that language servers may sometimes send ill-formed messages:
```
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] header: Content-Length: 111
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] header: 
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":142,"method":"window/workDoneProgress/create","params":{"token":"rustAnalyzer/Indexing"}}
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] header: Content-Length: 141
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] header: 
2021-06-18T19:11:50.957 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$/progress","params":{"token":"rustAnalyzer/Indexing","value":{"kind":"begin","title":"Indexing","percentage":0}}}
2021-06-18T19:11:50.961 helix_lsp::transport [INFO] header: Content-Length: 157
2021-06-18T19:11:50.961 helix_lsp::transport [INFO] header: 
2021-06-18T19:11:50.961 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":142}
2021-06-18T19:11:50.961 helix_lsp::transport [INFO] header: {"jsonrpc":"2.0","method":"$/progress","params":{"token":"rustAnalyzer/Indexing","value":{"kind":"report","message":"40/523 (tokio_macros)","percentage":7}}}Content-Length: 156
2021-06-18T19:11:50.961 helix_lsp::transport [INFO] header: 
<crash happened here>
```
Notice that the last message does not look right at all.

**Comment by malte-v** [comment]
#306 should fix this issue.
