### ISSUE TITLE
Crash on splitting selection with `^` (start of line)

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#346]
### Reproduction steps

Select a line with `x`, hit `s` to split and type `^`

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'attempt to subtract with overflow', helix-core/src/selection.rs:355:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   3: helix_core::selection::select_on_matches
             at ./helix-core/src/selection.rs:355:43
   4: helix_term::commands::select_regex::{{closure}}
             at ./helix-term/src/commands.rs:779:34
   5: helix_term::ui::regex_prompt::{{closure}}
             at ./helix-term/src/ui/mod.rs:65:29
   6: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1528:9
   7: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
             at ./helix-term/src/ui/prompt.rs:389:17
   8: helix_term::compositor::Compositor::handle_event
             at ./helix-term/src/compositor.rs:114:19
   9: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:200:32
  10: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:159:21
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  12: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:475:9
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  14: hx::main::{{closure}}
             at ./helix-term/src/main.rs:98:5
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-lin
ux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  16: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:263:54
  17: tokio::coop::with_budget::{{closure}}
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  18: std::thread::local::LocalKey<T>::try_with
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  19: std::thread::local::LocalKey<T>::with
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  20: tokio::coop::with_budget
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  21: tokio::coop::budget
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  22: tokio::park::thread::CachedParkThread::block_on
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:263:31
  23: tokio::runtime::enter::Enter::block_on
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/enter.rs:151:13
  24: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/mod.rs:71:9
  25: tokio::runtime::Runtime::block_on
             at /home/gokul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:452:43
  26: hx::main
             at ./helix-term/src/main.rs:100:5
  27: core::ops::function::FnOnce::call_once
             at /home/gokul/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

</details>

https://github.com/helix-editor/helix/blob/866b32b5d7f997cf33cb9ec5c155348a58fc267b/helix-core/src/selection.rs#L353-L355

`end - 1` values to 0 in this case hence the error.

**Comment by archseer** [comment]
I had to do a similar thing on `search`, if `mat.start() == mat.end()` we need to skip it because it's an empty range (it's end exclusive).
