### ISSUE TITLE
Panicked at unreachable code in RopeGraphemes iterator

### ISSUE THREAD

**Issue by CBenoit** [helix-editor/helix#360]
### Reproduction steps

I tried to open a mp3 file with helix (just because we can open non UTF-8 file now).
One specific mp3 file caused the panic.

Here is a zip containing the file: [pronunciation_ja_saibashi.mp3.zip](https://github.com/helix-editor/helix/files/6704810/pronunciation_ja_saibashi.mp3.zip)

### Environment

- Helix version: v21.1.3-22-g21937662f

<details><summary>Trace</summary>

```
thread 'main' panicked at 'internal error: entered unreachable code', helix-core/src/graphemes.rs:210:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: <helix_core::graphemes::RopeGraphemes as core::iter::traits::iterator::Iterator>::next
   4: helix_term::ui::editor::EditorView::render_buffer
   5: helix_term::ui::editor::EditorView::render_view
   6: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
   7: helix_term::compositor::Compositor::render
   8: helix_term::application::Application::render
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::runtime::enter::Enter::block_on
  11: tokio::runtime::Runtime::block_on
  12: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by kirawi** [comment]
Yeah I noticed it too, it only happens on binary file types so I just left it be so the PR could get merged. I want to get it fixed though.
