### ISSUE TITLE
Svelte language server throws errors and code highlighting is missing.

### ISSUE THREAD

**Issue by sommerper** [helix-editor/helix#3803]
Hi!
I'm trying out Helix for the first time and I'm running into some problems with a Svelte project. It seems that I get typescript code completion but no code highlighting.

I don't know if it's a bug or if I just don't know what I'm doing.
I've installed the language servers:
```
npm install -g typescript typescript-language-server
npm install -g svelte-language-server
```
This is what it looks like:
![image](https://user-images.githubusercontent.com/1512048/189535849-fbdd2946-bb07-44e4-b11a-87eb7c1b5338.png)

And here is the helix.log
```
2022-09-10T12:20:05.676 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
2022-09-10T15:56:42.925 helix_lsp::transport [ERROR] err <- "Initialize language server at  file:///home/xxx/development/web/sveltekit-test\n"
2022-09-10T15:56:42.954 helix_lsp::transport [ERROR] err <- "Initialize new ts service at  /home/xxx/development/web/sveltekit-test/tsconfig.json\n"
2022-09-10T15:56:42.968 helix_lsp::transport [ERROR] err <- "Trying to load configs for /home/xxx/development/web/sveltekit-test\n"
2022-09-10T15:56:43.004 helix_lsp::transport [ERROR] err <- "Loaded config at  /home/xxx/development/web/sveltekit-test/svelte.config.js\n"
2022-09-10T15:56:43.026 helix_lsp::transport [ERROR] err <- "SnapshotManager File Statistics:\n"
2022-09-10T15:56:43.026 helix_lsp::transport [ERROR] err <- "Project files: 15\n"
2022-09-10T15:56:43.026 helix_lsp::transport [ERROR] err <- "Svelte files: 7\n"
2022-09-10T15:56:43.026 helix_lsp::transport [ERROR] err <- "From node_modules: 0\n"
2022-09-10T15:56:43.026 helix_lsp::transport [ERROR] err <- "Total: 15\n"
2022-09-10T15:56:43.754 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:56:45.313 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:56:45.575 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:56:45.790 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:09.668 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:09.748 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:16.421 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:16.455 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m10\u{1b}[0m:\u{1b}[93m7\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1003: \u{1b}[0mIdentifier expected.\n"
2022-09-10T15:57:16.455 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:16.455 helix_lsp::transport [ERROR] err <- "\u{1b}[7m10\u{1b}[0m  data.\n"
2022-09-10T15:57:16.455 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m      \u{1b}[0m\n"
2022-09-10T15:57:16.455 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:16.461 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m14\u{1b}[0m:\u{1b}[93m7\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1003: \u{1b}[0mIdentifier expected.\n"
2022-09-10T15:57:16.461 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:16.461 helix_lsp::transport [ERROR] err <- "\u{1b}[7m14\u{1b}[0m  data.\n"
2022-09-10T15:57:16.461 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m      \u{1b}[0m\n"
2022-09-10T15:57:16.461 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:16.488 helix_lsp::transport [ERROR] err <- "Preprocessing failed\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "Error: [svelte-preprocess] Encountered type error\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at throwError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at throwTypescriptError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at transpileTs (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:178:47)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at mixedImportsTranspiler (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:233:60)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at transformer (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:303:11)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at transform (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at async /home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:118:29\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at async Object.script (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:148:33)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at async wrappedPreprocessor.script (/home/xxx/.npm-global/lib/node_modules/svelte-language-server/dist/src/plugins/svelte/SvelteDocument.js:249:28)\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "    at async process_single_tag (/home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler.js:32109:28) {\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "  __source: 'Script'\n"
2022-09-10T15:57:16.492 helix_lsp::transport [ERROR] err <- "}\n"
2022-09-10T15:57:19.553 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:19.614 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:22.376 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:22.437 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:31.576 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:31.623 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:32.759 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:32.816 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:34.358 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:34.386 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m12\u{1b}[0m:\u{1b}[93m13\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1005: \u{1b}[0m';' expected.\n"
2022-09-10T15:57:34.386 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:34.386 helix_lsp::transport [ERROR] err <- "\u{1b}[7m12\u{1b}[0m   interface TestType {\n"
2022-09-10T15:57:34.386 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m            ~~~~~~~~\u{1b}[0m\n"
2022-09-10T15:57:34.386 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:34.393 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m16\u{1b}[0m:\u{1b}[93m13\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1005: \u{1b}[0m';' expected.\n"
2022-09-10T15:57:34.394 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:34.394 helix_lsp::transport [ERROR] err <- "\u{1b}[7m16\u{1b}[0m   interface TestType {\n"
2022-09-10T15:57:34.394 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m            ~~~~~~~~\u{1b}[0m\n"
2022-09-10T15:57:34.394 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:34.423 helix_lsp::transport [ERROR] err <- "Preprocessing failed\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "Error: [svelte-preprocess] Encountered type error\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at throwError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at throwTypescriptError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at transpileTs (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:178:47)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at mixedImportsTranspiler (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:233:60)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at transformer (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:303:11)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at transform (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at async /home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:118:29\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at async Object.script (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:148:33)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at async wrappedPreprocessor.script (/home/xxx/.npm-global/lib/node_modules/svelte-language-server/dist/src/plugins/svelte/SvelteDocument.js:249:28)\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "    at async process_single_tag (/home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler.js:32109:28) {\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "  __source: 'Script'\n"
2022-09-10T15:57:34.424 helix_lsp::transport [ERROR] err <- "}\n"
2022-09-10T15:57:35.346 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:35.366 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m10\u{1b}[0m:\u{1b}[93m7\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1003: \u{1b}[0mIdentifier expected.\n"
2022-09-10T15:57:35.366 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:35.366 helix_lsp::transport [ERROR] err <- "\u{1b}[7m10\u{1b}[0m  load.\n"
2022-09-10T15:57:35.366 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m      \u{1b}[0m\n"
2022-09-10T15:57:35.366 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:35.373 helix_lsp::transport [ERROR] err <- "\u{1b}[96msrc/routes/test.svelte.injected.ts\u{1b}[0m:\u{1b}[93m14\u{1b}[0m:\u{1b}[93m7\u{1b}[0m - \u{1b}[91merror\u{1b}[0m\u{1b}[90m TS1003: \u{1b}[0mIdentifier expected.\n"
2022-09-10T15:57:35.373 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:35.373 helix_lsp::transport [ERROR] err <- "\u{1b}[7m14\u{1b}[0m  load.\n"
2022-09-10T15:57:35.373 helix_lsp::transport [ERROR] err <- "\u{1b}[7m  \u{1b}[0m \u{1b}[91m      \u{1b}[0m\n"
2022-09-10T15:57:35.373 helix_lsp::transport [ERROR] err <- "\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "Preprocessing failed\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "Error: [svelte-preprocess] Encountered type error\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at throwError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at throwTypescriptError (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at transpileTs (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:178:47)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at mixedImportsTranspiler (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:233:60)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at transformer (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/transformers/typescript.js:303:11)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at transform (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at async /home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:118:29\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at async Object.script (/home/xxx/development/web/sveltekit-test/node_modules/svelte-preprocess/dist/autoProcess.js:148:33)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at async wrappedPreprocessor.script (/home/xxx/.npm-global/lib/node_modules/svelte-language-server/dist/src/plugins/svelte/SvelteDocument.js:249:28)\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "    at async process_single_tag (/home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler.js:32109:28) {\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "  __source: 'Script'\n"
2022-09-10T15:57:35.393 helix_lsp::transport [ERROR] err <- "}\n"
2022-09-10T15:57:52.631 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T15:57:52.635 helix_lsp::transport [ERROR] err <- "SnapshotManager File Statistics:\n"
2022-09-10T15:57:52.635 helix_lsp::transport [ERROR] err <- "Project files: 15\n"
2022-09-10T15:57:52.635 helix_lsp::transport [ERROR] err <- "Svelte files: 7\n"
2022-09-10T15:57:52.635 helix_lsp::transport [ERROR] err <- "From node_modules: 200\n"
2022-09-10T15:57:52.635 helix_lsp::transport [ERROR] err <- "Total: 216\n"
2022-09-10T15:57:52.685 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T16:02:09.432 helix_view::clipboard [INFO] Using xclip to interact with the system and selection (primary) clipboard
2022-09-10T16:02:09.433 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false},"workspaceFolders":true}},"processId":3458344,"rootPath":"/home/xxx/development/web/sveltekit-test","rootUri":"file:///home/xxx/development/web/sveltekit-test","workspaceFolders":[{"name":"sveltekit-test","uri":"file:///home/xxx/development/web/sveltekit-test"}]},"id":0}
2022-09-10T16:02:10.002 helix_lsp::transport [ERROR] err <- "Initialize language server at  file:///home/xxx/development/web/sveltekit-test\n"
2022-09-10T16:02:10.014 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{"includeText":false}},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","\"","'","`","/","@","<",">","*","#","$","+","^","(","[","@","-",":","|"]},"documentFormattingProvider":true,"colorProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","source.organizeImports","source.sortImports","refactor"]},"executeCommandProvider":{"commands":["function_scope_0","function_scope_1","function_scope_2","function_scope_3","constant_scope_0","constant_scope_1","constant_scope_2","constant_scope_3","extract_to_svelte_component","Infer function return type"]},"renameProvider":true,"referencesProvider":true,"selectionRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"],"retriggerCharacters":[")"]},"semanticTokensProvider":{"legend":{"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"],"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","method","event"]},"range":true,"full":true},"linkedEditingRangeProvider":true,"implementationProvider":true,"typeDefinitionProvider":true}}}
2022-09-10T16:02:10.014 helix_lsp::transport [INFO] <- {"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","source.organizeImports","source.sortImports","refactor"]},"colorProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","\"","'","`","/","@","<",">","*","#","$","+","^","(","[","@","-",":","|"]},"definitionProvider":true,"documentFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["function_scope_0","function_scope_1","function_scope_2","function_scope_3","constant_scope_0","constant_scope_1","constant_scope_2","constant_scope_3","extract_to_svelte_component","Infer function return type"]},"hoverProvider":true,"implementationProvider":true,"linkedEditingRangeProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":true,"legend":{"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"],"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","method","event"]},"range":true},"signatureHelpProvider":{"retriggerCharacters":[")"],"triggerCharacters":["(",",","<"]},"textDocumentSync":{"change":2,"openClose":true,"save":{"includeText":false}},"typeDefinitionProvider":true}}
2022-09-10T16:02:10.015 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2022-09-10T16:02:10.015 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"svelte","text":"<script context=\"module\">\n\timport { browser, dev } from '$app/env';\n\n\t// we don't need any JS on this page, though we'll load\n\t// it in dev so that we get hot module replacement...\n\texport const hydrate = dev;\n\n\t// ...but if the client-side router is already loaded\n\t// (i.e. we came here from elsewhere in the app), use it\n\texport const router = browser;\n\n\t// since there's no dynamic data here, we can prerender\n\t// it so that it gets served as a static asset in prod\n\texport const prerender = true;\n</script>\n\n<svelte:head>\n\t<title>About</title>\n</svelte:head>\n\n<div class=\"content\">\n\t<h1>About this app</h1>\n\n\t<p>\n\t\tThis is a <a href=\"https://kit.svelte.dev\">SvelteKit</a> app. You can make your own by typing the\n\t\tfollowing into your command line and following the prompts:\n\t</p>\n\n\t<!-- TODO lose the @next! -->\n\t<pre>npm init svelte@next</pre>\n\n\t<p>\n\t\tThe page you're looking at is purely static HTML, with no client-side interactivity needed.\n\t\tBecause of that, we don't need to load any JavaScript. Try viewing the page's source, or opening\n\t\tthe devtools network panel and reloading.\n\t</p>\n\n\t<p>\n\t\tThe <a href=\"/todos\">TODOs</a> page illustrates SvelteKit's data loading and form handling. Try using\n\t\tit with JavaScript disabled!\n\t</p>\n</div>\n\n<style>\n\t.content {\n\t\twidth: 100%;\n\t\tmax-width: var(--column-width);\n\t\tmargin: var(--column-margin-top) auto 0 auto;\n\t}\n</style>\n","uri":"file:///home/xxx/development/web/sveltekit-test/src/routes/about.svelte","version":0}}}
2022-09-10T16:02:10.037 helix_lsp::transport [ERROR] err <- "Initialize new ts service at  /home/xxx/development/web/sveltekit-test/tsconfig.json\n"
2022-09-10T16:02:10.052 helix_lsp::transport [ERROR] err <- "Trying to load configs for /home/xxx/development/web/sveltekit-test\n"
2022-09-10T16:02:10.080 helix_lsp::transport [ERROR] err <- "Loaded config at  /home/xxx/development/web/sveltekit-test/svelte.config.js\n"
2022-09-10T16:02:10.098 helix_lsp::transport [ERROR] err <- "SnapshotManager File Statistics:\n"
2022-09-10T16:02:10.098 helix_lsp::transport [ERROR] err <- "Project files: 15\n"
2022-09-10T16:02:10.098 helix_lsp::transport [ERROR] err <- "Svelte files: 7\n"
2022-09-10T16:02:10.098 helix_lsp::transport [ERROR] err <- "From node_modules: 0\n"
2022-09-10T16:02:10.098 helix_lsp::transport [ERROR] err <- "Total: 15\n"
2022-09-10T16:02:10.828 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T16:02:12.143 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T16:02:12.157 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/xxx/development/web/sveltekit-test/src/routes/about.svelte","diagnostics":[]}}
2022-09-10T16:02:12.369 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T16:02:12.845 helix_lsp::transport [ERROR] err <- "Using Svelte v3.46.4 from /home/xxx/development/web/sveltekit-test/node_modules/svelte/compiler\n"
2022-09-10T16:02:12.862 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/xxx/development/web/sveltekit-test/src/routes/todos/index.svelte","diagnostics":[]}}
2022-09-10T16:02:57.850 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"shutdown","params":null,"id":1}
2022-09-10T16:02:57.858 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":1,"result":null}
2022-09-10T16:02:57.858 helix_lsp::transport [INFO] <- null
2022-09-10T16:02:57.858 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"exit","params":null}

```

It looks like it's spawning errors but the messages don't really look like errors.

Am I doing something wrong?

**Comment by the-mikedavis** [comment]
Did you install helix from source? The runtime directory may need to be linked: https://github.com/helix-editor/helix/blob/03612174ee4cef23217b5adf415ced4a851b4a44/README.md?plain=1#L48-L55

Those errors are stderr from the language server so you may need to consult svelte LS's logs or documentation. It looks like the language server doesn't exit though so they may be benign.

**Comment by sommerper** [comment]
Yes, I installed from source but I must have messed up the symlink part because after doing that I get code highlighting!

Thanks a bunch!
