### ISSUE TITLE
panic while removing characters in a line with "special" chars

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#386]
When a line includes an "uncommon" character (I assume this happens with chars that are > 1 byte) helix panics if you move the cursor with the arrow keys and remove any other character up to that point on the same line (using <kbd>Backspace</kbd> or <kbd>Del</kbd>).

### Reproduction steps

1. in `INS` mode, type anything with uncommon characters - `x²` for example
2. *without leaving* `INS` mode, move the cursor one to the left with the arrow keys and hit backspace (removing `x`)
3. helix panics

<details><summary>stack trace</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationFailed', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tendril-0.4.2\src\tendril.rs:861:31
stack backtrace:
   0:     0x7ff60a99486e - <unknown>
   1:     0x7ff60a9b002c - <unknown>
   2:     0x7ff60a98f258 - <unknown>
   3:     0x7ff60a997522 - <unknown>
   4:     0x7ff60a997003 - <unknown>
   5:     0x7ff60a59f676 - <unknown>
   6:     0x7ff60a997c05 - <unknown>
   7:     0x7ff60a997771 - <unknown>
   8:     0x7ff60a9951bf - <unknown>
   9:     0x7ff60a9976c9 - <unknown>
  10:     0x7ff60aae0090 - tree_sitter_typescript
  11:     0x7ff60aae01a3 - tree_sitter_typescript
  12:     0x7ff60a89a621 - <unknown>
  13:     0x7ff60a721004 - <unknown>
  14:     0x7ff60a731713 - <unknown>
  15:     0x7ff60a607800 - <unknown>
  16:     0x7ff60a60d125 - <unknown>
  17:     0x7ff60a62e14b - <unknown>
  18:     0x7ff60a5a629c - <unknown>
  19:     0x7ff60a5ac2f3 - <unknown>
  20:     0x7ff60a58c28a - <unknown>
  21:     0x7ff60a589800 - <unknown>
  22:     0x7ff60a5835c6 - <unknown>
  23:     0x7ff60a5835ea - <unknown>
  24:     0x7ff60a997d67 - <unknown>
  25:     0x7ff60a5899c7 - <unknown>
  26:     0x7ff60aac45bc - tree_sitter_typescript
  27:     0x7ffd327a7034 - BaseThreadInitThunk
  28:     0x7ffd32f62651 - RtlUserThreadStart
```

</details>

### Environment

- Platform: Win10
- Helix version: 0.3.0

**Comment by archseer** [comment]
Hmm interesting but I'm unable to reproduce: https://asciinema.org/a/edgaxRi4e6rvEOqHkg5IIZgVG

Can you compile Helix from git, reproduce it and give me the full stack trace? We strip debug info on releases but I think it might be worth keeping it to debug cases like these.

For reference, we do use graphemes to determine movement:

https://github.com/helix-editor/helix/blob/82fc28a0ce2cb2b86968335f32e95aaff3e2cba4/helix-term/src/commands.rs#L2570

**Comment by CptPotato** [comment]
Alright, here's a debug stack trace using `d4e1ec339e022ffd5073873ac0bc64e3c095d064`:

<details><summary>stack trace</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationFailed', C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tendril-0.4.2\src\tendril.rs:861:31
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\/library\core\src\panicking.rs:92
   2: core::result::unwrap_failed
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\/library\core\src\result.rs:1355
   3: enum$<core::result::Result<tuple<>, enum$<tendril::tendril::SubtendrilError>>, 0, 1, Err>::unwrap<tuple<>,enum$<tendril::tendril::SubtendrilError>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\result.rs:1037
   4: tendril::tendril::Tendril<tendril::fmt::UTF8, tendril::tendril::NonAtomic>::pop_front<tendril::fmt::UTF8,tendril::tendril::NonAtomic>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tendril-0.4.2\src\tendril.rs:861
   5: helix_core::transaction::ChangeSet::compose
             at C:\[...]\helix\helix-core\src\transaction.rs:198
   6: helix_view::document::{{impl}}::apply::{{closure}}
             at C:\[...]\helix\helix-view\src\document.rs:798
   7: helix_view::document::take_with::{{closure}}<helix_core::transaction::ChangeSet,closure-0>
             at C:\[...]\helix\helix-view\src\document.rs:319
   8: std::panic::{{impl}}::call_once<helix_core::transaction::ChangeSet,closure-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\panic.rs:347
   9: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,helix_core::transaction::ChangeSet>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\panicking.rs:401
  10: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  11: std::panicking::try<helix_core::transaction::ChangeSet,std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\panicking.rs:365
  12: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,helix_core::transaction::ChangeSet>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\panic.rs:434
  13: helix_view::document::take_with<helix_core::transaction::ChangeSet,closure-0>
             at C:\[...]\helix\helix-view\src\document.rs:319
  14: helix_view::document::Document::apply
             at C:\[...]\helix\helix-view\src\document.rs:797
  15: helix_term::commands::insert::delete_char_backward
             at .\src\commands.rs:2575
  16: helix_term::commands::Command::execute
             at .\src\commands.rs:143
  17: helix_term::ui::editor::EditorView::insert_mode
             at .\src\ui\editor.rs:543
  18: helix_term::ui::editor::{{impl}}::handle_event
             at .\src\ui\editor.rs:659
  19: helix_term::compositor::Compositor::handle_event
             at .\src\compositor.rs:115
  20: helix_term::application::Application::handle_terminal_events
             at .\src\application.rs:206
  21: helix_term::application::{{impl}}::event_loop::{{closure}}
             at .\src\application.rs:158
  22: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  23: helix_term::application::{{impl}}::run::{{closure}}
             at .\src\application.rs:481
  24: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  25: hx::main::{{closure}}
             at .\src\main.rs:97
  26: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  27: tokio::park::thread::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\park\thread.rs:263
  28: tokio::coop::with_budget::{{closure}}<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>,closure-0>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:106
  29: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\thread\local.rs:399
  30: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\thread\local.rs:375
  31: tokio::coop::with_budget
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:99
  32: tokio::coop::budget
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:76
  33: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\park\thread.rs:263
  34: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\enter.rs:151
  35: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\thread_pool\mod.rs:71
  36: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\mod.rs:452
  37: hx::main
             at .\src\main.rs:99
  38: core::ops::function::FnOnce::call_once<fn() -> enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>,tuple<>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\[...]\helix\target\debug\hx.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

</details>

The way you've reproduced it should have triggered the bug, I can reproduce it every time on my two Win10 systems. Another interesting thing is that this only happens when the line was changed without leaving `INS` mode.
i.e. if I do the same steps but go to `NOR` mode after step 1. and back to `INS` it doesn't panic.

---

Another panic I can consistently trigger is using <kbd>Del</kbd> at the end of a line, though this one might be unrelated to the above:

1. open hx
2. press <kbd>Del</kbd> <kbd>Return</kbd>

<details><summary>stack trace</summary>

```
thread 'main' panicked at 'Attempt to index past end of Rope: char index 0, Rope char length 0', C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\ropey-1.3.1\src\rope.rs:805:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\/library\std\src\panicking.rs:515
   1: std::panicking::begin_panic_fmt
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\/library\std\src\panicking.rs:457
   2: ropey::rope::Rope::char
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\ropey-1.3.1\src\rope.rs:805
   3: helix_term::commands::insert::insert_newline::{{closure}}
             at .\src\commands.rs:2514
   4: core::ops::function::impls::{{impl}}::call_once<tuple<helix_core::selection::Range*>,closure-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\ops\function.rs:280
   5: enum$<core::option::Option<helix_core::selection::Range*>, 1, 18446744073709551615, Some>::map<helix_core::selection::Range*,tuple<usize, usize, enum$<core::option::Option<tendril::tendril::Tendril<tendril::fmt::UTF8, tendril::tendril::NonAtomic>>, 1, 184
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\option.rs:489
   6: core::iter::adapters::map::{{impl}}::next<tuple<usize, usize, enum$<core::option::Option<tendril::tendril::Tendril<tendril::fmt::UTF8, tendril::tendril::NonAtomic>>, 1, 18446744073709551615, Some>>,core::slice::iter::Iter<helix_core::selection::Range>,clo
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\iter\adapters\map.rs:101
   7: helix_core::transaction::Transaction::change<core::iter::adapters::map::Map<core::slice::iter::Iter<helix_core::selection::Range>, closure-0>>
             at C:\[...]\helix\helix-core\src\transaction.rs:487
   8: helix_core::transaction::Transaction::change_by_selection<closure-0>
             at C:\[...]\helix\helix-core\src\transaction.rs:511
   9: helix_term::commands::insert::insert_newline
             at .\src\commands.rs:2506
  10: helix_term::commands::Command::execute
             at .\src\commands.rs:143
  11: helix_term::ui::editor::EditorView::insert_mode
             at .\src\ui\editor.rs:543
  12: helix_term::ui::editor::{{impl}}::handle_event
             at .\src\ui\editor.rs:659
  13: helix_term::compositor::Compositor::handle_event
             at .\src\compositor.rs:115
  14: helix_term::application::Application::handle_terminal_events
             at .\src\application.rs:206
  15: helix_term::application::{{impl}}::event_loop::{{closure}}
             at .\src\application.rs:158
  16: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  17: helix_term::application::{{impl}}::run::{{closure}}
             at .\src\application.rs:481
  18: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  19: hx::main::{{closure}}
             at .\src\main.rs:97
  20: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\future\mod.rs:80
  21: tokio::park::thread::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\park\thread.rs:263
  22: tokio::coop::with_budget::{{closure}}<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>,closure-0>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:106
  23: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\thread\local.rs:399
  24: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\std\src\thread\local.rs:375
  25: tokio::coop::with_budget
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:99
  26: tokio::coop::budget
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\coop.rs:76
  27: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\park\thread.rs:263
  28: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\enter.rs:151
  29: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\thread_pool\mod.rs:71
  30: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\[...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.7.1\src\runtime\mod.rs:452
  31: hx::main
             at .\src\main.rs:99
  32: core::ops::function::FnOnce::call_once<fn() -> enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>,tuple<>>
             at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by archseer** [comment]
For the first error, I can reproduce it now. I think I left the insert mode in the recording then re-entered it.

**Comment by archseer** [comment]
Pushed https://github.com/helix-editor/helix/commit/ca98210d2016d96d1c441932d7a67bbc6e5eccb7 and https://github.com/helix-editor/helix/commit/6214d707f3aac89938441171cf7cc0d96517bbe5, can you verify if the second bug is fixed?

**Comment by CptPotato** [comment]
Both panics are fixed for me, thanks.
