### ISSUE TITLE
Can not Move in INS mode after upgrade to 22.08.1

### ISSUE THREAD

**Issue by yellowred** [helix-editor/helix#3908]
### Summary

I used arrow keys to move in INS mode to edit text, but after upgrade to a new version from 22.05 (dad6d0f3) it does not work anymore. Arrow keys move cursor in NORMAL mode, but not in INSERT. Home and End keys do not work either. I use Helix on Ubuntu to edit Rust files with lang server enabled.

### Reproduction Steps

 
1. Start Helix `hx`.
2. `SPACE`, `f`, then select a file, Enter.
3. Use arrows to navigate to a code block.
4. `a`
5. Try to use arrows: not working.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-09-20T11:39:53.321 helix_lsp::transport [ERROR] err <- "thread '<unnamed>' panicked at 'Box<dyn Any>', /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5\n"
2022-09-20T11:39:53.321 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "   0: std::panicking::begin_panic\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:616:12\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "   1: proc_macro_error::abort_now\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "   2: proc_macro_error::diagnostic::Diagnostic::abort\n"
2022-09-20T11:39:53.329 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/diagnostic.rs:182:9\n"
2022-09-20T11:39:53.330 helix_lsp::transport [ERROR] err <- "   3: diesel_derives::as_expression::derive\n"
2022-09-20T11:39:53.330 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/as_expression.rs:11:9\n"
2022-09-20T11:39:53.330 helix_lsp::transport [ERROR] err <- "   4: diesel_derives::derive_as_expression::{{closure}}\n"
2022-09-20T11:39:53.330 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/lib.rs:157:5\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "   6: std::panicking::try::do_call\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "   7: __rust_try\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "   8: std::panicking::try\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "   9: std::panic::catch_unwind\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "  10: proc_macro_error::entry_point\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:432:18\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "  11: diesel_derives::derive_as_expression\n"
2022-09-20T11:39:53.331 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/lib.rs:147:1\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  12: core::ops::function::FnOnce::call_once\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  13: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:424:40\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  14: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:392:26\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  15: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:79:33\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  16: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:74:9\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  17: proc_macro::bridge::scoped_cell::ScopedCell<T>::set\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:79:9\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "  18: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}\n"
2022-09-20T11:39:53.332 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:340:35\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  19: std::thread::local::LocalKey<T>::try_with\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  20: std::thread::local::LocalKey<T>::with\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  21: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:340:9\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  22: proc_macro::bridge::client::run_client::{{closure}}\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:385:9\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  24: std::panicking::try::do_call\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  25: __rust_try\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  26: std::panicking::try\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  27: std::panic::catch_unwind\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  28: proc_macro::bridge::client::run_client\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:384:5\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "  29: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run\n"
2022-09-20T11:39:53.333 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:424:13\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "  30: proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::run_server\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "  31: proc_macro_srv::abis::abi_1_58::Abi::expand\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "  32: proc_macro_srv::abis::Abi::expand\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "  33: proc_macro_srv::dylib::Expander::expand\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "  34: proc_macro_srv::cli::run\n"
2022-09-20T11:39:53.336 helix_lsp::transport [ERROR] err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "thread '<unnamed>' panicked at 'Box<dyn Any>', /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   0: std::panicking::begin_panic\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:616:12\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   1: proc_macro_error::abort_now\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   2: proc_macro_error::diagnostic::Diagnostic::abort\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/diagnostic.rs:182:9\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   3: diesel_derives::as_expression::derive\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/as_expression.rs:11:9\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   4: diesel_derives::derive_as_expression::{{closure}}\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/lib.rs:157:5\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   6: std::panicking::try::do_call\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   7: __rust_try\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   8: std::panicking::try\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "   9: std::panic::catch_unwind\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "  10: proc_macro_error::entry_point\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:432:18\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "  11: diesel_derives::derive_as_expression\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /home/frankkk/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/lib.rs:147:1\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "  12: core::ops::function::FnOnce::call_once\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "  13: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:424:40\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "  14: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}\n"
2022-09-20T11:39:53.382 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:392:26\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  15: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:79:33\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  16: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:74:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  17: proc_macro::bridge::scoped_cell::ScopedCell<T>::set\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/scoped_cell.rs:79:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  18: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:340:35\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  19: std::thread::local::LocalKey<T>::try_with\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  20: std::thread::local::LocalKey<T>::with\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  21: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:340:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  22: proc_macro::bridge::client::run_client::{{closure}}\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:385:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  24: std::panicking::try::do_call\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  25: __rust_try\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  26: std::panicking::try\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  27: std::panic::catch_unwind\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  28: proc_macro::bridge::client::run_client\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:384:5\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  29: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:424:13\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  30: proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::run_server\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  31: proc_macro_srv::abis::abi_1_58::Abi::expand\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  32: proc_macro_srv::abis::Abi::expand\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  33: proc_macro_srv::dylib::Expander::expand\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "  34: proc_macro_srv::cli::run\n"
2022-09-20T11:39:53.383 helix_lsp::transport [ERROR] err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"

```
</details>

### Platform

Linux

### Terminal Emulator

tmux 3.0a

### Helix Version

helix 22.08.1 (947ff63e)

**Comment by CptPotato** [comment]
Removing cursor navigation from insert mode has been a recent (controversial) change, see #3671, #3865.

If you want to reintroduce the keybinds you can do so by adding them to your `config.toml`:

```toml
[keys.insert]
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"
```

**Comment by aral** [comment]
Further to @CptPotato’s reply, if you want to enable the word movement keys and home and end functionality also, you need to add the following to your config file:

```toml
[keys.insert]
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"
C-left = "move_prev_word_end"
C-right = "move_next_word_start"
end = "goto_line_end_newline"
home = "goto_line_start"
```

Although you might want to remove the `up` and `down` bindings so you don’t trigger the autocompletion bug when navigating vertically in insert mode.

**Comment by yellowred** [comment]
Thanks for your help. Would be great to have it in the docs, so new comers like myself understood what that mode is for. Right now the docs say arrows work in the Insert mode.

**Comment by yellowred** [comment]
@aral Thanks for update. I have also put arrows keys back into the config except Up and Down so I wouldn't be affected by auto complete bug. Nice to see that this project has so lively discussions and passionate devs.
