### ISSUE TITLE
Index out of bounds panic when playing around with selections.

### ISSUE THREAD

**Issue by juho-p** [helix-editor/helix#391]
### Reproduction steps

Have lines of text in the editor. Select some of it. Press `S`. Search some pattern (for example, empty space) and enter. Move around. Crash (sometimes, very rarely, not sure what exaclty has to happen).

I don't know how to properly reproduce this.

### Environment

- Platform: Linux
- Helix version: v0.3.0-23-ge915988 (current master)

<details><summary>~/.cache/helix/helix.log</summary>

-> My helix log is empty

Running with RUST_BACKTRACE=1, I was able to randomly produce this.

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/hx`
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', helix-core/src/selection.rs:147:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   5: <smallvec::SmallVec<A> as core::ops::index::Index<I>>::index
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.6.1/src/lib.rs:1624:10
   6: helix_core::selection::Selection::primary
             at ./helix-core/src/selection.rs:147:9
   7: helix_core::selection::Selection::cursor
             at ./helix-core/src/selection.rs:152:9
   8: helix_view::view::View::ensure_cursor_in_view
             at ./helix-view/src/view.rs:87:22
   9: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
             at ./helix-term/src/ui/editor.rs:685:17
  10: helix_term::compositor::Compositor::handle_event
             at ./helix-term/src/compositor.rs:115:19
  11: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:206:32
  12: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:158:21
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  14: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:481:9
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  16: hx::main::{{closure}}
             at ./helix-term/src/main.rs:97:5
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  18: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:263:54
  19: tokio::coop::with_budget::{{closure}}
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  20: std::thread::local::LocalKey<T>::try_with
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  21: std::thread::local::LocalKey<T>::with
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  22: tokio::coop::with_budget
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  23: tokio::coop::budget
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  24: tokio::park::thread::CachedParkThread::block_on
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:263:31
  25: tokio::runtime::enter::Enter::block_on
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/enter.rs:151:13
  26: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/mod.rs:71:9
  27: tokio::runtime::Runtime::block_on
             at /home/juho/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:452:43
  28: hx::main
             at ./helix-term/src/main.rs:99:5
  29: core::ops::function::FnOnce::call_once
             at /home/juho/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
k19:16:55 - ~/code/helix 
```

</details>

**Comment by juho-p** [comment]
Suspicious code is fn normalize() at helix-core/src/selection.rs:217

It seems to sometimes return too big `primary_index` due to broken logic (I think).

**Comment by juho-p** [comment]
A pretty messy way to reproduce as follows:

In the same directory as attached file: [foo.txt](https://github.com/helix-editor/helix/files/6738354/foo.txt)

```
:o foo.txt<cr>
xxxxxxxxxxS <cr>gljjjjjjjjjjk
```
