### ISSUE TITLE
Crash: Position is out of range for changeset

### ISSUE THREAD

**Issue by Jummit** [helix-editor/helix#4226]
### Summary

I got this crash multiple times:

```
thread 'main' panicked at 'Position 738 is out of range for changeset len 695!', helix-core/src/transaction.rs:397:13
```

### Reproduction Steps

I tried this:

1. `hx`
2. Navigate in the document

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-10-12T15:13:00.469 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 43, character: 0 }, end: Position { line: 43, character: 1 } }, severity: Some(Error), code: None, code_description: None, source: Some("rustc"), message: "unexpected closing delimiter: `}`\nunexpected closing delimiter", related_information: Some([DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 40, character: 24 }, end: Position { line: 40, character: 25 } } }, message: "this opening brace..." }, DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 42, character: 4 }, end: Position { line: 42, character: 5 } } }, message: "...matches this closing brace" }]), tags: None, data: None }
2022-10-12T15:13:00.470 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 42, character: 4 }, end: Position { line: 42, character: 5 } }, severity: Some(Hint), code: None, code_description: None, source: Some("rustc"), message: "...matches this closing brace", related_information: Some([DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 43, character: 0 }, end: Position { line: 43, character: 1 } } }, message: "original diagnostic" }]), tags: None, data: None }
2022-10-12T15:13:08.182 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 42, character: 0 }, end: Position { line: 42, character: 1 } }, severity: Some(Error), code: None, code_description: None, source: Some("rustc"), message: "unexpected closing delimiter: `}`\nunexpected closing delimiter", related_information: Some([DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 39, character: 24 }, end: Position { line: 39, character: 25 } } }, message: "this opening brace..." }, DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 41, character: 4 }, end: Position { line: 41, character: 5 } } }, message: "...matches this closing brace" }]), tags: None, data: None }
2022-10-12T15:13:08.182 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 41, character: 4 }, end: Position { line: 41, character: 5 } }, severity: Some(Hint), code: None, code_description: None, source: Some("rustc"), message: "...matches this closing brace", related_information: Some([DiagnosticRelatedInformation { location: Location { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/jummit/Programming/tree-sitter-lsp/src/main.rs", query: None, fragment: None }, range: Range { start: Position { line: 42, character: 0 }, end: Position { line: 42, character: 1 } } }, message: "original diagnostic" }]), tags: None, data: None }

```

</details>

### Platform

Linux

### Terminal Emulator

Gnome Terminal

### Helix Version

22.08.1 (c54a0363)

**Comment by the-mikedavis** [comment]
This is caused by the changes in https://github.com/helix-editor/helix/pull/4186 but I think the crashes are red herrings of other problems with selections or transactions.

Do you remember what you were doing right before the crash? Navigating as you say in the reproduction steps should not cause this because navigating doesn't produce any transactions.

**Comment by Jummit** [comment]
I think the crash occurred after exiting insert mode with some documentation open and moving about.

**Comment by dariooddenino** [comment]
Experienced this today. It's very easy to replicate. From an empty buffer, type `ia<esc>uia`

The result is:
```
thread 'main' panicked at 'Position 2 is out of range for changeset len 1!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by the-mikedavis** [comment]
`panic!` calls in the source are usually assertions that are necessary for correctness. The problem was not really the panic but the funky state the editor got into (in this case by not applying transactions to the view in undo/redo).
