### ISSUE TITLE
Implement `window/showMessageRequest` in LSP client

### ISSUE THREAD

**Issue by ckipp01** [helix-editor/helix#4699]
Some servers will make use of this. You can see it in the spec [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest). An example of a server that uses this is [Metals](https://scalameta.org/metals/), which is the language server for Scala. We use this when a user first opens up a workspace to prompt them to import the workspace. A request looks like this:

```json
[Trace - 03:48:41 pm] Sending request 'window/showMessageRequest - (2)'
Params: {
  "actions": [
    {
      "title": "Import build"
    },
    {
      "title": "Not now"
    },
    {
      "title": "Don\u0027t show again"
    }
  ],
  "type": 3,
  "message": "New sbt workspace detected, would you like to import the build?"
}
```

Having support for this would be great. There's also a handful of other usecases with Metals for this requestt.

**Comment by jba** [comment]
I'm having the same issue with `gopls`, which is trying to tell me about a bad config:
```
helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "Invalid settings: unexpected gopls setting \"moose\"; unexpected gopls setting \"ui\"" }
```

**Comment by abrassel** [comment]
Hey, I wanted to jump in on this issue - I would love to do the remaining work to get this PR merged.

**Comment by wzzrd** [comment]
I would soooo love to get the functionality merged into helix... I'm a heavy user of ansible-language-server, which doesn't currently work with helix because of this :( 

More than happy to do some testing is that helps?

**Comment by roignpar** [comment]
I am also running into an issue related to this with the F# LSP ([fsautocomplete](https://github.com/ionide/FsAutoComplete)):
```
2025-05-31T22:41:44.931 helix_term::application [ERROR] Language Server: Method window/showMessageRequest not found in request 22
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls err <- "[22:41:44.931 ERR] [FsAutoComplete.Lsp.AdaptiveFSharpLspServer] HandleFormatting Request Errored\n"
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls err <- "System.AggregateException: One or more errors occurred. (Method not found: window/showMessageRequest)\n"
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls err <- " ---> StreamJsonRpc.RemoteMethodNotFoundException: Method not found: window/showMessageRequest\n"
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls err <- "   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)\n"
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls err <- "   --- End of inner exception stack trace ---\n"
2025-05-31T22:41:44.932 helix_lsp::transport [ERROR] fsharp-ls <- InvalidParams: System.AggregateException: One or more errors occurred. (Method not found: window/showMessageRequest)
 ---> StreamJsonRpc.RemoteMethodNotFoundException: Method not found: window/showMessageRequest
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   --- End of inner exception stack trace ---
2025-05-31T22:41:44.932 helix_view::document [WARN] LSP formatting failed: protocol error: InvalidParams: System.AggregateException: One or more errors occurred. (Method not found: window/showMessageRequest)
 ---> StreamJsonRpc.RemoteMethodNotFoundException: Method not found: window/showMessageRequest
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   --- End of inner exception stack trace ---
```
As a result completions and inlay hints work, but code formatting doesn't.

**Comment by DrSensor** [comment]
running same issue with [`@rescript/language-server`](https://github.com/rescript-lang/rescript-vscode/tree/master/server)
```log
2025-11-17T17:29:16.040 helix_term::application [ERROR] Language Server: Method window/showMessageRequest not found in request 1
2025-11-17T17:29:20.544 helix_lsp::transport [ERROR] rescript-language-server err: <- StreamClosed
2025-11-17T17:29:20.638 helix_term::application [ERROR] Language Server: Method window/showMessageRequest not found in request 1
```

**Comment by the-mikedavis** [comment]
Added in 76c23b306716ebd9ec6e73384915e58fad061557
