### ISSUE TITLE
Crash on Save JSON File with Emojis

### ISSUE THREAD

**Issue by kristopherbullinger** [helix-editor/helix#4791]
### Summary

when saving a file with the following contents:
```json
[
"🇺🇸",
"🎄"
]
```
helix crashes with the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid char range 14..13: start must be <= end', /Users/blah/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/rope.rs:546:37
```

### Reproduction Steps

create a file `data.json` with the following contents:
```json
[
"🇺🇸",
"🎄"
]
```
(note that the level of indentation appears to be important)

Open the file with helix `hx data.json`. 

Save the file with `:w`.

Observe the crash.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-17T15:31:01.642 helix_loader [DEBUG] Located configuration folders: ["[redacted]"]
2022-11-17T15:31:01.651 helix_view::clipboard [INFO] Using pbcopy+pbpaste to interact with the system clipboard
2022-11-17T15:31:01.653 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-11-17T15:31:01.653 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-11-17T15:31:01.653 mio::poll [TRACE] registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
2022-11-17T15:31:01.653 helix_lsp::client [INFO] Using custom LSP config: {"provideFormatter":true}
2022-11-17T15:31:01.653 mio::poll [TRACE] registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
2022-11-17T15:31:01.654 mio::poll [TRACE] registering event source with poller: token=Token(5), interests=READABLE | WRITABLE
2022-11-17T15:31:01.654 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false},"workspaceFolders":true}},"initializationOptions":{"provideFormatter":true},"processId":25858,"rootPath":"[redacted]","rootUri":"[redacted]","workspaceFolders":[{"name":"fox-weather-service","uri":"[redacted]"}]},"id":0}
2022-11-17T15:31:01.654 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-11-17T15:31:01.654 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2022-11-17T15:31:01.821 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"documentSymbolProvider":true,"documentRangeFormattingProvider":true,"documentFormattingProvider":true,"colorProvider":{},"foldingRangeProvider":true,"selectionRangeProvider":true,"documentLinkProvider":{}}}}
2022-11-17T15:31:01.821 helix_lsp::transport [INFO] <- {"capabilities":{"colorProvider":{},"documentFormattingProvider":true,"documentLinkProvider":{},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"foldingRangeProvider":true,"hoverProvider":true,"selectionRangeProvider":true,"textDocumentSync":2}}
2022-11-17T15:31:01.821 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2022-11-17T15:31:01.821 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"provideFormatter":true}}}
2022-11-17T15:31:01.821 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"json","text":"[\n\"🇺🇸\",\n\"🎄\"\n]\n","uri":"[redacted]","version":0}}}
2022-11-17T15:31:01.823 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"[redacted]","diagnostics":[]}}
2022-11-17T15:31:02.449 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":true,"tabSize":2},"textDocument":{"uri":"[redacted]"}},"id":1}
2022-11-17T15:31:02.451 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":1,"result":[{"range":{"start":{"line":0,"character":1},"end":{"line":1,"character":0}},"newText":"\n  "},{"range":{"start":{"line":1,"character":7},"end":{"line":2,"character":0}},"newText":"\n  "},{"range":{"start":{"line":3,"character":1},"end":{"line":4,"character":0}},"newText":""}]}
2022-11-17T15:31:02.451 helix_lsp::transport [INFO] <- [{"newText":"\n  ","range":{"end":{"character":0,"line":1},"start":{"character":1,"line":0}}},{"newText":"\n  ","range":{"end":{"character":0,"line":2},"start":{"character":7,"line":1}}},{"newText":"","range":{"end":{"character":0,"line":4},"start":{"character":1,"line":3}}}]
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller
2022-11-17T15:31:02.453 mio::poll [TRACE] deregistering event source from poller

```

</details>

### Platform

macOS

### Terminal Emulator

iTerm2 3.4.16

### Helix Version

helix 22.08.1 (a7ec4aae)

**Comment by Stonks3141** [comment]
Can't reproduce on Manjaro KDE with Konsole, might be a Mac problem.

**Comment by kristopherbullinger** [comment]
Yes, just to be sure, i cloned the helix project and ran `cargo build --release ~/mydir/data.json` and got the same error.

**Comment by the-mikedavis** [comment]
This panic needs the language server to be installed - it's caused by the auto-formatting change.

<details><summary>On 322e957ea1947108d10699f217b75b831df2a2c0 in a debug build, I see this backtrace...</summary>

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/michael/src/helix/hx/helix-core/src/transaction.rs:487:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: helix_core::transaction::Transaction::change
             at ./helix-core/src/transaction.rs:487:24
   4: helix_lsp::util::generate_transaction_from_edits
             at ./helix-lsp/src/lib.rs:221:9
   5: helix_view::document::Document::format::{{closure}}
             at ./helix-view/src/document.rs:498:16
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
   8: helix_term::commands::make_format_callback::{{closure}}
             at ./helix-term/src/commands.rs:2547:24
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  11: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  13: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
  14: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/mod.rs:1626:9
  15: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/next.rs:32:9
  16: helix_term::application::Application::event_loop_until_idle::{{closure}}::{{closure}}
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/select.rs:507:49
  17: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/future/poll_fn.rs:38:9
  18: helix_term::application::Application::event_loop_until_idle::{{closure}}
             at ./helix-term/src/application.rs:328:13
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  20: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:311:57
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  22: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:1009:38
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  24: hx::main_impl::{{closure}}
             at ./helix-term/src/main.rs:155:53
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  26: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:54
  27: tokio::coop::with_budget::{{closure}}
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  30: tokio::coop::with_budget
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
  31: tokio::coop::budget
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  32: tokio::park::thread::CachedParkThread::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  33: tokio::runtime::enter::Enter::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/enter.rs:152:13
  34: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/mod.rs:79:9
  35: tokio::runtime::Runtime::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/mod.rs:492:44
  36: hx::main_impl
             at ./helix-term/src/main.rs:157:5
  37: hx::main
             at ./helix-term/src/main.rs:37:21
  38: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

This can be reproduced most with this test case:

```rust
// helix-lsp/src/lib.rs
// ...
    #[test]
    fn emoji_format_gh_4791() {
        use lsp_types::{Position, Range, TextEdit};

        let edits = vec![
            TextEdit {
                range: Range {
                    start: Position {
                        line: 0,
                        character: 1,
                    },
                    end: Position {
                        line: 1,
                        character: 0,
                    },
                },
                new_text: "\n  ".to_string(),
            },
            TextEdit {
                range: Range {
                    start: Position {
                        line: 1,
                        character: 7,
                    },
                    end: Position {
                        line: 2,
                        character: 0,
                    },
                },
                new_text: "\n  ".to_string(),
            },
        ];

        let source = Rope::from_str(
            r#"[
"🇺🇸",
"🎄"
]"#,
        );

        generate_transaction_from_edits(&source, edits, OffsetEncoding::Utf8);
    }
```

I'm not sure whether we're not calculating the position in the rope incorrectly or if the language server is sending nonsense.

We may need to add a clause in `lsp_pos_to_pos` which handles

> If the `character` value is greater than the line length it defaults back to the line length.

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position
