### ISSUE TITLE
Position out of range for changeset panic

### ISSUE THREAD

**Issue by koalazub** [helix-editor/helix#4900]
### Summary

Crash when coding a Flutter/Dart project

```
thread 'main' panicked at 'Position 461 is out of range for changeset len 450!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
keep executing.
```

### Reproduction Steps

Using the latest version of Dart/Flutter

I would:
- open helix with `hx`
- Wait for the LSP to kick in
- Jump between some code
- make some code actions

This is where the crash would sometimes occur. I'm moving around pretty quickly, so I wasn't paying attention to where it crashed these past 2 times. Will update the description if it happens again

Update:

Had another crash when changing to insert on a line

### Helix log

Log is found in the gist(file is too large): https://gist.github.com/koalazub/b15e960b48080f301b358e32d630e9ee

### Platform

Ubuntu: Ubuntu 22.10

### Terminal Emulator

alacritty 0.12.0-dev (c5ae05e8)

### Helix Version

helix 22.08.1 (8529d756)

**Comment by getreu** [comment]
I run into this 10 times in the last 2 days. See backtrace below.

helix 22.08.1 (f0f295a6)

```
getreu@mosel1:.../tp-note$ hx .
thread 'main' panicked at 'Position 16284 is out of range for changeset len 16275!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
getreu@mosel1:.../tp-note$ RUST_BACKTRACE=1 hx
thread 'main' panicked at 'Position 16272 is out of range for changeset len 16262!', helix-core/src/transaction.rs:397:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: helix_core::transaction::ChangeSet::map_pos
   3: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   4: helix_core::selection::Selection::map
   5: helix_view::view::View::apply
   6: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   7: helix_term::compositor::Compositor::handle_event
   8: helix_term::application::Application::handle_terminal_events
   9: hx::main_impl::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: tokio::runtime::runtime::Runtime::block_on
  13: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
getreu@mosel1:.../tp-note$
```

**Comment by getreu** [comment]
I run into this 10 times in the last 2 days. See backtrace below.

helix 22.08.1 (f0f295a6)

```
$:.../tp-note$ hx .
thread 'main' panicked at 'Position 16284 is out of range for changeset len 16275!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
getreu@mosel1:.../tp-note$ RUST_BACKTRACE=1 hx
thread 'main' panicked at 'Position 16272 is out of range for changeset len 16262!', helix-core/src/transaction.rs:397:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: helix_core::transaction::ChangeSet::map_pos
   3: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   4: helix_core::selection::Selection::map
   5: helix_view::view::View::apply
   6: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   7: helix_term::compositor::Compositor::handle_event
   8: helix_term::application::Application::handle_terminal_events
   9: hx::main_impl::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: tokio::runtime::runtime::Runtime::block_on
  13: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$:.../tp-note$
```

**Comment by philipgiuliani** [comment]
I also saw this crash. Commit 642a961c032b2a7e7fa67bfc3da54588d0ae8c5b is still OK. Seems it had been introduced with the transaction changes.

/cc @the-mikedavis

**Comment by the-mikedavis** [comment]
I found a reproduction case:

* `hx f.rs` with rust-analyzer and rustfmt setup and auto-pairs enabled
* `ifn main() {<ret>:wu`

<details><summary>backtrace...</summary>

```
thread 'main' panicked at 'Position 18 is out of range for changeset len 13!', helix-core/src/transaction.rs:397:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: helix_core::transaction::ChangeSet::map_pos
             at ./helix-core/src/transaction.rs:397:13
   3: helix_core::selection::Range::map
             at ./helix-core/src/selection.rs:172:17
   4: helix_core::selection::Selection::map::{{closure}}
             at ./helix-core/src/selection.rs:459:30
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:280:13
   6: core::option::Option<T>::map
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:912:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/map.rs:103:9
   8: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.10.0/src/lib.rs:1769:36
   9: <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.10.0/src/lib.rs:1754:9
  10: core::iter::traits::iterator::Iterator::collect
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/traits/iterator.rs:1784:9
  11: helix_core::selection::Selection::map
             at ./helix-core/src/selection.rs:457:13
  12: helix_view::view::JumpList::apply
             at ./helix-view/src/view.rs:78:30
  13: helix_view::view::View::apply
             at ./helix-view/src/view.rs:353:9
  14: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
             at ./helix-term/src/ui/editor.rs:1434:33
  15: helix_term::compositor::Compositor::handle_event
             at ./helix-term/src/compositor.rs:141:19
  16: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:595:22
  17: helix_term::application::Application::event_loop_until_idle::{{closure}}
             at ./helix-term/src/application.rs:332:21
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  19: helix_term::application::Application::event_loop::{{closure}}
             at ./helix-term/src/application.rs:311:57
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  21: helix_term::application::Application::run::{{closure}}
             at ./helix-term/src/application.rs:1035:38
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  23: hx::main_impl::{{closure}}
             at ./helix-term/src/main.rs:155:53
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  25: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  26: tokio::runtime::coop::with_budget
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  27: tokio::runtime::coop::budget
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  28: tokio::runtime::park::CachedParkThread::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  29: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  30: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  31: tokio::runtime::runtime::Runtime::block_on
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:281:45
  32: hx::main_impl
             at ./helix-term/src/main.rs:157:5
  33: hx::main
             at ./helix-term/src/main.rs:37:21
  34: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by alexsunxl** [comment]
I meet this panic also, hope for this PR merged quickly😀. And where can i find the helix-panic-log?
