### ISSUE TITLE
Crash when Appending a newline at the end of a file

### ISSUE THREAD

**Issue by luctius** [helix-editor/helix#492]
Version: Master (d4bd5b3)
Video: https://asciinema.org/connect/d64d27b4-45a6-4223-a235-a8ed951d2d7b
Backtrace:
thread 'main' panicked at 'assertion failed: increment >= 0', helix-core/src/indent.rs:96:5
stack backtrace:
   0:     0x55e5c350cc60 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e5c350cc60 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e5c350cc60 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e5c350cc60 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e5c35336ff - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55e5c3507fb5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55e5c350ef6b - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e5c350ef6b - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e5c350ef6b - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55e5c350ea3d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55e5c2791c23 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc5864f128499e426
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1560:9
  11:     0x55e5c275d8c1 - helix_term::application::Application::run::{{closure}}::{{closure}}::h14ce802e2229c1c5
                               at /home/cor/extra/workspace/helix/helix-term/src/application.rs:461:13
  12:     0x55e5c350f5a0 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
  13:     0x55e5c350f0e7 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  14:     0x55e5c350d0fc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  15:     0x55e5c350f079 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  16:     0x55e5c273e781 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  17:     0x55e5c273e6cd - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  18:     0x55e5c310775d - helix_core::indent::calculate_indentation::h094825f77ee612f7
                               at /home/cor/extra/workspace/helix/helix-core/src/indent.rs:96:5
  19:     0x55e5c3107900 - helix_core::indent::suggested_indent_for_pos::h62c1c18ecd06ecca
                               at /home/cor/extra/workspace/helix/helix-core/src/indent.rs:144:9
  20:     0x55e5c29a967a - helix_term::commands::insert::insert_newline::{{closure}}::hd0bfebafda0de742
                               at /home/cor/extra/workspace/helix/helix-term/src/commands.rs:2762:32
  21:     0x55e5c2991fff - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h7378f7b68ce0539b
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:280:13
  22:     0x55e5c29d4964 - core::option::Option<T>::map::h9ed2559df4dc9675
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:487:29
  23:     0x55e5c28a2901 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hdf77ad55ed8b413a
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:101:9
  24:     0x55e5c282ecf8 - helix_core::transaction::Transaction::change::h980a1e86b0475694
                               at /home/cor/extra/workspace/helix/helix-core/src/transaction.rs:489:36
  25:     0x55e5c282cb79 - helix_core::transaction::Transaction::change_by_selection::hfcce9dc9021332e0
                               at /home/cor/extra/workspace/helix/helix-core/src/transaction.rs:513:9
  26:     0x55e5c29a91ed - helix_term::commands::insert::insert_newline::h15d61aa175903d73
                               at /home/cor/extra/workspace/helix/helix-term/src/commands.rs:2751:31
  27:     0x55e5c29626cc - helix_term::commands::Command::execute::h3185703320bccc3c
                               at /home/cor/extra/workspace/helix/helix-term/src/commands.rs:159:9
  28:     0x55e5c2a374b5 - helix_term::ui::editor::EditorView::insert_mode::h7d1150b812a6efd5
                               at /home/cor/extra/workspace/helix/helix-term/src/ui/editor.rs:564:13
  29:     0x55e5c2a38189 - <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event::h2c64ee066814fdc4
                               at /home/cor/extra/workspace/helix/helix-term/src/ui/editor.rs:680:33
  30:     0x55e5c289cc77 - helix_term::compositor::Compositor::handle_event::h8924affa43a7463c
                               at /home/cor/extra/workspace/helix/helix-term/src/compositor.rs:117:19
  31:     0x55e5c289c3a4 - helix_term::application::Application::handle_terminal_events::h6d3cc44fb550b0cd
                               at /home/cor/extra/workspace/helix/helix-term/src/application.rs:191:32
  32:     0x55e5c27573ff - helix_term::application::Application::event_loop::{{closure}}::ha66101d454f90ede
                               at /home/cor/extra/workspace/helix/helix-term/src/application.rs:154:21
  33:     0x55e5c276f36b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h51020fa259a062aa
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  34:     0x55e5c275ce5e - helix_term::application::Application::run::{{closure}}::h9a55a330631dfdb9
                               at /home/cor/extra/workspace/helix/helix-term/src/application.rs:464:9
  35:     0x55e5c276f7a9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he152e32b915a2d6e
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  36:     0x55e5c276550f - hx::main::{{closure}}::h9f621d5968e9d5b5
                               at /home/cor/extra/workspace/helix/helix-term/src/main.rs:97:5
  37:     0x55e5c276f2b9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4bb87a4d90553ec1
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  38:     0x55e5c2769410 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h375b085a13ba8a44
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/park/thread.rs:263:54
  39:     0x55e5c2775f82 - tokio::coop::with_budget::{{closure}}::h85ac97dc1de12c6d
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:106:9
  40:     0x55e5c278ff08 - std::thread::local::LocalKey<T>::try_with::hd4f7ea314e2bd100
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  41:     0x55e5c278f85d - std::thread::local::LocalKey<T>::with::hd5c5e2b7e764b66f
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  42:     0x55e5c2769157 - tokio::coop::with_budget::h1072acf7491f7db5
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:99:5
  43:     0x55e5c2769157 - tokio::coop::budget::h5c081113a9f9bb0c
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:76:5
  44:     0x55e5c2769157 - tokio::park::thread::CachedParkThread::block_on::hafe6a95d6c65d933
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/park/thread.rs:263:31
  45:     0x55e5c278896e - tokio::runtime::enter::Enter::block_on::h2f178ec61e1e72a5
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/enter.rs:151:13
  46:     0x55e5c2776363 - tokio::runtime::thread_pool::ThreadPool::block_on::he9b7bdf4cf9c393f
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/thread_pool/mod.rs:71:9
  47:     0x55e5c2773412 - tokio::runtime::Runtime::block_on::h481857665f74b812
                               at /home/cor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/mod.rs:452:43
  48:     0x55e5c27644e2 - hx::main::hb06e0a3771c36f6c
                               at /home/cor/extra/workspace/helix/helix-term/src/main.rs:99:5
  49:     0x55e5c277ed9b - core::ops::function::FnOnce::call_once::h1be0cc5dc4e15808
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  50:     0x55e5c275e2be - std::sys_common::backtrace::__rust_begin_short_backtrace::h982518b453457fc5
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  51:     0x55e5c2774851 - std::rt::lang_start::{{closure}}::hd2668bc1d37a90d0
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  52:     0x55e5c350f97a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  53:     0x55e5c350f97a - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  54:     0x55e5c350f97a - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  55:     0x55e5c350f97a - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  56:     0x55e5c350f97a - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  57:     0x55e5c2774830 - std::rt::lang_start::hfcd9edbfd390d28e
                               at /home/cor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  58:     0x55e5c2765bdc - main
  59:     0x7fc6c84c6565 - __libc_start_main
  60:     0x55e5c273ef1e - _start
  61:                0x0 - <unknown>

**Comment by cessen** [comment]
I'm having a really hard time reproducing this.  What are the steps?  Just go to the end of a file in insert mode and press enter?

**Comment by luctius** [comment]
> I'm having a really hard time reproducing this.  What are the steps?  Just go to the end of a file in insert mode and press enter?

I don't have access to my pc at the moment but I think this should do it.

- Have a file with (at least) a single character (in my case a bracket) on the last line.
- go to the end of the file, and append past the character.
This should cause the crash.

If this does not reproduce it, I will make a better test case tomorrow.

**Comment by cessen** [comment]
Hmm, yeah, that's not triggering anything for me.  Just works as expected.

The main reason I'm asking is I want to verify if it still happens in #376 or not.  It seems to have incidentally fixed a few other errors similar to this one.  So if it fixes this one too, then I think we can just wait to merge that (which is getting pretty close).  But if it doesn't fix it, then we'll want to merge @pickfire's fix.

**Comment by pickfire** [comment]
@cessen I think you can just merge my fix and backport it to the refactor. @luctius Can you please see if it fixes your issue?

**Comment by cessen** [comment]
> I think you can just merge my fix and backport it to the refactor.

It also seems like my PR isn't quite as close to getting merged as I thought, so might as well fix it in master anyway.
