### ISSUE TITLE
Async job failed: protocol error

### ISSUE THREAD

**Issue by jcsmithf22** [helix-editor/helix#5537]
When ever I open a '<' in a .tsx file, I get the following error message underneath the status line. 

Async job failed: protocol error: InternalError: Request textDocument/completion failed with message: <main> TypeScript Server Error (4.8.4) Cannot read properties of undefined (reading 'getFullStart')

The rest of the message is cut off. Does anyone have any idea what is causing this? Is it a typescript server error? I have attached a screenshot. Thank you ahead of time.

<img width="1680" alt="Screenshot 2023-01-14 at 7 46 34 PM" src="https://user-images.githubusercontent.com/88597020/212510771-00047e76-bf05-4455-8f29-843dcbb93d02.png">

This is the log:

```
2023-01-14T20:02:25.553 helix_view::editor [ERROR] editor error: Async job failed: protocol error: InternalError: Request textDocument/completion failed with message: <main> TypeScript Server Error (4.9.4)
Cannot read properties of undefined (reading 'getFullStart')
TypeError: Cannot read properties of undefined (reading 'getFullStart')
    at isPositionInsideNode (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/next/dist/server/next-typescript.js:159:32)
    at /Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/next/dist/server/next-typescript.js:299:25
    at visitNodes (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:31224:30)
    at forEachChildInSourceFile (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:31583:20)
    at Object.forEachChild (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:31998:47)
    at proxy.getCompletionsAtPosition (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/next/dist/server/next-typescript.js:294:16)
    at Session.getCompletions (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:181290:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:179963:61)
    at /Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/Users/josiahsmith/Documents/Programming/Next/fpchurch/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by nxy7** [comment]
I've just built helix from master and also have this error. I don't think it's lsp fault, as it didn't affect my setup before updating from last release to master branch.

**Comment by jcsmithf22** [comment]
> I've just built helix from master and also have this error. I don't think it's lsp fault, as it didn't affect my setup before updating from last release to master branch.

It is happening to me with the master branch build as well as the homebrew version. I haven't had any success troubleshooting.

**Comment by jcsmithf22** [comment]
> I've just built helix from master and also have this error. I don't think it's lsp fault, as it didn't affect my setup before updating from last release to master branch.

Are you using next js 13 with the app directory? Apparently this is a next js issue, and happens in other editors as well. It happens when you use a `export default function FunctionName() {}` in a file named page.js in the app/ directory.

A temporary fix is adding empty {} in the function declaration.

`export default function FunctionName({}) {}`

**Comment by nxy7** [comment]
I've built helix from master again (i'm hopping on several branches rn) and error went away. Indeed I was using nextjs with app directory, but without updating node dependencies error went away so now I'm not really sure what caused it.

**Comment by jcsmithf22** [comment]
I will have to try building from master again then, I'm confused why I had the same issue with vscode as well, even after creating a brand new next js app just to test for the issue.

**Comment by Proful** [comment]
> > I've just built helix from master and also have this error. I don't think it's lsp fault, as it didn't affect my setup before updating from last release to master branch.
> 
> Are you using next js 13 with the app directory? Apparently this is a next js issue, and happens in other editors as well. It happens when you use a `export default function FunctionName() {}` in a file named page.js in the app/ directory.
> 
> A temporary fix is adding empty {} in the function declaration.
> 
> `export default function FunctionName({}) {}`

Worked for me. Thanks!
