### ISSUE TITLE
Panics on helix-v0.0.7-x86_64-windows

### ISSUE THREAD

**Issue by mheden** [helix-editor/helix#56]
I downloaded the zip file from the `release` page:

```
C:\devel>c:\bin\helix-v0.0.7-x86_64-windows\hx.exe
thread 'main' panicked at 'Attempt to slice past end of RopeSlice: slice end 1, RopeSlice length 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ropey-1.2.0\src\slice.rs:784:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\devel>set RUST_BACKTRACE=1

C:\devel>c:\bin\helix-v0.0.7-x86_64-windows\hx.exe
thread 'main' panicked at 'index out of bounds: the len is 10600 but the index is 10600', helix-tui\src\buffer.rs:185:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

C:\devel>set RUST_BACKTRACE=full

C:\devel>c:\bin\helix-v0.0.7-x86_64-windows\hx.exe
thread 'main' panicked at 'index out of bounds: the len is 10600 but the index is 10600', helix-tui\src\buffer.rs:185:14
stack backtrace:
   0:     0x7ff67e8918de - <unknown>
   1:     0x7ff67e8adb0c - <unknown>
   2:     0x7ff67e88d7c8 - <unknown>
   3:     0x7ff67e89484d - <unknown>
   4:     0x7ff67e894319 - <unknown>
   5:     0x7ff67e5a5513 - <unknown>
   6:     0x7ff67e894f35 - <unknown>
   7:     0x7ff67e894aa1 - <unknown>
   8:     0x7ff67e8921ff - <unknown>
   9:     0x7ff67e8949f9 - <unknown>
  10:     0x7ff67e9a8910 - tree_sitter_typescript
  11:     0x7ff67e9a88d7 - tree_sitter_typescript
  12:     0x7ff67e68305f - <unknown>
  13:     0x7ff67e5bf271 - <unknown>
  14:     0x7ff67e5a5173 - <unknown>
  15:     0x7ff67e598739 - <unknown>
  16:     0x7ff67e5b98e9 - <unknown>
  17:     0x7ff67e52e2f1 - <unknown>
  18:     0x7ff67e51c7a6 - <unknown>
  19:     0x7ff67e51c7ca - <unknown>
  20:     0x7ff67e895097 - <unknown>
  21:     0x7ff67e52ed37 - <unknown>
  22:     0x7ff67e9905d0 - tree_sitter_typescript
  23:     0x7ffaadaf7c24 - BaseThreadInitThunk
  24:     0x7ffaaf9ed721 - RtlUserThreadStart

**Comment by archseer** [comment]
A fix for this was pushed (https://github.com/helix-editor/helix/commit/78980f575be1cbb31f1bdab92d3ecd2be4d2adac), waiting for 0.0.8 to build (https://github.com/helix-editor/helix/actions/runs/899578274) which will include the fix :)
