### ISSUE TITLE
Volar vue-language-server crashed when open vue files

### ISSUE THREAD

**Issue by sun617** [helix-editor/helix#6243]
### Summary

Build latest master branch of helix to open vue file then volar of vue-language-server crashed
Maybe this is related to change of https://github.com/helix-editor/helix/pull/6058 

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:
open vue file the vue-language-server volar started
Instead, this happened:
language server crashed

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-03-10T13:42:10.533 helix_term::application [ERROR] Language Server: Method client/registerCapability not found in request 0
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "/home/sun/.npm/_npx/8b20ff0d5db79130/node_modules/vscode-jsonrpc/lib/common/connection.js:565\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "                                               ^\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "ResponseError: Method not found: client/registerCapability\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "    at handleResponse (/home/sun/.npm/_npx/8b20ff0d5db79130/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "    at handleMessage (/home/sun/.npm/_npx/8b20ff0d5db79130/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "    at processMessageQueue (/home/sun/.npm/_npx/8b20ff0d5db79130/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "    at Immediate.<anonymous> (/home/sun/.npm/_npx/8b20ff0d5db79130/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "    at processImmediate (node:internal/timers:466:21) {\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "  code: -32601,\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "  data: undefined\n"
2023-03-10T13:42:10.535 helix_lsp::transport [ERROR] err <- "}\n"
2023-03-10T13:42:10.558 helix_lsp::transport [ERROR] err: <- StreamClosed
```

</details>

### Platform

Linux

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix part of flake.lock
```
    "helix": {
      "locked": {
        "lastModified": 1678334908,
        "narHash": "sha256-VUTKgrXMBr8UKl47vzWrpmc/0HmOijfJBS5QYibKpQo=",
        "owner": "helix-editor",
        "repo": "helix",
        "rev": "2cf4ce235662fcb272c684751b844b2ebc1b757f",
        "type": "github"
      },
```

**Comment by the-mikedavis** [comment]
Yep this is most likely caused by #6058. The language server should not be sending us a `client/registerCapability` (also see https://github.com/helix-editor/helix/issues/6230) and servers based on the `vscode-languageserver-node` dependency exit when we send a JSONRPC error for `client/registerCapability` requests because it doesn't handle the promise rejection. I'll look at submitting a patch upstream.

**Comment by the-mikedavis** [comment]
I opened up https://github.com/volarjs/volar.js/pull/18 which fixes this in volar. That dependency will then need to be updated in https://github.com/vuejs/language-tools/tree/master/packages/vue-language-server but that should fix the exit here.
