### ISSUE TITLE
Git diff gutter doesn't work on Windows

### ISSUE THREAD

**Issue by Snoupix** [helix-editor/helix#6358]
### Summary

Alright so I'm using Helix 22.12 (built from source) on Windows 11 with the *new* Windows Terminal.

Everything is working well except the Git diff gutter. I tried on many projects and I first thought that the problem was Windows Terminal but on my WSL distro, everything is working well (Rocky Linux 9, Helix version 22.12).

Feel free to ask me for details about my setup but I think I've mentioned everything.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
2023-03-17T03:07:55.356 helix_loader [DEBUG] Located configuration folders: []
2023-03-17T03:07:55.373 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:55.375 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:55.782 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-17T03:07:56.830 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:57.221 helix_term::commands::typed [DEBUG] quitting...
2023-03-17T03:07:57.221 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:57.243 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-17T03:07:57.308 helix_term::commands::typed [DEBUG] quitting...
2023-03-17T03:07:57.350 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:57.351 helix_term::job [DEBUG] waiting on jobs...
2023-03-17T03:07:57.351 helix_term::job [DEBUG] waiting on jobs...
2023-03-17T03:07:59.922 helix_loader [DEBUG] Located configuration folders: []
2023-03-17T03:07:59.938 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:07:59.941 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:08:00.348 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-17T03:08:06.319 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:08:06.609 helix_term::commands::typed [DEBUG] quitting...
2023-03-17T03:08:06.610 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:08:06.723 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-17T03:08:07.346 helix_term::commands::typed [DEBUG] quitting...
2023-03-17T03:08:07.346 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-17T03:08:07.346 helix_term::job [DEBUG] waiting on jobs...
2023-03-17T03:08:07.346 helix_term::job [DEBUG] waiting on jobs...
</details>

### Platform

Windows

### Terminal Emulator

Powershell 7.3.3

### Helix Version

helix 22.12 (96ff64a8)

**Comment by Snoupix** [comment]
Running `cargo test --workspace` on the cloned Helix repo (22.12 (96ff64a))
![image](https://user-images.githubusercontent.com/35530306/226344619-e958d83f-495e-40f2-94d0-be4617e5882f.png)

**Comment by pascalkuthe** [comment]
We have not been able to reproduce the problem independently in win11 virtual machines unofrtunately. I added a bunch of logging in #6441 that will hopefully help with pinning this down:
Could you run the tests again with that branch and check the output?
Could you also try opening any file in a git repo with helix build from the PR I linked and paste the PR here? 

Hopefully, the error message will give us some clues as to what is going on.

**Comment by Snoupix** [comment]
Alright ! There you go:
```
failures:

---- git::test::symlink stdout ----
thread 'git::test::symlink' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }', helix-vcs\src\git\test.rs:116:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- git::test::modified_file stdout ----
thread 'git::test::modified_file' panicked at 'called `Result::unwrap()` on an `Err` value: failed to open git repo

Caused by:
    0: Failed to load the git configuration
    1: Could not read configuration file
    2: The filename, directory name, or volume label syntax is incorrect. (os error 123)', helix-vcs\src\git\test.rs:79:41

---- git::test::unmodified_file stdout ----
thread 'git::test::unmodified_file' panicked at 'called `Result::unwrap()` on an `Err` value: failed to open git repo

Caused by:
    0: Failed to load the git configuration
    1: Could not read configuration file
    2: The filename, directory name, or volume label syntax is incorrect. (os error 123)', helix-vcs\src\git\test.rs:67:41
```

I tried again on a git linked project and still nothing.

**Comment by Snoupix** [comment]
OMG.
I apologize for the time lost talking about that issue on Element and here but I fixed the problem by updating my git CLI....
from `git version 2.22.0.windows.1` to `git version 2.40.0.windows.1`.

So now it's working as expected in Helix but I still have a git test failing out of 3.

```
failures:

---- git::test::symlink stdout ----
thread 'git::test::symlink' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }', helix-vcs\src\git\test.rs:116:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But, again, in Administrator mode, there is no problem at all.
```
test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 9.45s
```

Feeling dumb but thanks a lot for trying to solve the issue. @pascalkuthe

**Comment by kirawi** [comment]
I'm surprised that would fix it. AFAIK Helix doesn't use the git cli.

**Comment by Snoupix** [comment]
I'm surprised too, Pascal told me that on Element, that's why I didn't even thought about it.
It's maybe an issue with git-repository or imara-diff ? I don't know enough about them or the Helix code base to tell.

**Comment by pascalkuthe** [comment]
on windows we have to use the git CLI to determine certain parts of the config

**Comment by Byron** [comment]
@kirawi It's too bad the system has already been upgraded as it would be really interesting to learn why the following invocation could yield an invalid file path: `git config -l --show-origin`. Could you post the output here with `git 2.40` and if you find the time, for `git 2.22`? 

Even though `gitoxide` now learns how to be even more lenient when handling `git` configuration files, it would be better if it could figure out the correct file to open. Thanks again!
