### ISSUE TITLE
Panic when moving between monitors

### ISSUE THREAD

**Issue by dr4gut** [helix-editor/helix#6382]
### Summary

I had Helix open on a vertical monitor. I pulled the terminal emulator to a larger, horizontal monitor which caused helix to crash.

`thread 'main' panicked at 'index out of bounds: the len is 3180 but the index is 5532', helix-term/src/ui/menu.rs:354:29`

### Reproduction Steps

 

I cannot reproduce the issue

I tried this:

1. Run helix on a vertical monitor and move the window to a horizontal one

I expected this to happen: Helix resizes along with the emulator

Instead, this happened: Helix panicked

### Helix log

No relevant log entry. 

### Platform

Windows (WSL2)

### Terminal Emulator

Windows Terminal

### Helix Version

22.12-382-g34be71f

**Comment by Lykos153** [comment]
This just happened to me without multiple monitors. Just one single laptop monitor, resized Helix from half screen to full screen with a tiling window manager (xmonad) and got:

```
thread 'main' panicked at 'index out of bounds: the len is 2159 but the index is 3084', helix-term/src/ui/menu.rs:367:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Version: helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
https://github.com/helix-editor/helix/pull/7089#issuecomment-1564990166
