### ISSUE TITLE
Helix panics on pkill -USR1

### ISSUE THREAD

**Issue by mkapra** [helix-editor/helix#7459]
### Summary

helix panics when changing the theme in the configuration file on USR1 signal.

### Reproduction Steps

 

I tried this:

1. `:config-open`
2. Change the theme to another theme and save the configuration
3. Spawn a new terminal and run `pkill -USR1 hx`

I expected this to happen:

The configuration gets reloaded and the color scheme changes.

Instead, this happened:

```
thread 'main' panicked at 'index out of bounds: the len is 72 but the index is 81', /home/runner/work/helix/helix/helix-view/src/theme.rs:297:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Bus error
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-06-26T17:25:32.665 helix_term::application [WARN] failed to load theme `rose_pine_dawn` - Theme: file not found for: rose_pine_dawn
```

The confusing part is here that it says it could not find the theme. When restarting helix the theme is working.

</details>

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 23.05 (7f5940be)

**Comment by the-mikedavis** [comment]
Which themes are you switching between? Also, could you reproduce this with the the `RUST_BACKTRACE` environment variable set to `full`?

**Comment by mkapra** [comment]
I am using the themes `rose_pine_(dawn|moon)`

I tried setting `RUST_BACKTRACE` to `1` but the printed error was the same. With `RUST_BACKTRACE = full` its the same output too.

**Comment by mkapra** [comment]
Maybe this is interesting too: If I call `:config-reload` then the theme switch is made without any error.

**Comment by archseer** [comment]
The error will be the same, but the backtrace is useful for debugging.

**Comment by mkapra** [comment]
With that message I meant that there is no stack trace. Just the same message as before:

```
> RUST_BACKTRACE=full hx
thread 'main' panicked at 'index out of bounds: the len is 72 but the index is 81', /home/runner/work/helix/helix/helix-view/src/theme.rs:297:9
stack backtrace:
Bus error
```

**Comment by Snoupix** [comment]
I tried on the version **(master 23.05 843ae971)** and I have no problem at all.
My setup is not the same as yours (WSL, Arch), but it's changing both themes (rose pine moon and dawn) with `:config-reload` and with `pkill -USR1 hx`.

I'd like to help you but I can't reproduce the bug on my side.

**Comment by webdev23** [comment]
Yeah, it does crash using  `pkill -USR1 hx`, it wasn't earlier as i have scripts who were using it before.

I suspect it's linked to the shell or terminal you are using.

However, using kill and the good PID in my case, it does still work without crash:

`kill -USR1 $(ps -C hx -o pid | tail -n1)`
