### ISSUE TITLE
Panic on exit when mouse support is disabled

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#825]
Recently helix has started crashing for me every time I exit;the error message I get is `thread panicked while processing panic. aborting.`.

I was able to trace the issue back to handling mouse support:
Inside the panic hook `execute!(std::io::stdout(), DisableMouseCapture)` ([application.rs:565](https://github.com/helix-editor/helix/blob/f8f63c55081ee966c7cb2b84139c25c6301b5fff/helix-term/src/application.rs#L565)) produces another panic if mouse support is disabled, crashing the application. Commenting it out reveals the original stack trace - which conviniently seems to be the same bug:

<details>
<summary>backtrace</summary>

```
thread 'main' panicked at 'Original console mode not set: TryFromIntError(())', [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\event\sys\windows.rs:36:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\result.rs:1355
   3: enum$<core::result::Result<u32, core::num::error::TryFromIntError>>::expect<u32,core::num::error::TryFromIntError>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:997
   4: crossterm::event::sys::windows::original_console_mode
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\event\sys\windows.rs:34
   5: crossterm::event::sys::windows::disable_mouse_capture
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\event\sys\windows.rs:49
   6: crossterm::event::{{impl}}::execute_winapi
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\event.rs:288
   7: crossterm::command::{{impl}}::queue<std::io::stdio::Stdout,crossterm::event::DisableMouseCapture>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\command.rs:129
   8: helix_term::application::{{impl}}::restore_term::{{closure}}
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.21.0\src\macros.rs:66
   9: enum$<core::result::Result<mut std::io::stdio::Stdout*, std::io::error::Error>>::and_then<mut std::io::stdio::Stdout*,std::io::error::Error,mut std::io::stdio::Stdout*,closure-1>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:704
  10: helix_term::application::Application::restore_term
             at .\helix-term\src\application.rs:513
  11: helix_term::application::{{impl}}::run::{{closure}}
             at .\helix-term\src\application.rs:546
  12: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\future\mod.rs:80
  13: hx::main::{{closure}}
             at .\helix-term\src\main.rs:97
  14: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\future\mod.rs:80
  15: tokio::park::thread::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\park\thread.rs:263
  16: tokio::coop::with_budget::{{closure}}<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>,closure-0>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\coop.rs:106
  17: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\std\src\thread\local.rs:400
  18: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>>>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\std\src\thread\local.rs:376
  19: tokio::coop::with_budget
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\coop.rs:99
  20: tokio::coop::budget
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\coop.rs:76
  21: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<generator-0>>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\park\thread.rs:263
  22: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\runtime\enter.rs:151
  23: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\runtime\thread_pool\mod.rs:77
  24: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at [...]\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.12.0\src\runtime\mod.rs:463
  25: hx::main
             at .\helix-term\src\main.rs:99
  26: core::ops::function::FnOnce::call_once<fn() -> enum$<core::result::Result<tuple<>, anyhow::Error>, 1, 18446744073709551615, Err>,tuple<>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:227
```
</details>

-> When attempting to disable mouse capture without it being enabled first the `execute()!` call panics.

### Reproduction steps

1. turn off mouse support (`mouse = false` in the `[editor]` section of config.toml)
2. run helix and close it again

### Environment

- Platform: Win10 x64
- Helix version: `v0.4.1-199-g8925fdd`

I thought about making a PR to check `self.config.editor.mouse` before executing the mouse capture commands but I don't think that's a good fix, as it doesn't necessarily reflect the current state (i.e. if the program panics before the mouse was captured or if the config is changed/reloaded at runtime).

It's also surprising that `execute!()` panics internally, even though it returns a result.

**Comment by archseer** [comment]
I started looking into this, it's an issue because crossterm only calls `init_original_console_mode` if you've previously called `enable_mouse_mode`.

https://github.com/crossterm-rs/crossterm/blob/4e72bd1c7e4081ecb9d739653f583cea58882383/src/event/sys/windows.rs#L41

Looking at the logic, I think it's okay to only call disable if we previously called enable, since disable will actually revert to what the mode was before we started crossterm (https://github.com/crossterm-rs/crossterm/blob/4e72bd1c7e4081ecb9d739653f583cea58882383/src/event/sys/windows.rs#L49)

**Comment by archseer** [comment]
Opened https://github.com/crossterm-rs/crossterm/issues/613
