### ISSUE TITLE
Panic on helix-view/src/document

### ISSUE THREAD

**Issue by TripleDogDare** [helix-editor/helix#8522]
### Summary

I don't have a lot of details here. I've increased the backtrace detail in case it happens again.

#### Backtrace
```
$ hx
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `ViewId(2v1)`,
 right: `ViewId(3v1)`: Savepoint must not be used with a different view!', helix-view/src/document.rs:1278:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: helix_view::document::Document::restore
   5: helix_term::ui::completion::Completion::new::{{closure}}
   6: <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::handle_event
   7: <helix_term::ui::completion::Completion as helix_term::compositor::Component>::handle_event
   8: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   9: helix_term::compositor::Compositor::handle_event
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: tokio::runtime::park::CachedParkThread::block_on
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  13: tokio::runtime::runtime::Runtime::block_on
  14: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Reproduction Steps

None. Will update if it happens again.

1. I had a vertical split (2 panes total).
2. I don't remember precisely which thing I was doing. I remember using jump-to-reference and I save fairly frequently out of habit and the crash report indicates `SavePoint` is relevant.

### Helix log

Filtered to current day.
```
2023-10-11T12:20:31.263 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-10-11T12:20:31.267 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-10-11T16:26:36.952 helix_lsp::transport [ERROR] <- ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:26:36.952 helix_view::document [WARN] LSP formatting failed: protocol error: ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:26:45.811 helix_lsp::transport [ERROR] <- ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:26:45.811 helix_view::document [WARN] LSP formatting failed: protocol error: ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:27:10.622 helix_lsp::transport [ERROR] <- ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:27:10.622 helix_view::document [WARN] LSP formatting failed: protocol error: ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:27:26.175 helix_lsp::transport [ERROR] <- ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:27:26.175 helix_view::document [WARN] LSP formatting failed: protocol error: ServerError(0): 371:1: expected selector or type assertion, found '}'
2023-10-11T16:40:09.364 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-10-11T16:40:09.364 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-10-11T16:40:09.900 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
```

### Platform

Linux

#### Additional Platform Details
```
 ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

```
 ~ $ uname -a
Linux _ 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux
```

### Terminal Emulator

Gnome Terminal Version 3.46.8 for GNOME 43 Using VTE version 0.70.3 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 23.05 (7f5940be)

**Comment by the-mikedavis** [comment]
Most likely this was fixed on master by https://github.com/helix-editor/helix/pull/8118. If you can find reproduction steps feel free to reopen / open a new issue

**Comment by TripleDogDare** [comment]
@the-mikedavis I think you are correct. I can follow the reproduction steps in #8118 to reproduce the stack trace. Thanks.
