### ISSUE TITLE
goto definition doesn't work

### ISSUE THREAD

**Issue by stokhos** [helix-editor/helix#944]
I'm new to helix, I pressed `gd` to try to jump to the definition of a function that is in the same file.

But nothing happened. Did I miss something?

**Comment by kirawi** [comment]
Perhaps you don't have the LSP installed? Can you check your logs?

**Comment by DrunkRandomWalker** [comment]
2021-10-31T18:37:12.077 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }

I'm using pyright, and it is in PATH

**Comment by kirawi** [comment]
The default LSP for Python is `pylsp`. You'll have to change that in your [`languages.toml`](https://github.com/helix-editor/helix/blob/master/languages.toml).

**Comment by stokhos** [comment]
2021-10-31T19:12:44.964 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]}},"window":{"workDoneProgress":true}},"processId":133154,"rootUri":null},"id":0}
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "internal/modules/cjs/loader.js:905\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "  throw err;\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "  ^\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "Error: Cannot find module './dist/pyright'\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "Require stack:\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "- /home/stokhos/.local/bin/pyright\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Module.require (internal/modules/cjs/loader.js:974:19)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at require (internal/modules/cjs/helpers.js:93:18)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Object.<anonymous> (/home/stokhos/.local/bin/pyright:8:1)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Module.load (internal/modules/cjs/loader.js:950:32)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "  code: 'MODULE_NOT_FOUND',\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "  requireStack: [ '/home/stokhos/.local/bin/pyright' ]\n"
2021-10-31T19:12:45.047 helix_lsp::transport [ERROR] err <- "}\n"
2021-10-31T19:12:45.048 helix_lsp::transport [ERROR] err: <- StreamClosed
2021-10-31T19:12:45.048 helix_lsp::transport [ERROR] err: <- StreamClosed


 helix crashed and not sure why I got this error

**Comment by kirawi** [comment]
Looks like `pyright` crashed. I don't really know anything else because I don't work with Python.

**Comment by kirawi** [comment]
Maybe try another LSP and see if it works?
