### ISSUE TITLE
Panic in ropey when deleting chars with multiple selections collapsed

### ISSUE THREAD

**Issue by lisael** [helix-editor/helix#9490]
### Summary

```
❯ RUST_BACKTRACE=1 hx
thread 'main' panicked at 'assertion failed: start <= end', /home/lisael/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.2.0/src/rope.rs:601:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/panicking.rs:50:5
   3: ropey::rope::Rope::remove
   4: helix_core::transaction::ChangeSet::apply
   5: helix_view::document::Document::_apply
   6: helix_view::document::Document::apply
   7: hx::commands::insert::delete_char_backward
   8: <hx::ui::editor::EditorView as hx::compositor::Component>::handle_event
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::park::thread::CachedParkThread::block_on
  11: tokio::runtime::thread_pool::ThreadPool::block_on
  12: tokio::runtime::Runtime::block_on
  13: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
see reproduction steps for detail

### Reproduction Steps

 

I tried this:

1. `hx`
2.`iccccabcab<esc>xsab<ret><bs><bs><bs><bs>`

I expected this to happen:

the buffer contains `a`

Instead, this happened:

panic

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

xfce-terminal

### Installation Method

AUR 23.10-1

### Helix Version

helix 23.10 (hx -V panics too, searching for main.rs)

**Comment by pascalkuthe** [comment]
can not reproduce this on laster master. I suspect that you may be using an out of date version of helix somehow. This sounds exactly like the bugs that were fixed in  #6024. We even have similar testcases in our integration test suite
