### ISSUE TITLE
hx crashes when opening a C header file.

### ISSUE THREAD

**Issue by siddharthagudgunti** [helix-editor/helix#960]
Trying to open a good old header file with hx, following crash happened as below:
❯ hx ../st/config.h
thread 'main' panicked at 'Query error at 93:14. Invalid node type qualified_identifier', helix-core/src/syntax.rs:201:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction steps

[![asciicast](https://asciinema.org/a/446413.svg)](https://asciinema.org/a/446413)

### Environment

- Platform: Artix Linux WSL2 with Windows 10 
- Helix version: v0.5.0-21-g1720b98

<details>
helix.log file does not contain any info. However, RUST_BACKTRACE=full is below:

```
❯ RUST_BACKTRACE=full hx -v config.h                                                                                      
thread 'main' panicked at 'Query error at 93:14. Invalid node type qualified_identifier', helix-core/src/syntax.rs:201:29
stack backtrace:
   0:     0x555bf18e9a6c - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/li
bunwind.rs:90:5
   1:     0x555bf18e9a6c - std::backtrace_rs::backtrace::trace_unsynchronized::h6dcceebcd6a9f2ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mo
d.rs:66:5
   2:     0x555bf18e9a6c - std::sys_common::backtrace::_print_fmt::h4eacf4e9ad977499
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555bf18e9a6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e42c22572a7e7b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555bf191014c - core::fmt::write::h072b578a8e90aa54
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:     0x555bf18e3fd5 - std::io::Write::write_fmt::hc32d3cabefff1d24
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:     0x555bf18eb8d0 - std::sys_common::backtrace::_print::h058b85b6efc15780
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555bf18eb8d0 - std::sys_common::backtrace::print::hdb7de10b704104b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555bf18eb8d0 - std::panicking::default_hook::{{closure}}::h5451997d203bda2f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:     0x555bf18eb487 - std::panicking::default_hook::h419b121e68f746a2
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:     0x555bf18ebf84 - std::panicking::rust_panic_with_hook::h32c44b1364c1c247
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:     0x555bf18eba60 - std::panicking::begin_panic_handler::{{closure}}::he2e5f48fb16982d1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
  12:     0x555bf18e9f14 - std::sys_common::backtrace::__rust_end_short_backtrace::haea54a33f9e18aba
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x555bf18eb9c9 - rust_begin_unwind
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  14:     0x555bf13d4a21 - core::panicking::panic_fmt::h824e0febbdf5e655
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  15:     0x555bf17caf66 - helix_core::syntax::LanguageConfiguration::initialize_highlight::h60c33e0610863fa9
  16:     0x555bf17c4c31 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::h84db57bced71e670
  17:     0x555bf18ad850 - once_cell::imp::initialize_inner::ha49789632cda0923
  18:     0x555bf13cad0e - once_cell::imp::OnceCell<T>::initialize::h4e403213fcfd79d0
  19:     0x555bf17cb07e - helix_core::syntax::LanguageConfiguration::highlight_config::hd4f7c68627f21107
  20:     0x555bf1638743 - helix_view::document::Document::set_language::hcd3e0a70f2f122e4
  21:     0x555bf1637960 - helix_view::document::Document::open::h8d9196c26be6cdb6
  22:     0x555bf164f4ec - helix_view::editor::Editor::open::ha39e96f07424542c
  23:     0x555bf14da273 - helix_term::application::Application::new::h91ada13ae99304f1
  24:     0x555bf1426cf0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha718ad20893ce270
  25:     0x555bf140117b - tokio::park::thread::CachedParkThread::block_on::haeab704b0920ba63
  26:     0x555bf140f9bd - tokio::runtime::thread_pool::ThreadPool::block_on::hb01d15879fd0eab4
  27:     0x555bf14183d5 - tokio::runtime::Runtime::block_on::hf4a1751f05fa9420
  28:     0x555bf1403bd2 - hx::main::hac95456383f70c0c
  29:     0x555bf13fc3a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3cdfe85ba1790d83
  30:     0x555bf140ab4d - std::rt::lang_start::{{closure}}::hd40a3b5daaa99483
  31:     0x555bf18ec58a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h97e9d5f21cbee92f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:259:13
  32:     0x555bf18ec58a - std::panicking::try::do_call::hdfecd950eba8f698
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  33:     0x555bf18ec58a - std::panicking::try::h3c77c8ba3eb0735c
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  34:     0x555bf18ec58a - std::panic::catch_unwind::h8e0d62076d8d837e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  35:     0x555bf18ec58a - std::rt::lang_start_internal::{{closure}}::h647045b4c6a22e67
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:48
  36:     0x555bf18ec58a - std::panicking::try::do_call::h905d96e4a757647e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  37:     0x555bf18ec58a - std::panicking::try::hc113426beb3c908b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  38:     0x555bf18ec58a - std::panic::catch_unwind::h74f684ea7038ea12
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  39:     0x555bf18ec58a - std::rt::lang_start_internal::h5ba185919d396c97
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:20
  40:     0x555bf1403cc2 - main
  41:     0x7f2a77ebeb25 - __libc_start_main
  42:     0x555bf13d51fe - _start
  43:                0x0 - <unknown>
```

</details>

**Comment by archseer** [comment]
Are you building from source? If so, did you make sure to update to latest upstream submodules? We recently updated the `cpp` grammar (that's also used for `.h` files): https://github.com/helix-editor/helix/pull/930

You might need to run `git submodule sync; git submodule update --init` followed by `cargo clean -p helix-syntax; cargo build` to rebuild updated grammars under `runtime/grammars/*`

**Comment by sudormrfbin** [comment]
Can we run the submodule commands automatically on cargo build ?

**Comment by siddharthagudgunti** [comment]
> 
> 
> Are you building from source? If so, did you make sure to update to latest upstream submodules? We recently updated the `cpp` grammar (that's also used for `.h` files): #930
Yes.
> 
> You might need to run `git submodule sync; git submodule update --init` followed by `cargo clean -p helix-syntax; cargo build` to rebuild updated grammars under `runtime/grammars/*`
Well, tried this too. But, of no use. Same failure.

**Comment by archseer** [comment]
I can't find the commit you're on actually, `g1720b98` doesn't seem to be in the repository.

**Comment by siddharthagudgunti** [comment]
> 
> 
> I can't find the commit you're on actually, `g1720b98` doesn't seem to be in the repository.

When I pulled today it was https://github.com/helix-editor/helix/tree/1720b98760eb5958a31bc6e2b88564dbf5bf63e5

**Comment by siddharthagudgunti** [comment]
Got the issue. It is with the latest runtime queries. The runtime queries added at commit # a1c7e55e3be95be6769d3a08518c8a41c257016f are causing the problem.

**Comment by archseer** [comment]
Yeah it's part of #930 which updated both the queries and the grammar. I did a full rebuild and can't replicate the problem. It did show up when I had an outdated grammar

**Comment by archseer** [comment]
Maybe try doing the steps above again but manually deleting all the grammars in runtime/grammars/* first? To make sure it definitely rebuilt.

**Comment by siddharthagudgunti** [comment]
> 
> 
> Maybe try doing the steps above again but manually deleting all the grammars in runtime/grammars/* first? To make sure it definitely rebuilt.

This worked. Thanks.
Now, I think @sudormrfbin 's suggestion is good. Can we add a target (similar to make files) in cargo to do refresh and build?
